### ISSUE TITLE
HowTo: Docker Commands

### ISSUE THREAD

**Issue by wildmolasses** [TrueBlocks/trueblocks-core#1342]
Instead of executing the entrypoint, run the container in bash mode:
```
docker-compose run --entrypoint bash trueblocks.public.dappnode.eth
```

Delete volumes (persistent data aka indexes)
```
docker-compose down --volumes
```

Rpc provider on wildmolasses:
RPC_PROVIDER=172.17.0.1:8545

**Comment by tjayrush** [comment]
Closing as dup of #1349
