### ISSUE TITLE
Startup

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#1514]
Need etherscan API key
Need blooms and index chunks
Need to point index pointer to the index
Need a way to start the scraper
Need an Ethereum RPC end point

env TEST_MODE=true getBlock --force 4369999

chifra list 0xf503017d7baf7fbc0fff7492b751025c6a78179b
chifra list 0x05a56e2d52c817161883f50c441c3228cfe54d9f
chifra list 0xd2f5852eb4b0c12c23a97914b2a9d954cf621781
chifra list 0xfdecc82ddfc56192e26f563c3d68cb544a96bfed
chifra abis 0x314159265dd8dbb310642f98f50c066173c1259b

**Comment by tjayrush** [comment]
This is all fixed.

**Comment by cesarvspr** [comment]
How can I put my API KEY on the first usage? I'm having trouble with this.

**Comment by MattDodsonEnglish** [comment]
@cesarvspr Can you try these instructions from the docs? https://docs.trueblocks.io/docs/prologue/installing-trueblocks/#3-update-the-configs-for-your-rpc-and-api-keys

At the bottom of the page, there is also a troubleshooting section to you find your config file. Let us know if that helps!
