### ISSUE TITLE
Ethslurp - Need help

### ISSUE THREAD

**Issue by 0xChupaCabra** [TrueBlocks/trueblocks-core#1518]
Helllo!
I'm new to this tool and I've just compile it after setting up my geth node.
Everything is working fine, except for ethslurp. After running it for the first time it never asked me for my etherscan api key. 
I have tried to add 
api_key = "myapikey" in the ethslurp.toml file  , as i saw at this link: http://ethslurp.com/doc_config.html 
f but ethslurp keeps quitting with this message:
 Warning: This program requires an api_key from Etherscan. See http://api.etherscan.io/apis. Quitting...

Can anyone help me to understand what i am doing wrong?
thank you very much and sorry for the stupid question

**Comment by tjayrush** [comment]
Nice to have you.

In the file called `$HOME/.quickBlocks/quickBlocks.toml` add an entry thus:

```
[settings]
etherscan_key = "YOUR KEY"
```

If there's already a settings section add your key there. If not, add the section.

I've written an issue against the docs, which appear to be mistaken.

Not a stupid question at all. Stupid documentation.

**Comment by tjayrush** [comment]
Here's the issue: #1519
