### ISSUE TITLE
blockScrape --monitor is probably broken (--daemon mode)

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#1533]
Search for "FRESHEN_FLAG"

**Comment by tjayrush** [comment]
Also -- my old nemesis -- multiple running versions of blockScrape / acctExport running at the same time may need re-testing.

We used to test to see if `acctScrape` was running and made `blockScrape` go to sleep but we remove `acctScrape` and now test of `acctExport` running. May not really work as it used to.

This is a hard problem.

**Comment by tjayrush** [comment]
This isn't broken. Never was actually.

**Comment by jtjunior09** [comment]
Hello @tjayrush- sorry to comment on a closed Issue, but I'm not seeing monitors being updated with `chifra scrape both` or `chifra scrape monitors`. I tested this by adding a monitor for Uniswap (which as we all know is incredibly active), but the latest appearance in `chifra status monitors --details` is staying on the block number that the monitor was added on, similarly in the cache `0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45.last.txt` isn't getting updated.

The scraping output for monitors just shows
trueblocks-chifra-scrape[137471]: INFO[04-02|19:25:04.206]  MonitorScraper : [ sleep  -->  wake ]
trueblocks-chifra-scrape[137471]: INFO[04-02|19:25:04.206]  MonitorScraper : [ wake  -->  sleep ]

**Comment by tjayrush** [comment]
No problem. The reason it's not updating is because that code has been temporarily disabled as it wasn't quite working correctly. The commented out code is here: https://github.com/TrueBlocks/trueblocks-core/blob/master/src/apps/chifra/internal/scrape/output.go#L135.

You can uncomment it, but I'm not 100% sure it will work correctly. I don't remember exactly what wasn't working right, but I do know we've re-written a good portion of it with better code that is also not ready.

Unfortunately.

Not sure if you have time or inclination to fix it with us, but if you're interested hit us up in the discord. I can show you parts of what has to be done to re-enable it. Without that type of help, it may take a while to get that code back in service as it's a bit on the back burner.
