### ISSUE TITLE
Chifra scrape on ubuntu box reports 'scraper already running'.

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#1546]
On an ubuntu box enter:

```
chifra scrape
```

It reports that the scraper is already running, which is not true. Can't scrape.

**Comment by srgank** [comment]
kristina@kristina-Lenovo-ideapad-110-15ISK:~/project/trueblocks-core/bin$ ./chifra  scrape
00219551 ( 219551)- <ERROR> : blockScrape is already running. Cannot run.
{ "status": "running" }
kristina@kristina-Lenovo-ideapad-110-15ISK:~/project/trueblocks-core/bin$ 

Error comes from function in file blockScrape/options.cpp
//--------------------------------------------------------------------------------
ScrapeState COptions::getCurrentState(void) {
    if (controlFile.empty())
        controlFile = configPath("cache/tmp/scraper-state.txt");
    stateStr = asciiFileToString(controlFile);
    if (stateStr == "running")
        state = STATE_RUNNING;
    else if (stateStr == "paused")
        state = STATE_PAUSED;
    else {
        state = STATE_STOPPED;/home/kristina/.quickBlocks/cache/tmp/scraper-state.txt
where was stored "running" string
        stateStr = "stopped";
    }
    LOG4("The scraper was ", stateStr, ".");
    return state;
}

i locate mentioned file scraper-state.txt in my folder
/home/kristina/.quickBlocks/cache/tmp/scraper-state.txt
where was stored "running" string.

function bool COptions::changeState(void) seems that change status without of checking running status.

**Comment by tjayrush** [comment]
Hey @srgank Thanks so much for looking into this. This particular function has always been a real troubling part of my code. The basic function that doesn't really work right is making sure that `chifra scrape` does not run more than once -- and -- it has to work on both Linux and Mac (and eventually Windows I guess).

We write that temp file the first time `chifra scrape` starts and then capture the user's Control+C and clean it up (You'll see that the first line of every TrueBlocks program register's a quitHandler whose job it is to clean up when the user hits Control+C. Overall, I would say this work really well.

Sometimes though, especially on Linux, that file does not seem to get cleaned up.

We have to paths I suppose:

1. Try to figure out why the file is not being cleaned up when `chifra scrape` is killed, or
2. (Preferred) come up with a better way to ensure that `chifra scrape` never runs twice.

This is a standard, old problem in C++ that I'm sure must have a much better solution than writing a file, but I've never been able to find one that cross platform.

Perhaps you know of a good solution.

**Comment by tjayrush** [comment]
We put a much better message explaining this situation and directing the user how to correct the problem. Plus, we've started a new version of the scraper which will totally change the way the scraper is started/stopped/paused, so this issue will fully disappear when that code rolls out. Closing this.
