### ISSUE TITLE
Chifra Explore

### ISSUE THREAD

**Issue by cgallic** [TrueBlocks/trueblocks-core#1558]
**Describe the bug**
When using chifra explore: 

error shows: sh: 1: ethscan.py: not found

**To Reproduce**
I just run chifra explore

**Screenshots**
[Add screenshots to help explain your problem:]

**Desktop (please complete the following information):**
Ubuntu 20.04
QuikNode Full Parity Node

**Additional context**
[Add any other context about the problem:]

**Comment by tjayrush** [comment]
This is almost definitely a problem with your shell's PATH.

For this to work not only `./trueblocks-core/bin` must be in your path, but also `./trueblocks-core/bin/test/`.

Let me know if that works so I can close this bug.

Thanks for reporting it.

**Comment by cgallic** [comment]
It's fixed you can close
