### ISSUE TITLE
Store data in a correct location per OS.

### ISSUE THREAD

**Issue by LefterisJP** [TrueBlocks/trueblocks-core#1587]
Storing data in ~/.XXX is generally discouraged as it pollutes the home directory. Apps should be good citizens of the OS they run in and store data in the expected locations.

Expected directory differs per OS. We already do something like that in rotki so perhaps this function could be of help: https://github.com/rotki/rotki/blob/88760576331e63e2c92eb8473debcdd61639c393/rotkehlchen/config.py#L36-L60

**Comment by tjayrush** [comment]
Thanks @LefterisJP You're the second person to say this. I'll make this a top priority since you a friend 😄

**Comment by LefterisJP** [comment]
Tbh I personally don't mind THAT much. But it's a good idea to do and as more people use trueblocks you will hear it more. And it's one of those things the earlier you do the better.

**Comment by tjayrush** [comment]
This is done. I'd love if you can confirm that the instructions to migrate (here https://github.com/TrueBlocks/trueblocks-core/tree/master/src/other/migrations) work for you and report any problems.

If you pull the latest code and rebuild, `chifra` will refuse to run and point you to that page until you complete the migration.

**Comment by tjayrush** [comment]
Assuming this works. We have at least one successful migration.
