### ISSUE TITLE
Standarize naming convention of tools

### ISSUE THREAD

**Issue by MattDodsonEnglish** [TrueBlocks/trueblocks-core#1593]
Some are singular and some plural.
`ethslurp` isn't camel case.

Some ideas at standardizing:

All object nouns plural. E.g.:
* getBlocks
* whenBlocks
 
And all subject/status nouns singular
 * pinMan[ager]
 * cacheStatus
 
All verbs bare infinitive (i.e. without to; ~~to~~ go) [chifra only, ignore underlying go tool names, like blaze)
 * chifra scrape 
 * chifra serve
 *

**Comment by tjayrush** [comment]
Changed `ethQuote` to `getQuotes` to get started...

I'm going to try to change the rest this weekend, but I think one of them (`getTrans`) will be an exception. I don't want to use `getTransactions` nor do I want `getTranses` or whatever the plural would be there. So it will stay `getTrans`.

**Comment by tjayrush** [comment]
Removed `tokenTool` and `turboDive` as both were not complete and didn't really need to be there.

**Comment by tjayrush** [comment]
Changed `getTokenInfo` to `getTokens`

**Comment by tjayrush** [comment]
Changed `getBlock` to `getBlocks` and `getTrace` to `getTraces`

**Comment by tjayrush** [comment]
I think I'm done changing the names of the tools. This is what they look like now:

![image](https://user-images.githubusercontent.com/5417918/116767588-20fae400-a9ff-11eb-8a03-5617bd4c8ba8.png)

It's not perfect, but I think it's better than it was. These names feel good to me.

I didn't change anything in the apps folder. That folder looks like this:

![image](https://user-images.githubusercontent.com/5417918/116767630-5d2e4480-a9ff-11eb-8034-adaa5b465d10.png)

**Comment by tjayrush** [comment]
@MattDodsonEnglish  I think we can close this issue for now. Further changes would take more effort than they're worth.

**Comment by MattDodsonEnglish** [comment]
All looks good to me, but do you want to keep ethslurp all lower?

**Comment by tjayrush** [comment]
We tried to do this a number of years ago, but ran into problems.

This program is about two years older than many of the others. This means that more people have it running in the wild (inside of shell scripts, etc.) Catching up to and fixing those would be impossible.

On some operating systems, upper case / lower case doesn't matter, so it won't break. On others it would break.

We'll just live with it. Once we 'fully decentralize' all connections to EtherScan will disappear anyway.
