### ISSUE TITLE
swagger.yaml file has two validation errors

### ISSUE THREAD

**Issue by MattDodsonEnglish** [TrueBlocks/trueblocks-core#1605]
Both are about empty `parameters` objects. The fix is easy; either remove the parameters object, or add some parameters. But it can't be empty. This will fail for stricter documentation generators. (I just discovered it testing the docs with redoc)

The error occurs for the following two operations:

* accounts-list : https://github.com/TrueBlocks/trueblocks-core/blob/master/docs/swagger.yaml#L245
* accounts-rm: https://github.com/TrueBlocks/trueblocks-core/blob/03a068cfee2d1a81b9e181fccc401037fb09fb88/docs/swagger.yaml#L493

**Comment by tjayrush** [comment]
Fixed with recent commit fd9fef0b0c7f0edee3d467c586583c59e1ce4856.

You can close this issue if you agree.

Can I ask you what tool you used to validate the file? Swagger hub?
