### ISSUE TITLE
Nix build does not copy installable files as on other operating systems

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#1614]
A user reports that when building on Nix, certain files (names.tab, prefunds.txt) are not installed in the $CONFIG folder. This is because "Nix is strict about" copying files during the build.

Another user previously reported that we "shouldn't be copying files on install."

This may be the reason.

Simple solution -- if the file doesn't exist, create it on first read (there are a few different places where this has to happen: Known ABIs, Known Names, etc.

I don't like putting hard coded stuff like this in the source code, but it may be the only way.

We don't like the idea of downloading something from the Internet (security issue). We could use IPFS, but then how is it updated? Not the simplest problem.

Perhaps we have a 'supplemental' build for Nix (or supplemental README section) that instructs user on how to hand-copy the needed files.

**Comment by d-xo** [comment]
The issue with nix is not so much copying files during build time, but rather lies with the requirement that the output of nix builds be immutable. I think that a clearer distinction between immutable data (templates etc.), mutable data (names db), and user config (`trueBlocks.toml`) would solve the issue.

In general I have no issue with the build system delivering immutable data as part of the install process. The issue really is only with the mutable data (names db) and user config (`trueBlocks.toml`). If these two pieces of state only can be created if needed under `$XDG_DATA_HOME/trueblocks` for the names db, and `$XDG_CONFIG_HOME/trueblocks` for `trueBlocks.toml`, then everything should work fine under nix (assuming that the application knows to also check `$XDG_DATA_DIRS` as well as `$XDG_DATA_HOME` for the immutable data files).

As a final minor point, I think in general the build / install phases are a little mixed together in the current build system. This is more an issue of convention and style.

**Comment by MattDodsonEnglish** [comment]
Hey @xwvvvvwx , thanks for your input.

If you ever have time, do you mind providing an example of what you meant here?  

> As a final minor point, I think in general the build / install phases are a little mixed together in the current build system. This is more an issue of convention and style.

You might be able to illuminate something we ourselves haven't seen.

**Comment by d-xo** [comment]
Right now calling `make` installs a bunch of files into `~/.local/share/trueblocks`, this would IMO be done more conventionally as part of a seperate `make install` step. My cmake is *very* rusty, but I think the [`install`](https://cmake.org/cmake/help/latest/command/install.html) command could be useful here.

**Comment by tjayrush** [comment]
@d-xo May I close this?

**Comment by d-xo** [comment]
Has the issue been fixed?

**Comment by tjayrush** [comment]
Closing as stale.
