### ISSUE TITLE
cmake ../src fails on windows, can't find curl path

### ISSUE THREAD

**Issue by deeayeen** [TrueBlocks/trueblocks-core#1622]
I tried setting up for Windows, I installed all prerequisites, and failed when running cmake ../src looks like I had issues getting the libcurl path recognized

To reproduce:
mkdir build && cd build
cmake ../src

![image](https://user-images.githubusercontent.com/35680780/119551512-644c3680-bda2-11eb-817f-703ab4e4f44c.png)

**Comment by davidfsol5** [comment]
I've successfully built trueblocks-core and run chifra using Windows Subsystem for Linux (WSL). It just worked--no problems. I've never tried building in native Windows. Curl has been distributed in Windows for a while now, but are the make files Windows compatible?

**Comment by tjayrush** [comment]
Thanks so much for trying. Concerning the CMake files, my guess is that they are not Windows compatible -- I haven't seen the keyboard side of a Windows computer since prior to Y2K. I wouldn't even know where to begin.

It would be amazing if you'd like to make a PR fixing that situation. Thanks.

**Comment by tjayrush** [comment]
@davidfsol5 I am going to close this? We're not currently supporting native Windows. I sounds like it build otherwise.
