### ISSUE TITLE
getUserName can return uninitialized memory

### ISSUE THREAD

**Issue by grahamc** [TrueBlocks/trueblocks-core#1630]
I noticed that the /status API endpoint will sometimes emit raw bytes, and tracked it down to getUserName:

https://github.com/TrueBlocks/trueblocks-core/blob/fe94cf03d46df15229bcfce3a7126bb62b953c6d/src/libs/utillib/sfos.cpp#L309-L317

It looks like the return value of `getlogin_r` should be checked to see if it is zero, and on non-zero handle the case and return some type of initialized memory.

**Comment by grahamc** [comment]
Here is another case of the same issue: https://github.com/TrueBlocks/trueblocks-core/blob/master/src/apps/cacheStatus/options.cpp#L224-L235

**Comment by andir** [comment]
You can get rid of the `memset(username, 0, LOGIN_NAME_MAX);` if you always initialize your stack memory with zeros:
```
char username[LOGIN_NAME_MAX] = { 0 };
```

Also make sure that the LOGIN_NAME_MAX is always define. You are only defining it if the hostnames max length isn't already defined.

**Comment by tjayrush** [comment]
@andir This is great. I don't think that syntax existed when this code was originally written. I'm happy to make the change, but you're welcome to if you like. Let me know. @grahamc Thanks for finding it.

**Comment by tjayrush** [comment]
Fixed.
