### ISSUE TITLE
Multiple errors cause malformated JSON response

### ISSUE THREAD

**Issue by dszlachta** [TrueBlocks/trueblocks-core#1638]
When multiple errors come from the single endpoint, the response is not a valid JSON:
```
{ "errors": [ "trueBlocks - Could not open prefunds data." ] }
{ "errors": [ "The Ethereum node (https://api.archivenode.io/6xtotjgakuo2m07lsjt1j6xtot8ho41i) returned an empty response." ] }
```
It should be 
```
{ "errors": [
  "trueBlocks - Could not open prefunds data." ,
  "The Ethereum node (https://api.archivenode.io/6xtotjgakuo2m07lsjt1j6xtot8ho41i) returned an empty response." 
] }
```

**Comment by tjayrush** [comment]
Can you document which request causes this multiple error? Like, what's the curl command? So I can re-produce it.

**Comment by dszlachta** [comment]
I just did `GET /status` like so: curl localhost:8080/status.
But, I'm using dockerized core so I guess it is an issue with the configuration

**Comment by tjayrush** [comment]
This code generates the errors: https://github.com/TrueBlocks/trueblocks-core/blob/master/src/libs/etherlib/node.cpp#L1086.

I'm traveling today, so if you wish you can try to hack something to fix it (for example, only return a single error by breaking out of the loop after going through once, here: https://github.com/TrueBlocks/trueblocks-core/blob/master/src/libs/etherlib/node.cpp#L1111.

I'll fix it this weekend for real.

**Comment by tjayrush** [comment]
I am going to close this as a dup of #1672.
