### ISSUE TITLE
chifra abis - allow easier adding of function/event/parameter lists to chifra abis --find

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#1647]
Currently, if we want to add a function name, event name, or parameter name to the files used by `chifra abis --find`, we have to hand edit. It would be easy to add an option to update those files through the command line. Something like

```
chifra abis add --function <function_name>,
chifra abis add --event <event_name>, or
chifra abis add --params <param_list>
```

**Comment by perama-v** [comment]
So this would be for a user who is working with a particular contract, where the contract ABI is missing an element (no signature -> name map). If the user knew the name, they could `chifra abis add` and that would save it locally for future use?

**Comment by tjayrush** [comment]
Yes. That would save it locally for future use, but at some point it would be cool if those new signatures could be shared with the community at large in a way that is (a) automatic, and (b) free, and (c) not fakable. With signatures and four-bytes the seems possible using technics we've seen in the [local-first article](https://www.inkandswitch.com/local-first.html). With names/address pairs, it's not so simple.

**Comment by tjayrush** [comment]
chifra abis --find is on hold. Closing until needed.
