### ISSUE TITLE
Tracing check on non-mainnet chains will never work

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#1648]
If we're running on a non-mainnet chain, this function:

https://github.com/TrueBlocks/trueblocks-core/blob/develop/src/libs/etherlib/node.cpp#L770

Will always fail because only on mainnet does the test transaction have 23 traces. We should come up with a better way than telling people to add an entry in `blockScrape.toml` of

```
[requires]
tracing = false
```

**Comment by perama-v** [comment]
For further context, on Goerli, with `.toml` modified to include:
```
[requires]
testing = false
```
The call `chifra blocks 5062611` returns data normally, but the call with traces `chifra blocks 5062611 -t` returns:
```
{ "data": [] }
```
As do all calls to `chifra traces`.

**Comment by tjayrush** [comment]
> For further context, on Goerli, with `.toml` modified to include:
> 
> ```
> [requires]
> testing = false
> ```
> 
> The call `chifra blocks 5062611` returns data normally, but the call with traces `chifra blocks 5062611 -t` returns:
> 
> ```
> { "data": [] }
> ```
> 
> As do all calls to `chifra traces`.

I just noticed there used to be a mistake above. It said to set `testing` to false. It should have said set `tracing` to false. I corrected the above.

Are you sure you're running against a tracing node? Can you run a `curl` command against the same node using `trace_block` for example?

**Comment by tjayrush** [comment]
There's another option that you can turn off if trying to run against a non-mainnet node. See below.

**Comment by tjayrush** [comment]
There are two options you can set to disable checks for tracing and archive node on other chains. In a file `$CONFIG/blockScrape.toml` make these settings:

```
[requires]
tracing = false
archive = false
```

**Comment by tjayrush** [comment]
This issue is actually fixed, but I also copied it into the multichain.md file to keep double track. Okay to close.
