### ISSUE TITLE
long fetching transactions doesn't quit if server dies

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#1663]
Load an address with a lot of transactions (>4000) that has not been reconciled, so it takes a long time to load

In the terminal window, kill the server

The UI will spin wildly reporting errors instead of just going into some sort of more where it recongnizes that its in trouble and stops asking until the user does something to fix the problem.

**Comment by dszlachta** [comment]
I can check this one. @tjayrush could you assign it to me?

**Comment by tjayrush** [comment]
I'm going to close this. I'm sure this will get fixed because if it doesn't the whole thing doesn't work right. Closing.
