### ISSUE TITLE
Chifra `list` and `monitors` show incorrect help text 

### ISSUE THREAD

**Issue by samueldg** [TrueBlocks/trueblocks-core#1665]
Both `chifra list --help` and `chifra monitors --help` show the following help text.

```
  Usage:    chifra monitors [-p|-r|-l|-t|-C|-a|-i|-R|-y|-U|-c|-e|-v|-h] <address> [address...] [topics] [fourbytes]
  Purpose:  Export full detail of transactions for one or more addresses.

  Where:
	addrs                 one or more addresses (0x...) to export (required)
	topics                filter by one or more log topics (only for --logs option)
	fourbytes             filter by one or more fourbytes (only for transactions and trace options)
	-p  (--appearances)   export a list of appearances
	-r  (--receipts)      export receipts instead of transaction list
	-l  (--logs)          export logs instead of transaction list
	-t  (--traces)        export traces instead of transaction list
	-C  (--accounting)    export accounting records instead of transaction list
	-a  (--articulate)    articulate transactions, traces, logs, and outputs
	-i  (--cache_txs)     write transactions to the cache (see notes)
	-R  (--cache_traces)  write traces to the cache (see notes)
	-y  (--factory)       scan for contract creations from the given address(es) and report address of those contracts
	    (--emitter)       for log export only, export only if one of the given export addresses emitted the event
	    (--source <addr>) for log export only, export only one of these addresses emitted the event
	    (--relevant)      for log and accounting export only, if true export only logs relevant to one of the given export addresses
	-U  (--count)         only available for --appearances mode, if present return only the number of records
	-c  (--first_record <num>)the first record to process
	-e  (--max_records <num>)the maximum number of records to process before reporting
	    (--clean)         clean (i.e. remove duplicate appearances) from all existing monitors
	-v  (--verbose)       set verbose level (optional level defaults to 1)
	-h  (--help)          display this help screen
```

Which is the help for `chifra export`.

Seems similar to https://github.com/TrueBlocks/trueblocks-core/issues/1652, but for different commands.

**Comment by tjayrush** [comment]
These two issues happen for the same reason. Underlying `chifra` are the individual commands (`getBlocks`, `ethNames`, `acctExport`, etc.) In most cases a command (such as `chifra blocks`) is a straight translation from `chifra` to the underlying commands, so we can just pass the command line options across.

In the case of `chifra list` and `chifra monitors` the `chifra` command is an alias as opposed to a passthrough, so there is no underlying command to run (other than `acctExport`). This is why you see the help for `export`.

Same thing with `chifra init` which is an alias for `chifra pins --init`.

The solution is sort of easy but sort of hard. We just have to intercept these alias commands in the `./src/apps/chifra/options.cpp` and print the correct help text. The hard part is that the 'command line code' is auto-generated, so I've avoided fixing this until I can figure out how to automate the 'aliased' commands.

If anyone is interested, this might be a good starting point type of option to get started.

**Comment by tjayrush** [comment]
This now works as it should

**Comment by samueldg** [comment]
Thanks @tjayrush !
