### ISSUE TITLE
chifra init requires etherscan key - why?

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#1675]
One of the first things a new user does is

```
chifra init
```

If they have not previously entered an EtherScan key, TrueBlocks reports

```
Articulation requires an api_key from EtherScan
```

This is a very disconcerting message from a system that claims "We are 100% decentralized."

This happens because during `chifra init` we need to read and articulate the result from a query to the unchained index smart contract. Since we already know that contract's source code (we wrote it), there should not be any need for an ABI. We already have it.

To reproduce:

Edit the $CONFIG/trueBlocks.toml file and comment out the etherscan_key entry.
Run `chifra init`.

**Comment by defi-caratacus** [comment]
I would like to plus 1 this. Would be really cool to lose the etherscan requirement.

**Comment by tjayrush** [comment]
Closing.
