### ISSUE TITLE
1682 or 1679 broke dev branch build

### ISSUE THREAD

**Issue by davidfsol5** [TrueBlocks/trueblocks-core#1683]
/opt/github/trueblocks-core/src/libs/etherlib/reconciliation.cpp: In member function ‘bool qblocks::CReconciliation::reconcileEth(const qblocks::CReconciliation&, qblocks::blknum_t, const qblocks::CTransaction*, const address_t&)’:
/opt/github/trueblocks-core/src/libs/etherlib/reconciliation.cpp:944:16: error: zero-length gnu_printf format string [-Werror=format-zero-length]
  944 |         printf("");

I changed Line 944 to "         printf("%s", "");" locally to placate my compiler. What's the purpose of printing an empty string?

**Comment by tjayrush** [comment]
Sorry about that. We're working on automating the building and testing. A fix is coming soon. I'll close this when it's posted. We use the printf("") to set breakpoints during debugging. Usually gets removed.

**Comment by tjayrush** [comment]
This should be fixed, now.
