### ISSUE TITLE
blockScrape: chifra scrape -s (--sleep) flag doesn't work

### ISSUE THREAD

**Issue by davidfsol5** [TrueBlocks/trueblocks-core#1686]
chifra scrape --help lists a -s (--sleep) <double> flag for setting the number of seconds to sleep between passes.
When I tried it, I got the following error:
chifra scrape -s 3
unknown shorthand flag: 's' in -s
Usage of flame:
      --monitor       enable monitor scraper mode
      --port string   specify the server's port (default ":8080")
      --scrape        enable block scraper mode
      --verbose int   verbose level (between 0 and 10 inclusive)
unknown shorthand flag: 's' in -s
Same result for chifra scrape --sleep 3

Also, chifra scrape --help requires a functional rpc connection to an Ethereum client in order for the help message to show.

**Comment by tjayrush** [comment]
Closed with https://github.com/TrueBlocks/trueblocks-core/pull/1732
