### ISSUE TITLE
The documentarion example ethslurp -f:csv  0x713B73c3994442b533e6A083eC968e40606810Ec  doesn't works

### ISSUE THREAD

**Issue by cesarvspr** [TrueBlocks/trueblocks-core#1691]
# No support for -f:csv command 

`
ethslurp -f:csv  0x713B73c3994442b533e6A083eC968e40606810Ec
`

### What I get: 
`
Invalid option: -f:csv
`

**Comment by tjayrush** [comment]
Thanks so much for reporting this. This is a documentation error. It should say:

```
ethslurp --fmt csv 0x713B73c3994442b533e6A083eC968e40606810Ec
```

Further, while this way of running the command works, the preferred way to run individual tools is through the 'chifra' command line. In that case, the command translates to:

```
chifra slurp --fmt csv 0x713B73c3994442b533e6A083eC968e40606810Ec
```

If you just do `chifra`, you can see all the available commands.

**Comment by tjayrush** [comment]
Can you tell me where you found that documentation? I'd like to correct it. I searched our repo, and I can't find it.

**Comment by cesarvspr** [comment]
Thank you so much for your answer. 

Here is where I found the wrong command: http://www.ethslurp.com/

**Comment by tjayrush** [comment]
Oh. Thanks. That's a very, very old website. The new docs are here: http://docs.trueblocks.io (and the help page for `chifra slurp` is here: https://docs.trueblocks.io/docs/chifra/other/#chifra-slurp).

I'm going to close this. If you need further help, please feel free to either open a new issue or re-open this one.

**Comment by cesarvspr** [comment]
Oh I can imagine. 

Btw, would you mind help me with [this question](https://ethereum.stackexchange.com/questions/106991/how-to-request-more-than-5k-records-from-a-contract/106995#106995)?
