### ISSUE TITLE
make test-all always returns success exit code

### ISSUE THREAD

**Issue by dszlachta** [TrueBlocks/trueblocks-core#1692]
`make test-all` exits with 0 (success) even if some of the tests have failed

**Comment by tjayrush** [comment]
This line here: https://github.com/TrueBlocks/trueblocks-core/blob/master/src/dev_tools/testRunner/main.cpp#L140 can be inserted before this line here: https://github.com/TrueBlocks/trueblocks-core/blob/master/src/dev_tools/testRunner/main.cpp#L175 to fix this.

I would do this normally, but I'll let you do it as part of testing the continuous integration.

**Comment by tjayrush** [comment]
This should be working now.
