### ISSUE TITLE
Build: Config/Data directory needs a README

### ISSUE THREAD

**Issue by MattDodsonEnglish** [TrueBlocks/trueblocks-core#1718]
I think an in-directory README would help demystify a few things. Off the top of my head, a few items that I think would be useful are:

* A top level description of key files therein
* Some HOWTOs for customization, e.g. "How can a user add their own names?"
* A explanation of the Timestamp files, along with a instructions about what is and isn't safe to delete
* A reference of all possible parameters in the config?

Maybe there are some other important things too. When this is done, perhaps it could be added to the README cat and synced to the docs site too.

**Comment by tjayrush** [comment]
Closing, as stale.
