### ISSUE TITLE
Should transactionindex be transactionIndex?

### ISSUE THREAD

**Issue by MattDodsonEnglish** [TrueBlocks/trueblocks-core#1719]
I noticed a discrepancy when running `chifra transactions` (transactionIndex) and `chifra monitor` (transactionindex). If I'm not mistaken, don't both refer to the same data field? 

`grep -r transactionindex` returns many results. Mostly in `test`, but a few in `bin` and one in `src`. Is this correct, or should it be camelCase?

**Comment by tjayrush** [comment]
This is now fixed!!! Thanks @MattDodsonEnglish
