### ISSUE TITLE
Improve Documentation Site sync and publication

### ISSUE THREAD

**Issue by MattDodsonEnglish** [TrueBlocks/trueblocks-core#1741]
Some thoughts on how to make the documentation site workflow simple and automated.

## Constraints:
 
 - The source for the reference documentation lives in `trueblocks-core`. This is important for a single source of truth.
- The source for the documentation site lives in `trueblocks-docs`. This avoids shipping a website when users want a CLI application.
- The docs site gets multiple contributors, as of today, 6 humans and 1 robot.

## Current problems

Right now, the core <--> docs sync happens manually.
Jay updates the core reference, then runs a script that copies the code to docs.

Publishing also happens manually--whenever a user with permissions runs the rsync script.
There is no sync between when the repo was updated and when trueblocks.io was updated.
The site may be later than the repo, may be earlier─all depends on whenever the person ran the script from their local environment. With multiple contributors, very hard to keep track of what's the latest. There is also no record of publications, making it much harder.

The two publish scripts, `copy-from-core.sh` and `publish.sh`, are not generalized and not efficient.
`Copy-from-core` has hardcoded paths, and `publish.sh` (if it calls copy-from-core), gets all core reference docs every time,
regardless of whether or not those reference files have changed.

## Proposed solution

I think there are two issues:
1. Sync Core <--> docs every time core reference docs update.
2. Sync Docs <--> `trueblocks.io` every time the docs-repo changes.

One idea would be to:
1. Use a github action to automatically push to `trueblock-docs` anytime a file in `trueblocks-core/docs` changes.
  This should work: https://github.com/dmnemec/copy_file_to_another_repo_action
2. Use a Github action that, on every build:
  2.1 Runs Hugo
  2.2 Runs rsync to sync with the Ubuntu box

Solution 2 may require a little more custom work, but this blog seems to cover most of the same ideas https://zartman.xyz/blog/gh-static-deploy/

### Limitations

Here are some limitations I see:

* We'd have to put the YAML docs headers in `trueblocks-core` and make PRs to core every time we wanted to update part of that site
* Dependent on github actions; if those go down, nothing syncs.
* The core-docs sync may over copy, granular control of the exact file could be  a little more tricky.

Nevertheless, it's the best idea I can think of.

What do you think? Do you have any ideas?

**Comment by tjayrush** [comment]
Thanks for the discussion, Matt.

Question:

What are the 'YAML docs headers'? Is that the openapi.yaml file or more than that?

I don't see having to make PRs against the core every time we want to sync the Hugo site as a problem. I see it as a result of wanting a single source of truth. Plus -- this is only for the auto-generated parts of the Hugo site. So only if we change auto-generated things would there need to be a PR. Isn't that right?

Oh -- maybe now I understand what you mean by YAML docs headers. By "headers" to you mean the introductory text at the top of the files that contain the command line options and/or the data_model code? If yes, then this is going to have to be the case since one of the outputs of the auto-generation process is the README.md files in each tool/app of Core.

**Comment by tjayrush** [comment]
Also, I wouldn't worry at all about 'efficiency'. Yes, we're over copying file that don't need to be copied, but it literally takes less than a second, so optimizing for speed over ease of programming is wasted effort. Please don't spend time fixing the non-problem of copying too many files.

**Comment by MattDodsonEnglish** [comment]
>What are the 'YAML docs headers'? Is that the openapi.yaml file or more than that?

Sorry, I was imprecise. I meant to write YAML front matter. They are little headers in the .md files that define some configurations for how that page appears on the site. For example, here's chaindata's front matter.

Any way it doesn't matter that much. The frontmatter only changes when I do structural changes, like when I flattened out the `/docs` section.

```
---
title: "Blockchain Data"
description: "TrueBlocks is build on blockchain data. This reference guides you."
lead: "It all starts with transactions and addresses"
date: 2021-07-06T10:43:22-03:00
lastmod:
  - :git
  - lastmod
  - date
  - publishDate
draft: false
images: []
menu:
  data:
    parent: collections
weight: 2050
toc: true
---
```

**Comment by MattDodsonEnglish** [comment]
I'm going to experiment on my fork with this:
> Use a github action to automatically push to trueblock-docs anytime a file in trueblocks-core/docs changes. This should work: https://github.com/dmnemec/copy_file_to_another_repo_action 

And I agree with this,
> Also, I wouldn't worry at all about 'efficiency'. Yes, we're over copying file that don't need to be copied, but it literally takes less than a second, so optimizing for speed over ease of programming is wasted effort. Please don't spend time fixing the non-problem of copying too many files.

Especially since git will only recognize files that really change.

----
The other thing that I realized is that, longer term, when there is a package that users can download, so only people interested in developing on the site will clone the repo, then we can possibly merge `core` and `docs` into one mono-repo, which would further simplify things.

**Comment by tjayrush** [comment]
> The other thing that I realized is that, longer term, when there is a package that users can download, so only people interested in developing on the site will clone the repo, then we can possibly merge core and docs into one mono-repo, which would further simplify things.

I think this is probably the long term best solution. We already have a `./docs` folder in the `core` repo, so it has a natural home. It's fine to keep them separate for now so you don't have to do PRs all the time. I understand that. But long term, I think the separate `trueblocks-docs` site may be able to be merged into `core`.

**Comment by MattDodsonEnglish** [comment]
@tjayrush I have created a workflow action that will automatically sync files from core to docs. I also tested it a few times, it works.
You can see the results on my [fork of the core tools](https://github.com/MattDodsonEnglish/trueblocks-core/tree/autocopy), where I made changes, and [a testing branch of the readme](https://github.com/TrueBlocks/trueblocks-docs/tree/testing), where the changes were copied to.

For minimal friction, it would be easiest to make a `trueblocks-core/docs/content` directory that *mimics the docs reference file structure directly*. Currently that would look like this: 
 ```
├── api
│   ├── index.html
│   └── openapi.yaml
├── data-model
│   ├── accounts.md
│   ├── blockchain-data.md
│   ├── state.md
├── docs
│   ├── chifra
│   │   ├── accounts.md
│   │   ├── admin.md
│   │   ├── chaindata.md
│   │   ├── chainstate.md
│   │   ├── other.md
```

Of course, you could generate these files from wherever you want, but it'd be better to have a "clean" docs folder to copy over (i.e. without things like examples.txt). 

**Important**, these docs would need to include the YAML front matter.


After sorting out the directory structure, all you would need to do is

1. Generate a Github token and save it in the "secrets" of this repo
2. Create a file in `.github/workflows/`-- something like `docs-sync.yaml`-- and modify the `user_name` `email` and `source` parameters.

After that, the files would automatically be copied over to trueblocks-docs anytime they are edited, with an attached link to the parent commit.
 
```yaml
name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'docs/content'
        destination_repo: 'trueblocks/trueblocks-docs' 
        user_email: ''
        user_name: ''
  ```

**Comment by tjayrush** [comment]
> For minimal friction, it would be easiest to make a trueblocks-core/docs/content directory that mimics the docs reference file structure directly. 

Totally agree. Will do that first thing in the morning tomorrow...I'll just change it without worrying if I break it if that's okay.

**Comment by tjayrush** [comment]
> Important, these docs would need to include the YAML front matter.

I will get the YAML front matter from the Hugo site so that your 'copy' script can copy the entire folder without any processing.

**Comment by tjayrush** [comment]
> without things like examples.txt

I will move examples and other non-document folders elsewhere.

**Comment by tjayrush** [comment]
I will change the directory structure and then ask @dszlachta to help me add the git-hub action (for docs) to the repo as he is currently working on adding an action for testing.

**Comment by tjayrush** [comment]
Okay. This is good. I think all you need to know for the script is that there's a folder in the `trueblocks-core` repo called `./docs/content` which is identical in structure to the `trueblocks-docs/content` folder. It doesn't contain all the files in the `docs` repo, obviously, only the automatically generated documentation.

You should be able to simple copy and replace the entire `./trueblocks-core/docs/content/` folder which I'm pretty sure is what you wanted. Here's what the folders look like as of the next push:

![image](https://user-images.githubusercontent.com/5417918/132434737-4bc2e817-f610-4a4e-ba9c-9c47da214906.png)

**Comment by tjayrush** [comment]
All the folders are updated and I re-arranged everything on the `core` repo to work as you need it to work. There's one small issue with the data of the file, which I will take care of tomorrow, and then there's only two things left:

1) Auto generation of the data-model pages (they are just hard coded now and don't update automatically), and
2) Auto generation of the data-model inside of the openapi.yaml file (this won't take long once I have (1) completed).

I'll work on these tomorrow and then we can work on the GitHub action and we should be done with this task.

**Comment by MattDodsonEnglish** [comment]
Nice! Once you paste in that action, there'll be no more thinking about copying. It'll just happen on pushes to repo.

But beside that the docs side still needs an action that:

> 2.1 Runs `hugo` to build site
> 2.2 Runs `redoc-cli bundle` to build the api.html
> 2.3 Runs `rsync` to sync with the Ubuntu box 

I'll try to work on that soon. 
Then all syncing and publishing will be automated

**Comment by tjayrush** [comment]
I was thinking about `redoc`. I think it's better if I put that into the `core` side. In this way, since I am the only one who ever runs the 'auto-generation' code (by design), we don't have to introduce the need for `redoc` onto the `docs` repo.

I can just move that one `redoc` line to the core repo's auto-gen scripts. Then, when you copy, you can copy both the `openapi.yaml` and the `index.htm` in that same folder, and `Hugo` will find it.

Do you see any downside to that?

**Comment by tjayrush** [comment]
Is the action ready to install? Will it run every time I push? 99.99% of the time, nothing in the `./docs` folder will have changed.

**Comment by MattDodsonEnglish** [comment]
>I can just move that one redoc line to the core repo's auto-gen scripts. Then, when you copy, you can copy both the openapi.yaml and the index.htm in that same folder, and Hugo will find it.

> Do you see any downside to that?

Oh, definitely a better solution to put `redoc` core side. Makes perfect sense :+1: 

> Is the action ready to install? 

Yes, it should work. Remember to generate [a github API token](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/creating-a-personal-access-token) and stick it in the "Secrets" section of this repo.

> Will it run every time I push? 99.99% of the time, nothing in the ./docs folder will have changed.

It will run every time, but only in the sense that it will check if the `/docs/content` changed each time you push. However,  it will copy over files to `trueblocks-docs` only when a file actually changes. So the only thing we'll notice is when the something gets pushed over.

**Comment by tjayrush** [comment]
I'll do this now (do `redoc` on `core` side). It won't matter if you run it again on your side (the `docs` side), so I can change it without breaking anything.

**Comment by MattDodsonEnglish** [comment]
@tjayrush 
With the commit linked below, I've automated all [publication steps on the docs side with a github action](https://github.com/TrueBlocks/trueblocks-docs/blob/master/.github/workflows/deploy.yaml).

The action:

1. Builds the hugo site to the `/public` directory
2. Builds the api page on `public/api/index.html`
3. Pushes the commits to a docs `deploy` branch (this branch is only the autogenerated site)
4. Uses rsync to copy a clean `deploy` branch to trueblocks.io
5. If any of the steps fail, a discord notification is sent to the #documentation channel.

https://github.com/TrueBlocks/trueblocks-docs/commit/3962d38edba4db9cc06e75d51344f3664c5f6849#diff-87ee5504a3e25ac558b343724c905f2f7949e8cec3d92b9c4300bb922afa164f

On my side, I think I'm done. If you want to automate the core -> docs sync, you could make an action in core at
`github/workflow/sync.yaml`

I think this would work immediately, but you might need to add a `API_TOKEN_GITHUB`  (I believe it should generate automatically, but I could be wrong)
 
```
name: Push File

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'docs/content'
        destination_repo: 'trueblocks/trueblocks-docs' 
        user_email: ''jrush@quickblocks.io"
        user_name: ''tjayrush"
```
This action will _push changes to the docs repo only  if actual docs file changes_. Unless they affect `docs/content`, changes to `src` will not have any effect on the docs side.

But that's really to save you work. If for whatever reason you don't want to add it, that's fine too.

I think you can decide what you want, and close this issue.

**Comment by tjayrush** [comment]
@MattDodsonEnglish Are you okay with this issue? I'd like to close it.

I think the only part that isn't left is automating the 'push changes to repo from CORE to DOCS' which I'm not sure I want. I still haven't quite gotten away from pushing changes directly to `develop`, so if I change a command line, push the change, then change my mind, I don't want people to have incorrect docs (even for a few minutes).

I'd must rather move docs changes to the docs repo by hand -- at least until I break the habit of pushing changes directly to develop. I'm getting there. Closing this now, but we can revisit later.
