### ISSUE TITLE
Change "About" url: docs.trueblocks.io → trueblocks.io

### ISSUE THREAD

**Issue by MattDodsonEnglish** [TrueBlocks/trueblocks-core#1744]
This should take about 10 seconds, but it should streamline users to the right place, and possibly improve SEO a bit. See screenshot.

![image](https://user-images.githubusercontent.com/47385188/132593126-9da85dbc-09f2-4660-be96-2dbe24af7c84.png)

Oh, and Twitter too.

**Comment by tjayrush** [comment]
Done on here and Twitter
