### ISSUE TITLE
Why are clang-format and jq required for install?

### ISSUE THREAD

**Issue by MattDodsonEnglish** [TrueBlocks/trueblocks-core#1746]
As I was updating the install instructions, I began to wonder whether those two applications are necessary for user builds.
So I'm making this issue.

If they are necessary for user builds, they'll stay in the instructions, of course. If they are only necessary for testing or something, perhaps we don't need to list them as user requirements (I'll let that be your call).

I think any answer will be good enough to close this issue. After that's done, I'll make a PR to this repo to update the README's install section.

**Comment by MattDodsonEnglish** [comment]
From discord discussion:

> JQ is definitely needed for testing. clang-format is eventually going to be needed in order to make a PR on the code to ensure consistent formatting, so I would leave them both in place.

Ok, am going to leave both of these in. Maybe in the future, it'll make sense to extract those into a "Developing Trueblocks" section, but they are staying for now.

**Comment by tjayrush** [comment]
Makes sense. Eventually, the only people actually downloading code or cloning the repo will probably be developing since most users will be using an Electron app.
