### ISSUE TITLE
Remove -q flag from docker build in test_with_docker.sh

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#1769]
I'd like to be able to see the progress of the docker build when I run the action manually. I could change it myself, but I wanted to make that obvious before doing that.

**Comment by dszlachta** [comment]
This can be hard, as the only way to read the new image's ID is to get it from stdout. Without `-q`, docker prints a lot of messages

**Comment by tjayrush** [comment]
That's okay. It was just a convenience. Closing.
