### ISSUE TITLE
ChifraResponse.json.Unmarshal failure when bad data sent from Erigon

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#1776]
A user reports this when running against Erigon Rinkeby:

```
~/github/trueblocks-core/bin$ ./chifra scrape
ChifraResponse:json.Unmarshal() failed: invalid character '\x05' in string literalChifraResponse:json.Unmarshal() failed: invalid character '\x05' in string literalGetChifraMeta.GetChifraResponse failed with: invalid character '\x05' in string literal2021/09/30 09:16:38 scraping:    true
2021/09/30 09:16:38 open tmp/IndexScraper.txt: no such file or directory
```

We asked for the results of `chifra status --terse` and got this response:

```
~/github/trueblocks-core/bin$ chifra status --terse
client: {code:-32000,message:methodhandlercrashed} (not archive, tracing)
2021/09/30 10:26:46 trueblocks: GHC-TrueBlocks//0.12.1-alpha-452ee3083-20210930 (eskey, no pinkey)
2021/09/30 10:26:46 configPath: /home/david/.local/share/trueblocks/
2021/09/30 10:26:46 cachePath: /home/david/.local/share/trueblocks/cache/
2021/09/30 10:26:46 indexPath: /home/david/.local/share/trueblocks/unchained/
2021/09/30 10:26:46 rpcProvider: http://localhost:8545/
```

the **client:** line is wrong. (I will write an issue against Erigon), but TrueBlocks should not crash as a result.

**Comment by seacheo** [comment]
I have a similar issue when running chifra scrape. Chifra is pointed towards a full archive Erigon node with tracing on. 

```chifra scrape
ChifraResponse:json.Unmarshal() failed: invalid character 'h' after object key:value pairChifraResponse:json.Unmarshal() failed: invalid character 'h' after object key:value pairGetChifraMeta.GetChifraResponse failed with: invalid character 'h' after object key:value pair2021/10/02 01:49:15 scraping:    true
2021/10/02 01:49:15 open tmp/IndexScraper.txt: no such file or directory
```

The output of chifra status --terse:

```client: erigon/2021.09.1/linux-amd64/go1.16.7 (archive, tracing)
2021/10/02 01:51:06 trueblocks: GHC-TrueBlocks//0.12.1-alpha-37e122348-20211002 (eskey, no pinkey)
2021/10/02 01:51:06 configPath: /home/sean/.local/share/trueblocks/
2021/10/02 01:51:06 cachePath: "/home/sean/.local/share/trueblocks/cache/"
2021/10/02 01:51:06 indexPath: /home/sean/.local/share/trueblocks/unchained/
2021/10/02 01:51:06 rpcProvider: "http://localhost:8555/"
```

The same error occurs when running chifra serve but the command continues to run. With chifra scrape, the error results in the comman exiting.

**Comment by tjayrush** [comment]
In your copy of `chifra status --terse` it looks like the first line is missing. It should start with `client:`. Do you see that? Are you on the latest version of Erigon? We had a problem, I think because of this issue on Erigon: https://github.com/ledgerwatch/erigon/issues/2753.

However, we fail where we shouldn't.

**Comment by seacheo** [comment]
I just updated erigon and this is the full output from running `chifra status -- terse`:

```$ chifra status --terse
client: erigon/2021.10.2/linux-amd64/go1.17.1 (archive, tracing)
2021/10/02 19:00:28 trueblocks: GHC-TrueBlocks//0.12.1-alpha-37e122348-20211002 (eskey, no pinkey)
2021/10/02 19:00:28 configPath: /home/sean/.local/share/trueblocks/
2021/10/02 19:00:28 cachePath: "/home/sean/.local/share/trueblocks/cache/"
2021/10/02 19:00:28 indexPath: /home/sean/.local/share/trueblocks/unchained/
2021/10/02 19:00:28 rpcProvider: "http://localhost:8555/"
```

I still get the exact same error mentioned above. Does it have anything to do with the `tmp/IndexScraper.txt` file that is missing?

**Comment by tjayrush** [comment]
I'm sorry for your continued trouble. 

```
ChifraResponse:json.Unmarshal() failed: invalid character '\x05' in string literalChifraResponse:json.Unmarshal() failed: invalid character '\x05' in string literalGetChifraMeta.GetChifraResponse failed with: invalid character '\x05' in string literal2021/09/30 09:16:38 scraping:    true
2021/09/30 09:16:38 open tmp/IndexScraper.txt: no such file or directory
```

Do you still get the first part of the error (the `ChifraResponse` part)?

For the second part (the missing file), can you provide listing of the $CONFIG folder:

`find ~/Library/Application Support/TrueBlocks` (on Mac)

`find ~/.local/share/trueblocks` (on Linux)

Include the entire output of the command. That will help me understand what's going on.

**Comment by seacheo** [comment]
I've attached the terminal output of `chifra scrape` and the find command in a text file.
[Terminal Saved Output.txt](https://github.com/TrueBlocks/trueblocks-core/files/7280712/Terminal.Saved.Output.txt)

**Comment by tjayrush** [comment]
Thank you so much for your continued help.

Before doing anything -- just to help me debug -- can you do `ls -l ~/.local/share/trueblocks/cache/tmp/*`?

**Comment by tjayrush** [comment]
Thank you so much for this. It's so helpful.

After you've done the listing, do this:

 There's a folder on your machine, in the TrueBlocks cache, called `/home/sean/.local/share/trueblocks/cache/tmp`. You can empty that (technically, you can always remove anything in the cache at any time -- it will be created -- but it will slow things down the next time you query, so don't.) The `tmp` folder contains a few odds and ends, so you can always remove it. I'm not sure that will solve the issue, but it can't hurt, and it may help, so go ahead and do:
 
 ```
cd /home/sean/.local/share/trueblocks/cache/tmp/
rm *
 ```
 
 If you run the command again, it may fail, but I would hope the `Cannot open tmp/indexScraper.txt` error will disappear.
 
 I suspect this is two issues -- I'm trying to remove the second of the two.
 
 Then, for the first problem -- the weird `ChifraRespons:json.Unmarshal` issue, I wonder if I can ask you -- are you a coder? Can you help me debug it?
 
In a folder called `src/go-apps/flame/server` are two files: `options.go` and `server.go`. This error is coming from `options.go`. I'd do this myself, but I'm not seeing the problem here (and I have no Rinkeby node). Can you put some 'printf' style debugging prior to the Unmarshaling to see what JSON code it's trying to parse?

I feel like this will be super easy once I can see what data its choking on.

**Comment by seacheo** [comment]
After clearing the cache, the `Cannot open tmp/indexScraper.txt` still appears. I added the line `fmt.Printf(string(out))` right after the `err = json.Unmarshal(out, &response)` on line 70 and I've attached the response below.
[Terminal Saved Output.txt](https://github.com/TrueBlocks/trueblocks-core/files/7281104/Terminal.Saved.Output.txt)

**Comment by tjayrush** [comment]
I think we're making progress. I'm seeing this line:

"rpc_provider": ""http://localhost:8555/"",
  
(notice the double-double quotes).

Before changing anything else, can you send me the contents of your `~/.local/share/trueblocks/trueBlocks.toml` file?

I suspect there's a mis-configuration there.

If you have double-double quotes in that file, this may be part of the problem. After sending me the file, you can edit that to remove the double-double quotes.

If you don't have double-double quotes, then something else is wrong.

I either case, it appears we could 'trim' the user's input as the double-double quotes should never appear in our response.

Let me know.

Also -- are you the discord group? I'd like to acknowledge your super helpful attitude. Cheers.

**Comment by seacheo** [comment]
Yes the contents of the .toml file are here (Obviously omitted the etherscan key):

```
[version]
current = "0.11.8-alpha"

[settings]
cachePath = "/home/sean/.local/share/trueblocks/cache/"
rpcProvider = "http://localhost:8555/"
etherscan_key = "XXXXXXXXXXXXX"

[requries]
parity=false

```
I did not see the double-double quotes appear in the config which is a bit strange. I'm not in the discord group but I appreciate the shoutout. Thanks!

**Comment by tjayrush** [comment]
I should have told you to not copy your ES key. Sorry.

I'm a bit confused at this point. Can you put two line **before** the unmarshalling?

```
fmt.Printf("%v\n", out)
fmt.Printf("%s\n", string(out))
```

**Comment by seacheo** [comment]
Yup. Output attached below.

[Terminal Saved Output.txt](https://github.com/TrueBlocks/trueblocks-core/files/7281840/Terminal.Saved.Output.txt)

**Comment by tjayrush** [comment]
I truly do apologize for being so dense. This is taking way longer than it should. After we figure this out, I will write up a bunch of notes so at least your suffering can be amortized over other people who run into the same problem:

Let's try this: remove the entire folder `~/.local/share/trueblocks/cache/tmp` (including the folder -- it will be re-created the next time you run).

Prior to doing that, kill the server (if it's running).

After you do that, send me the results of `chifra status --terse`.

After you do that, send me the results of `chifra status --terse --fmt json`.

After you do that, try to start the server.

My current theory is that when Erigon provided bad data a couple of days ago, we failed, but before we failed we cached the results of the query for `chifra status` and then, after Erigon fixed itself, we were still reading a bogus cache item.

**Comment by seacheo** [comment]
Got it no worries. I've followed the steps and attached the output below.
[Terminal Saved Output.txt](https://github.com/TrueBlocks/trueblocks-core/files/7281998/Terminal.Saved.Output.txt)

**Comment by tjayrush** [comment]
This is new, isn't it?

```
00038427 (  38427)- <WARNG> : Could not open file: /home/sean/.local/share/trueblocks/cache/tmp/clientVersion.txt
00040999 (   2572)- <WARNG> : Could not open file: /home/sean/.local/share/trueblocks/cache/tmp/clientVersion.txt
```

Now I'm think it's a permissions problem. Can you do:

```
ls -l ~/.local/share/trueblocks
ls -l ~/.local/share/trueblocks/*
ls -l ~/.local/share/trueblocks/cache/*
ls -lR  ~/.local/share/trueblocks/cache/*
```

Edit the results to remove anything you don't want anyone to see (there shouldn't be anything.

**Comment by seacheo** [comment]
Yeah those are new errors. I've attached the output below. Is there anyway I can just wipe and reinstall trueblocks to avoid this error? Or is it a system issue?
[Terminal Saved Output.txt](https://github.com/TrueBlocks/trueblocks-core/files/7282219/Terminal.Saved.Output.txt)

**Comment by tjayrush** [comment]
Yeah. I guess so. I'm at a loss at this point.

To 'start over', you can remove all the files in `~/.local/share/trueblocks`, remove and reclone the repo, and follow the install instructions.

You can should be able to work with the `master` branch, as we just released version 0.14.0.

Let me know how it goes, please. Sorry I couldn't be of more help.

**Comment by seacheo** [comment]
Reinstalled and everything seems to work fine. Is there any way I can run `chifra scrape` on an Erigon node?  It seems like it requires tracing (wasn't sure if this was OpenEthereum specific)? What would you recommend I do to keep my index updated?

**Comment by tjayrush** [comment]
Very happy to hear it's fixed. Still not sure what the problem was.

See this comment: https://github.com/TrueBlocks/trueblocks-core/issues/1648#issuecomment-930659959

You may also need to add this to the same file. 

[requires]
parity = false

Matt, this should be an FAQ. Everyone who runs against non-Ethereum mainnet has this problem.

**Comment by MattDodsonEnglish** [comment]
Here you go, I've added it to the troubleshooting section, and linked it somewhere else.

It's a small change, but you might want to give it a quick check for accuracy.
https://github.com/TrueBlocks/trueblocks-docs/commit/42ff8b958b13747e8cedf8620409410d68fdbace

**Comment by tjayrush** [comment]
Even though we didn't solve the problem @seacheo, may I close this? It's actually documented elsewhere, so this is a dup otherwise.

**Comment by seacheo** [comment]
Yes feel free to close it. Thanks for the help!
