### ISSUE TITLE
Export: Should we export UTC or Z for dates? Must have something, what is correct?

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#1778]
It all depends :) Is the format that the backend is using right now standardized and understood by consumers?
Another thing is that I think backend should include timezone as well, because otherwise it's not clear which one is used. It could be `Z` for UTC, but it should be present in my opinion.

_Originally posted by @dszlachta in https://github.com/TrueBlocks/trueblocks-explorer/pull/187#discussion_r718373693_

**Comment by tjayrush** [comment]
Dawid. You made a comment in one of my PRs copied above. Can you expand on what you think we need to do to fix this? Exporting UTC is something I picked up a long time ago from some Ethereum code somewhere, but if it should be 'Z' instead, I'm happy to change it, but will that break existing code?

**Comment by dszlachta** [comment]
The format used by TrueBlocks right now is compatible with ISO 8601, so I think it is just a matter of adding `Z` to the returned string. I'm not sure about C++ code, but in go it shouldn't break anything except that we don't support this kind of strings as an input for `chifra when` (we support optional `UTC`, so would need to change it to `Z`)
