### ISSUE TITLE
chifra export --accounting --fmt json <address> returns malformed json on Rinkeby

### ISSUE THREAD

**Issue by davidfsol5** [TrueBlocks/trueblocks-core#1780]
Running "chifra export --accounting --fmt json" on Rinkeby returns a unquoted string value, -nan, at any $.data[n].statements[m].spotPrice. 

Example ['statements'] element:
  "statements": [
    {
      "blockNumber": 9326262,
      "transactionIndex": 32,
      "timestamp": 1632149759,
      "assetAddr": "0x0e5722a9bac7ed87a735bbdbb1737671ce0919a4",
      "assetSymbol": "WEI",
      "decimals": 18,
      "prevBlk": 9326122,
      "prevBlkBal": "1653862462067550758",
      "begBal": "1653862462067550758",
      "endBal": "1653409224062565140",
      "amountIn": "",
      "internalIn": "",
      "selfDestructIn": "",
      "minerBaseRewardIn": "",
      "minerNephewRewardIn": "",
      "minerTxFeeIn": "",
      "minerUncleRewardIn": "",
      "prefundIn": "",
      "amountOut": "",
      "internalOut": "",
      "selfDestructOut": "",
      "gasCostOut": "453238004985618",
      "reconciliationType": "regular",
      "spotPrice": -nan,
      "priceSource": "uniswap",
      "begBalDiff": "",
      "endBalCalc": "1653409224062565140",
      "endBalDiff": "",
      "totalIn": "",
      "totalOut": "453238004985618",
      "totalOutLessGas": "",
      "amountNet": "-453238004985618",
      "reconciled": true
    }
  ]

**Comment by davidfsol5** [comment]
$ chifra status --terse
client: erigon/2021.08.3/linux-amd64/go1.16.7 (archive, tracing)
2021/10/01 16:59:49 trueblocks: GHC-TrueBlocks//0.12.1-alpha-452ee3083-20210930 (eskey, no pinkey)
2021/10/01 16:59:49 configPath: ~/.local/share/trueblocks/
2021/10/01 16:59:49 cachePath: ~/.local/share/trueblocks/cache/
2021/10/01 16:59:49 indexPath: ~/.local/share/trueblocks/unchained/
2021/10/01 16:59:49 rpcProvider: http://localhost:8545

**Comment by davidfsol5** [comment]
From trueBlocks.toml:
[requires]
tracing = false
archive = false

**Comment by tjayrush** [comment]
Nice find. This is because we try to price the transaction by searching for UniSwap which (of course) is not on Rinkeby. It shouldn't return invalid JSON, though. Should be simple to fix. I will close this issue when it's ready.

**Comment by tjayrush** [comment]
For my information: https://stackoverflow.com/a/6602204/6307513

**Comment by tjayrush** [comment]
This commit (https://github.com/TrueBlocks/trueblocks-core/commit/37e12234885ac141af857a9fe682bee5ffc78731) should fix the `-nan` issue. I wrote another issue to disallow use of UniSwap on non-mainnet chains #1781  If that fixes the problem, can you please close this issue? Thanks.

**Comment by tjayrush** [comment]
This should be fixed. It was a divide by zero because UniSwap doesn't exist and was returning zero.
