### ISSUE TITLE
New block range parsing code could easily support more use cases

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#1798]
Two that come to mind:

1) Allow block ranges in `chifra list` and `chifra export`,
2) Allow more than one block range at a time.

Neither of these two currently work, and they will continue to not work, until we can modify the underlying C++ code, which we may not do because we are mostly going to re-write things in Go.

This issue just helps me not forget to add this function once we are living in Go Land.

**Comment by dszlachta** [comment]
As a note, we will have to change validation rules when adding support for multiple block ranges. 
The function used to validate arguments, `ValidateBlockIdentifiers` takes `maxRanges` as its last parameter. To allow multiple ranges, `maxRanges` should be set to -1.

**Comment by tjayrush** [comment]
I'm going to close this and open a different issue specifically for adding block range code to getState, getTokens, ethslurp and maybe others.
