### ISSUE TITLE
chifra scrape: Very easy way to speed up scrape (on hold)

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#1829]
Currently, we process each block through a go channel one at a time but concurrently. This is fine, but...at one point in the pipeline we call `eth_getLogs` which we need to do to process the logs.

The thing is, `eth_getLogs` takes both a `startBlock` and an `endBlock`, but because our pipeline handles each block separately, we always send `eth_getLogs(bn, bn)`. In other words, we always ask for one block at a time.

We could, instead, separate out two pipelines. One for regular block processing, which would called `trace_block` which only has a single parameter (`blockNumber`) and a different pipeline that processes groups of 10 blocks at a time for `eth_getLogs`.

We did some very rudimentary tests and found multi-block calls to `eth_getLogs` is about 20% faster.

**Comment by tjayrush** [comment]
Made into a TODO item in the code.

**Comment by bh2smith** [comment]
I believe this is a pretty important feature. Querying block by block instead of utilizing the block range results in an incredibly inefficient number of requests.

**Comment by tjayrush** [comment]
You're right, I think, but the thing is we have to query for `trace_block` and `eth_getBlockByNumber` since we need (in the first case) various information such as miner/validator, uncles, contract creations other than from the main tx, output data, and call data into sub-calls. For the later case, we need the withdrawals.

So, while it's true that we could use `eth_getLogs` with a broader range, I'm not sure how much it would help since we have to look at every block anyway.
