### ISSUE TITLE
Running pins --init --all with default IPFS gateway 

### ISSUE THREAD

**Issue by dszlachta** [TrueBlocks/trueblocks-core#1851]
Most likely calling `chifra pins --init --all` with the default IPFS gateway will result in exceeding the gateway's rate limit. The function that downloads chunks has a waiting mechanism to avoid this issue, however `--all` causes this function to run twice (for blooms and index chunks) in parallel.

One possible solution would be to use a global mutex. Another, to make the waiting time configurable as function parameter

**Comment by tjayrush** [comment]
This now uses our dedicated Pinata server, so no longer happens. If it's a problem in the future, there's the `--sleep` option which allows the user to throttle the requests.
