### ISSUE TITLE
Paths for pinMan

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#1853]
Two things:

1) Initial folder on first run:
      a. Edit the `trueblocks.toml` file and change the `indexPath` to a custom folder.
      b. Run `chifra init` (the old pinMan code) -- it should fail with a message complaining that the customized indexPath does not exist -- if a user customizes the `indexPath` the folder must exist.
      c. Run `chifra pins --init` without creating the customized folder (it will fail, but not elegantly)

Fix: `chifra pins --init` should quit if the `indexPath` does not exist but only if the user has customized the `indexPath` setting. If the user has not customized the indexPath, `chifra pins --init` should create the folder if it doesn't exist (it should already exist, but we don't want the user to have to create it if he/she has not customized the location).

2. If the `indexPath` folder exists, but any of the five subfolders does not exist, create them.

The contents of the `indexPath` should look this before downloading anything.

```
{indexPath}
├── blooms
├── finalized
├── ripe
├── staging
└── unripe
```

**Comment by dszlachta** [comment]
@tjayrush Should we close this one?

**Comment by tjayrush** [comment]
Yes.
