### ISSUE TITLE
wrong gasUsed return

### ISSUE THREAD

**Issue by lianqiao** [TrueBlocks/trueblocks-core#1940]
Hi,

my local eth node doesn't work with eth_getTransactionReceipt API, it always returns null like this:
{"jsonrpc":"2.0","id":"251","result":null}

but true block will return result with wrong gasUsed like this: 
(this transaction should have gasUsed = 21000, see here: https://www.blockchain.com/eth/tx/0x572625164dfcaccd49649d0e11ead303f8cce77efa79c588e7dd977f1170756b)
    {
      "hash": "0x572625164dfcaccd49649d0e11ead303f8cce77efa79c588e7dd977f1170756b",
      "blockHash": "0xb8194421e52915e8728060eb29789247a61e690bf18990204d9f164cb2b3cbf7",
      "blockNumber": 9990000,
      "transactionIndex": 122,
      "nonce": 1169,
      "timestamp": 1588465200,
      "from": "0xcae89dec6b173b03e09d76030d016f37b9404a04",
      "to": "0x4fed1fc4144c223ae3c1553be203cdfcbd38c581",
      "value": 50957091000000000,
      "gas": 21000,
      "gasPrice": 5000000000,
      "maxFeePerGas": 0,
      "maxPriorityFeePerGas": 0,
      "input": "0x",
      "hasToken": 0,
      "receipt": {
        "contractAddress": "0x0",
        "gasUsed": 22092768,
        "effectiveGasPrice": 5000000000,
        "status": 3513466368
      },
      "gasUsed": 22092768
    }

**Comment by tjayrush** [comment]
Hi. Thanks for your issue.

Maybe you could provide a bit more information. 

Can you copy in the results of doing

```
chifra status --terse
```

Also, when you say `eth_getTransactionReceipt` doesn't work, that confuses me. 

What do you get when you run this command:

```
curl -s -H "Content-Type: application/json" -d '{"method":"eth_getTransactionReceipt","params":["0xc8a6e2d363612721bfd9d850be100ce3e54264be2c4fe41f4b2837d51b2e99e7"],"id":1,"jsonrpc":"2.0"}' YOUR_RPC_ENDPOINT | jq
```

(Of course, replace YOUR_RPC_ENDPOINT with your RPC endpoint.)

We get:

```
{
  "jsonrpc": "2.0",
  "result": {
    "blockHash": "0xb8194421e52915e8728060eb29789247a61e690bf18990204d9f164cb2b3cbf7",
    "blockNumber": "0x986f70",
    "contractAddress": null,
    "cumulativeGasUsed": "0x97bfd1",
    "effectiveGasPrice": "0x12a05f200",
    "from": "0xcae89dec6b173b03e09d76030d016f37b9404a04",
    "gasUsed": "0x5208",
    "logs": [],
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "status": "0x1",
    "to": "0x4fed1fc4144c223ae3c1553be203cdfcbd38c581",
    "transactionHash": "0x572625164dfcaccd49649d0e11ead303f8cce77efa79c588e7dd977f1170756b",
    "transactionIndex": "0x7a"
  },
  "id": 1
}
```

which has a `gasUsed` of `21000` as you noted.

When I do `chifra receipt 0x572625164dfcaccd49649d0e11ead303f8cce77efa79c588e7dd977f1170756b` we get

```
{
  "data": [
    {
      "contractAddress": "0x0",
      "gasUsed": 21000,
      "effectiveGasPrice": 5000000000,
      "status": 1
    }
  ]
}
```

which appears correct.

**Comment by lianqiao** [comment]
`./trueblocks-core/bin/chifra status --terse` returns
```
client: Geth/v1.10.13-stable-7a0c19f8/linux-amd64/go1.17.2 (not archive, not tracing)
2021/12/03 08:07:51 trueblocks: GHC-TrueBlocks//0.17.0-alpha-78f3effe5-20211129 (eskey, no pinkey)
2021/12/03 08:07:51 configPath: /home/ec2-user/.local/share/trueblocks/
2021/12/03 08:07:51 cachePath: /home/ec2-user/.local/share/trueblocks/cache/
2021/12/03 08:07:51 indexPath: /home/ec2-user/.local/share/trueblocks/unchained/
2021/12/03 08:07:51 rpcProvider: http://localhost:8545

```

for the curl command you provided, my local eth node returns
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": null
}

```
this is what I mean `eth_getTransactionReceipt` doesn't work


the last command `chifra receipts 0x572625164dfcaccd49649d0e11ead303f8cce77efa79c588e7dd977f1170756b`
my output is:

```
blocknumber	transactionindex	hash	gasused	status	iserror
"Transaction 0x572625164dfcaccd49649d0e11ead303f8cce77efa79c588e7dd977f1170756b not found."
```

**Comment by tjayrush** [comment]
I'm going to close this as stale. It appears you're running against a Geth full node which does not have historical transactions. That may explain it. If you think this is wrong, please re-open.
