### ISSUE TITLE
Comment from user about ABI generation

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#1941]
On adding custom abis to TrueBlocks, what worked for me on Rinkeby is the following:
1. Generate an abi for a smartcontract and export it somewhere as json. My dev toolchain is based on Hardhat. So I used https://github.com/symblox/hardhat-abi-gen (I picked is from the top of a google search--"hardhat generate abi". @symblox forked it from another project. I did zero due diligence on the project. So, use it at your own risk.). The resulting json is an undecorated array of signature elements with a <contractName>.json file naming convention. My gen tool, hardhat-abi-gen, sticks this file in [projectRoot]/abi.
2. Copy <contractName>.json to [cachePath]\abis, and change the file's name to <contractAddress>.json.
3. Run chifra export --articulate --fmt json <contractAddress>. The resulting output showed proper articulation of prior transactions from calls to custom methods in the contract.
4. Run chifra abis <contractAddress>. Dumped output that looked right based on cursory eyeballing. 
GitHub
GitHub - symblox/hardhat-abi-gen: 🧰 Export Solidity contract ABIs o...
🧰 Export Solidity contract ABIs on compilation ⚙️. Contribute to symblox/hardhat-abi-gen development by creating an account on GitHub.

**Comment by davidfsol5** [comment]
Other observations:
* Running Step 4 before running Step 2 generates an empty [contractAddress].json file. 
* My contract references another contract. Chifra autogenerated an empty [otherContractAddress].json.
* I tried an ABI file that added a top-level "address" element and that named the signature element array "abi". Chifra was not able to articulate from this file.

**Comment by davidfsol5** [comment]
Normal hardhat compilation leaves contract abis in the build/artifacts/contracts directory. So, no need for hardhat-abi-gen as long as TrueBlocks can use the enriched content--more elements than just the method signature array.

I've attached an example abi from the openZeppelin tutorial contract, Box, for formatting.
[Box.zip](https://github.com/TrueBlocks/trueblocks-core/files/7644032/Box.zip)

**Comment by tjayrush** [comment]
Okay to close. Stored in multichain.md
