### ISSUE TITLE
Crash when treversing the DAI contract with --articulate option

### ISSUE THREAD

**Issue by pintail-xyz** [TrueBlocks/trueblocks-core#1963]
Crash when running `export` on the DAI contract address at around block 12596469, only when using `--articulate` option.

```
chifra export --articulate --first_block 12596469 0x6b175474e89094c44da98b954eedeac495271d0f > out
terminate called after throwing an instance of 'std::bad_alloc'txs for address 0x6b175474e89094c44da98b954eedeac495271d0f
  what():  std::bad_alloc
```
This issue does not occur when the `--articlulate` option is removed.

**Comment by tjayrush** [comment]
That is fantastic. I think we caught something....

Can you please confirm that each of these two command causes a core dump (they both do on my Linux box but not my Mac):

```
chifra export --articulate 0x6b175474e89094c44da98b954eedeac495271d0f --first_block 12596470
```

```
chifra transactions --articulate 12596470.26
```

**Comment by tjayrush** [comment]
It would be wildly helpful to me if you were to return the results of this command (the output is put into `file.out`):

```
TEST_MODE=true ~/.local/bin/chifra/getTrans --articulate 12596470.26 --fmt json --verbose 10 >file.out 2>&1
```

**Comment by pintail-xyz** [comment]
> Can you please confirm that each of these two command causes a core dump (they both do on my Linux box but not my Mac):
> 
> ```
> chifra export --articulate 0x6b175474e89094c44da98b954eedeac495271d0f --first_block 12596470
> ```
> 
> ```
> chifra transactions --articulate 12596470.26
> ```

Yep, both of those give me a `terminate called after throwing an instance of 'std::bad_alloc'` message.

> It would be wildly helpful to me if you were to return the results of this command (the output is put into `file.out`)

This also resulted in a core dump. `file.out` is 1347 lines long - I can send it to you on Discord.

**Comment by tjayrush** [comment]
This is definitely a bug in our code. We hope to have a fix soon. It results from a transaction with a signature that includes a `tuple` within a `tuple`, thus: `boostFor((address,address,uint256,uint256,uint256,uint256,address,address,bytes,tuple), uint256, uint256, address)`
