### ISSUE TITLE
Make install fails on linux

### ISSUE THREAD

**Issue by JeremyLegere** [TrueBlocks/trueblocks-core#1997]
Getting errors when following the install instructions on TrueBlocks
https://trueblocks.io/docs/install/install-trueblocks

### ~/t/build> cmake ../src
-- Using c++ standard c++17
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- ======== LOOKING FOR PYTHON ========================
-- Found PythonInterp: /usr/bin/python (found version "2.7.17") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found version "2.7.17") 
-- ======== LOOKING FOR CURL ========================
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.58.0") 
-- GIT: branch 'develop' commit '450bc383b' timestamp '1641214413'
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/trueblocks-core/build
### ~/t/build> make
Scanning dependencies of target util
[  0%] Building CXX object libs/utillib/CMakeFiles/util.dir/accountname.cpp.o
[  1%] Building CXX object libs/utillib/CMakeFiles/util.dir/apikey.cpp.o
[  1%] Building CXX object libs/utillib/CMakeFiles/util.dir/basenode.cpp.o
[  1%] Building CXX object libs/utillib/CMakeFiles/util.dir/bigint.cpp.o
[  1%] Building CXX object libs/utillib/CMakeFiles/util.dir/biglib.cpp.o
[  2%] Building CXX object libs/utillib/CMakeFiles/util.dir/biguint.cpp.o
[  2%] Building CXX object libs/utillib/CMakeFiles/util.dir/collection.cpp.o
[  2%] Building CXX object libs/utillib/CMakeFiles/util.dir/colors.cpp.o
[  3%] Building CXX object libs/utillib/CMakeFiles/util.dir/commandoption.cpp.o
[  3%] Building CXX object libs/utillib/CMakeFiles/util.dir/config_paths.cpp.o
[  3%] Building CXX object libs/utillib/CMakeFiles/util.dir/conversions.cpp.o
[  3%] Building CXX object libs/utillib/CMakeFiles/util.dir/curl_code.cpp.o
[  4%] Building CXX object libs/utillib/CMakeFiles/util.dir/database.cpp.o
[  4%] Building CXX object libs/utillib/CMakeFiles/util.dir/exportcontext.cpp.o
[  4%] Building CXX object libs/utillib/CMakeFiles/util.dir/fielddata.cpp.o
[  4%] Building CXX object libs/utillib/CMakeFiles/util.dir/filenames.cpp.o
[  5%] Building CXX object libs/utillib/CMakeFiles/util.dir/json_reader.cpp.o
[  5%] Building CXX object libs/utillib/CMakeFiles/util.dir/json_token.cpp.o
[  5%] Building CXX object libs/utillib/CMakeFiles/util.dir/json_value.cpp.o
[  6%] Building CXX object libs/utillib/CMakeFiles/util.dir/json_writer.cpp.o
[  6%] Building CXX object libs/utillib/CMakeFiles/util.dir/keccak.cpp.o
[  6%] Building CXX object libs/utillib/CMakeFiles/util.dir/logging.cpp.o
[  6%] Building CXX object libs/utillib/CMakeFiles/util.dir/markdown.cpp.o
[  7%] Building CXX object libs/utillib/CMakeFiles/util.dir/memmap.cpp.o
[  7%] Building CXX object libs/utillib/CMakeFiles/util.dir/names.cpp.o
[  7%] Building CXX object libs/utillib/CMakeFiles/util.dir/names_sql.cpp.o
[  7%] Building CXX object libs/utillib/CMakeFiles/util.dir/option.cpp.o
[  8%] Building CXX object libs/utillib/CMakeFiles/util.dir/options_base.cpp.o
[  8%] Building CXX object libs/utillib/CMakeFiles/util.dir/options_base_blocks.cpp.o
[  8%] Building CXX object libs/utillib/CMakeFiles/util.dir/options_base_trans.cpp.o
[  9%] Building CXX object libs/utillib/CMakeFiles/util.dir/options_base_usage.cpp.o
[  9%] Building CXX object libs/utillib/CMakeFiles/util.dir/performance.cpp.o
[  9%] Building CXX object libs/utillib/CMakeFiles/util.dir/prefunds.cpp.o
[  9%] Building CXX object libs/utillib/CMakeFiles/util.dir/rpcresult.cpp.o
[ 10%] Building CXX object libs/utillib/CMakeFiles/util.dir/runtimeclass.cpp.o
[ 10%] Building CXX object libs/utillib/CMakeFiles/util.dir/sfarchive.cpp.o
[ 10%] Building CXX object libs/utillib/CMakeFiles/util.dir/sfos.cpp.o
**/home/ubuntu/trueblocks-core/src/libs/utillib/sfos.cpp:21:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.**
libs/utillib/CMakeFiles/util.dir/build.make:926: recipe for target 'libs/utillib/CMakeFiles/util.dir/sfos.cpp.o' failed
make[2]: *** [libs/utillib/CMakeFiles/util.dir/sfos.cpp.o] Error 1
CMakeFiles/Makefile2:411: recipe for target 'libs/utillib/CMakeFiles/util.dir/all' failed
make[1]: *** [libs/utillib/CMakeFiles/util.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by tjayrush** [comment]
Can you give us any further information on this? We're not seeing broken builds on any of our build machines.

**Comment by JeremyLegere** [comment]
Hi there, it was an unknown issue with my node/vm config. I have since fixed it by spinning up a new vm and clean installing it.

**Comment by tjayrush** [comment]
Thanks for letting me know.

**Comment by steelep** [comment]
I had the same issue. 

Fixed by editing 

/trueblocks-core/src/libs/utillib/sfos.cpp

from: `#include <filesystem>
`

to: `#include <experimental/filesystem>
`

(Necessary to get it working on AWS Linux)

**Comment by tjayrush** [comment]
Thanks for letting us know.

Do you have any suggestions how to fix this and remain portable? (Sorry, I'm not excellent at portable code.)

Should I re-open this?

**Comment by steelep** [comment]
I think it may break other build processes with further modification, so probably best to leave as is, anyone with the same issue (which seems rare) will inevitably come here through google and fix..

**Comment by tjayrush** [comment]
Thanks. I created this (https://github.com/TrueBlocks/trueblocks-docs/issues/146). We can at least document it somewhere. Cheers.

**Comment by 0xad1onchain** [comment]
Yep the experimental header fixed it
