### ISSUE TITLE
Chifra: Some required folders are not created during install

### ISSUE THREAD

**Issue by dszlachta** [TrueBlocks/trueblocks-core#2034]
I may not remember it correctly, but was `make` supposed to create `blooms` and `finalized` directories?
It seems that it is not creating them right now (on develop).

**Comment by tjayrush** [comment]
How does this look like when it fails?

**Comment by dszlachta** [comment]
`make` doesn't fail, but if you try `chifra --init`, then it complains about missing directories (`error: could not open [path]/blooms/[block-range]`)

**Comment by tjayrush** [comment]
This is fixed.
