### ISSUE TITLE
Install instructions result in error: The root configuration file does not contain a list of chains

### ISSUE THREAD

**Issue by kyteague** [TrueBlocks/trueblocks-core#2075]
This is for the latest develop branch 93f52047b27c46c86c09028b8c11ba89bed135bc

Following install instructions results in an error:
```
	The root configuration file (/Users/kyle/code/dotfiles/trueblocks/trueBlocks.toml)
	does not contain a list of chains. Please follow all migrations up to v0.25.0 to continue.

	See https://github.com/TrueBlocks/trueblocks-core/blob/develop/MIGRATIONS.md

	GHC-TrueBlocks//0.26.0-alpha
```

Attempting to follow migrations I updated the `trueBlocks.toml` to
```
[chains.goerli]
rpcProvider = "ws://127.0.0.1:9090"
```

And ran `chifra status --terse --chain goerli`
This results in a different error
```
	The chain configuration folder for chain mainnet does not exist. Is it correct?
	Check: /Users/kyle/code/dotfiles/trueblocks/config/mainnet/
```

It's also quite unfortunate that you can't access `--help` to see if there are options that could even help you. Seems like there are at least 2 bugs here and documentation issues.

**Comment by tjayrush** [comment]
The first error will happen, I think, if you've not completed the migration, so the fact that it appears and then disappears after you followed the migration seems correct. Maybe I'm misunderstanding that.

The second error maybe related to the use of `ws:` for the rpc endpoint. Can you try replacing the `ws:` endpoint with the `http` RPC endpoint?

Also -- did you rebuild using the latest version? Does the folder mentioned exist? It should exist if you completed `cmake ../src` and `make` from the `./build` folder after pulling the latest version.

Are you on `develop` or `master`?

**Comment by tjayrush** [comment]
bump

**Comment by tjayrush** [comment]
One more bump, I guess, and then I'll close this.
