### ISSUE TITLE
Bug: Remove trailing / from curl url

### ISSUE THREAD

**Issue by arces** [TrueBlocks/trueblocks-core#2078]
Hello, I am getting this error:  
`Block 12345 is later than the last valid block 0.`

When I run this command:  
`chifra blocks 12345`

I followed a suggestion and enabled the curl to debug prints to turn on. I got this:  
`curl -s --data '{"method":"eth_syncing","params":[],"id":"1","jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST https://eth.getblock.io/mainnet/?api_key=*REAL_API_KEY_GOES_HERE*/`

The result was:  
`--[Invalidapikey]--`

If you put that URL (with a trailing / ) into your web browser then you get the same invalid API key response. If you remove the trailing / then it works just fine.  

I checked the TOML file, and there was no / in my RPCProvider. Just the URL and proper API key. 

Please remove it, or provide an option to not include the trailing /  from the curl URL.

Thank you.

**Comment by tjayrush** [comment]
Can you connect with me personally in the discord? You can find the discord link on our website: https://trueblocks.io. It will be easier to help you there because I can ask some questions that will be easier answered in private.

**Comment by tjayrush** [comment]
The problem is this line of code:

https://github.com/TrueBlocks/trueblocks-core/blob/master/src/apps/chifra/pkg/config/per_chain.go#L43

which calls this line of code:

https://github.com/TrueBlocks/trueblocks-core/blob/master/src/apps/chifra/pkg/config/per_chain.go#L62

which adds the slash if it's not there.
