### ISSUE TITLE
chifra scrape: Index contains old zip files, which causes errors when looping over files

### ISSUE THREAD

**Issue by naterush** [TrueBlocks/trueblocks-core#2084]
In my `unchained/mainnet/finalized` folder, I have the following zip files:
```
002705942-002708765.bin.gz
005827115-005832546.bin.gz
008850012-008855721.bin.gz
008855722-008862514.bin.gz
008862515-008869365.bin.gz
008875322-008880954.bin.gz
009000001-009005001.bin.gz
009019551-009024627.bin.gz
009045418-009050579.bin.gz
009055462-009061547.bin.gz
009061548-009068873.bin.gz
```

The unzipped versions of these files are also here, which makes me confused why they are here. They are annoying, as they cause my code that parses the index to fail (it doesn't handle zip files).

I don't think they should be there, should they?

**Comment by tjayrush** [comment]
Thanks for your issue. Before putting the files into IPFS, we zip them. When you do `chifra init` we download the ZIP file from IPFS and unzip it. Once we complete the 'pin to IPFS' part of the work (for which we will need these files), then we can remove them. For now, you can ignore them during your parse - valid files have `.acct.bin` as the file name.

**Comment by naterush** [comment]
I figured that was what was happening. Would just be nice if these files were cleared out, so I could loop over them easily.

**Comment by tjayrush** [comment]
Fix for this is fixed in a branch and will be merged shortly.
