### ISSUE TITLE
RPC Connection required for purely local operations

### ISSUE THREAD

**Issue by naterush** [TrueBlocks/trueblocks-core#2085]
# Bug
1. Turn off RPC Connection by inputting a bogus connection string.
2. Run the command `chifra names`
3. Receive the output:

```
  Warning: The RPC server (http://localhost:23456) was not found. Either start it, or edit the rpcProvider
  value in the file /Users/nathanrush/Library/Application Support/TrueBlocks/trueBlocks.toml. Quitting...
```

# Expected Behavior

I want to be able to perform local operations without needing an RPC connection. `chifra names` feels like it should be one of those operations. Is it now?

**Comment by tjayrush** [comment]
Fixed.
