### ISSUE TITLE
chifra scrape current file does not sequentially follow previous file

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#2091]
When using `chifra scrape indexer` you may get the above message.

What this means is a completely empty block was returned from the RPC. When I say completely empty, this means there's not even a miner address.

Our scraper thinks that every block must contain at least one address, but on some chains this is not true (for example, on some private chains).

It's possible to turn this warning off by editing a per-chain configuration file. Search for the word 'allow_missing' on this page: https://trueblocks.io/docs/chifra/configs/.

The file you want to edit is in `$CONFIG_FOLDER/config/<chain>/blockScrape.toml` where $CONFIG_FOLDER is dependent on your operating system (`~/.local/share/trueblocks` for linux, `~/Library/Application Support/TrueBlocks` for Mac) and `<chain>` is the name of the chain you're scraping.

You can find `$CONFIG_FOLDER` with `chifra status --terse`.

You can create the file if it doesn't exist and add the following value (creating the section if it doesn't exist):

```
[settings]
allow_missing = true
```

**Comment by davidfsol5** [comment]
The above advice fixed my instance of this problem scraping gnosis chain. 

Path for .toml file on my machine, Ubuntu 20.04.4 LTS, is `$CONFIG_FOLDER/config/<chain>/blockScrape.toml`. The `config` directory is singular not plural as shown above.

**Comment by tjayrush** [comment]
> The `config` directory is singular not plural as shown above

Corrected. Thanks.

**Comment by tjayrush** [comment]
This has been added to the FAQ: https://trueblocks.io/blog/faq/#error-message-current-file-does-not-sequentially-follow-previous-file

**Comment by tjayrush** [comment]
This has been added to the FAQ, so closing. Will still be findable looking at closed issues.
