### ISSUE TITLE
chifra tokens restful api /tokens doesn't recognize param "addrs"

### ISSUE THREAD

**Issue by AlanGuo** [TrueBlocks/trueblocks-core#2092]
restful api /tokens doesn't recognize param "addrs", but works properly with addrs2

![image](https://user-images.githubusercontent.com/727863/160153797-87c0603d-4ce7-426c-ae0b-5631ec5f416c.png)

<img width="1166" alt="image" src="https://user-images.githubusercontent.com/727863/160153618-fa275620-59c2-41af-89dd-a1ce92821c30.png">

**Comment by tjayrush** [comment]
In the short term, the solution to this is to use `addrs2` instead of `addrs` for the `tokens` endpoint. The documentation is incorrect.
