### ISSUE TITLE
chifra chunks: --check should consult manifest for number of files

### ISSUE THREAD

**Issue by notchia** [TrueBlocks/trueblocks-core#2119]
`chifra chunks --check` should consult the manifest for the number of files as part of its checking. This is to catch instances where `chifra init --all` may not have successfully processed all files (due to issues outside of Trueblocks' control). In these cases, `chifra chunks --check` should report that there weren't as many files as expected, even if none of the files were corrupted.

**Comment by tjayrush** [comment]
Done
