### ISSUE TITLE
chifra list: Two parallel requests to `/list` will cause `os.Rename` error

### ISSUE THREAD

**Issue by dszlachta** [TrueBlocks/trueblocks-core#2123]
Making two parallel requests to `/list` produces this error:
```
rename /Volumes/IndexCache/trueblocks/cache/mainnet/monitors/staging/0xf503017d7baf7fbc0fff7492b751025c6a78179b.mon.bin /Volumes/IndexCache/trueblocks/cache/mainnet/monitors/0xf503017d7baf7fbc0fff7492b751025c6a78179b.mon.bin: no such file or directory"
```
To reproduce run the below code in browser's console:
`get = () => fetch('http://localhost:8080/list?addrs=0xf503017d7baf7fbc0fff7492b751025c6a78179b'); get() ; get()`

This is most likely caused by the fact that we try to change the filesystem in an async environment of `chifra serve`: when the code triggered by the second/first request tries to move the file, the file is already gone.
I think that we could investigate setting up a mutex[1] for the monitor file being moved.

[1] https://pkg.go.dev/sync#Mutex

**Comment by tjayrush** [comment]
This used to be protected against in the C++ code. It must have gotten dropped with the recent change to `chifra list`. Nice catch.  How did you bump into this, just for my information?

**Comment by dszlachta** [comment]
I have a bug in my worker branch that causes Explorer to send double requests :)

**Comment by tjayrush** [comment]
Surround the call with a Mutex
