### ISSUE TITLE
whenBlock still appears in sub/develop/src/other/install/docker/tools/CMakeLists.txt 

### ISSUE THREAD

**Issue by koinju** [TrueBlocks/trueblocks-core#2131]
Based on the latest master or develop, Docker build fail because of the removal of whenBlock which still appears in sub/develop/src/other/install/docker/tools/CMakeLists.txt . But i see that the Bump to version 0.35.0 #2125 contain that modification : https://github.com/TrueBlocks/trueblocks-core/pull/2125/files#diff-c74131b8d6cab1bdfd174df7a7fe58ab876e7e8297cbd5602405cba4038e0baf ??

**Comment by tjayrush** [comment]
Thanks. I'll push a fix for this to develop shortly.
