### ISSUE TITLE
`chifra scrape` requires `--file`

### ISSUE THREAD

**Issue by dszlachta** [TrueBlocks/trueblocks-core#2156]
Currently, `chifra scrape` requires `--file` argument to be present. There are 2 problems:
1. `--file` is not documented in `chifra scrape --help`
2. during a discussion on Discord with @tjayrush we realized that `--file` argument should not be required.

**Comment by tjayrush** [comment]
This is the validation line that it's hitting on:

https://github.com/TrueBlocks/trueblocks-core/blob/master/src/apps/chifra/internal/scrape/validate.go#L64

and if you comment that line out, then this will hit:

https://github.com/TrueBlocks/trueblocks-core/blob/c0fbc744d51e6a6935f133f89ec50f800af27f5c/src/apps/chifra/internal/scrape/scrape_monitor.go#L175

You should be able to, instead, return a single line as if the first line of the file was

```
export --appearances
```

**Comment by tjayrush** [comment]
This is no longer true as of v0.37.0-beta.
