### ISSUE TITLE
chifra export: ETH reconciliation fails when delegatecall is used in internal transactions

### ISSUE THREAD

**Issue by artur-jablonski** [TrueBlocks/trueblocks-core#2159]
`chifra export --fmt json --accounting --articulate 0x7cfb89d6df1b89a678dcaf42b9c262593e881e22`

will generate two statements that don't reconcile:
1. 0x20e4a5279519859c3b8af108fa9b3238f23d5522ceb0f7245080ec79ad8f97fd
2. 0xb6bbb898938eda08034bc561c7a7dbdb6594912e84603088047844f568c363b6

this is the statement for tx 0x20e4a5279519859c3b8af108fa9b3238f23d5522ceb0f7245080ec79ad8f97fd

```
{
      "blockNumber": 13029304,
      "transactionIndex": 63,
      "timestamp": 1629024623,
      "assetAddr": "0x7cfb89d6df1b89a678dcaf42b9c262593e881e22",
      "assetSymbol": "WEI",
      "decimals": 18,
      "prevBlk": 13029231,
      "prevBlkBal": "",
      "begBal": "",
      "endBal": "53712605193010669297",
      "amountIn": "",
      "internalIn": "53712605193010669297",
      "selfDestructIn": "",
      "minerBaseRewardIn": "",
      "minerNephewRewardIn": "",
      "minerTxFeeIn": "",
      "minerUncleRewardIn": "",
      "prefundIn": "",
      "amountOut": "",
      "internalOut": "53712605193010669297",
      "selfDestructOut": "",
      "gasCostOut": "",
      "reconciliationType": "regular",
      "spotPrice": 3159.22552,
      "priceSource": "uniswap",
      "begBalDiff": "",
      "endBalCalc": "",
      "endBalDiff": "-53712605193010669297",
      "totalIn": "53712605193010669297",
      "totalOut": "53712605193010669297",
      "totalOutLessGas": "53712605193010669297",
      "amountNet": "",
      "reconciled": false
    }
```

totalIn is correct, but totalOut is not. It should be 0 and then the statement would reconcile. 

The problem lies in how the reconciliation algorithm uses traces.

```
{
    action: {
      from: '0xe592427a0aece92de3edee1f18e0157c05861564',
      callType: 'call',
      gas: '0x34b7',
      input: '0x',
      to: '0x7cfb89d6df1b89a678dcaf42b9c262593e881e22',
      value: '0x2e96981d76a33e6f1'
    },
    blockHash: '0x30868f5643d37a2a6a0cfa113b1cade2eabe093e3d8cb96d607efe73d1b2b1a4',
    blockNumber: 13029304,
    result: { gasUsed: '0x725', output: '0x' },
    subtraces: 1,
    traceAddress: [ 0, 0, 1, 2 ],
    transactionHash: '0x20e4a5279519859c3b8af108fa9b3238f23d5522ceb0f7245080ec79ad8f97fd',
    transactionPosition: 63,
    type: 'call'
  }
```

the above trace will be correcly counted towards internalIn as the wallet is the recipient 
of the value.

```
{
    action: {
      from: '0x7cfb89d6df1b89a678dcaf42b9c262593e881e22',
      callType: 'delegatecall',
      gas: '0x32ce',
      input: '0x',
      to: '0xd9db270c1b5e3bd161e8c8503c55ceabee709552',
      value: '0x2e96981d76a33e6f1'
    },
    blockHash: '0x30868f5643d37a2a6a0cfa113b1cade2eabe093e3d8cb96d607efe73d1b2b1a4',
    blockNumber: 13029304,
    result: { gasUsed: '0x5e0', output: '0x' },
    subtraces: 0,
    traceAddress: [ 0, 0, 1, 2, 0 ],
    transactionHash: '0x20e4a5279519859c3b8af108fa9b3238f23d5522ceb0f7245080ec79ad8f97fd',
    transactionPosition: 63,
    type: 'call'
  }
```

The above trace however is ERRONEOUSLY counted towards internalOut. Since the call is
`delegatecall` there's no transfer of value here even though the wallet appears as `from`
in this action.

**Comment by artur-jablonski** [comment]
closed by #2160

**Comment by tjayrush** [comment]
Hey. Thanks so much for the issue -- and especially the PR. I had to modify it a bit so the code you added didn't get overwritten by the auto-code generator, but other than that, your change passes all tests -- plus I added a new test to cover this issue. Win, win, win. I'll merge this soon.

**Comment by tjayrush** [comment]
> The above trace however is ERRONEOUSLY counted towards internalOut. Since the call is delegatecall there's no transfer of value here even though the wallet appears as from in this action.

Can you explain this to me? Is this what `delegatecall` means? That the trace may have a non-zero value, but that it does not actually take money away from the `from` address of this trace?

Was the caller that initiated this trace different than the `from` in this case?

**Comment by artur-jablonski** [comment]
> > The above trace however is ERRONEOUSLY counted towards internalOut. Since the call is delegatecall there's no transfer of value here even though the wallet appears as from in this action.
> 
> Can you explain this to me? Is this what `delegatecall` means? That the trace may have a non-zero value, but that it does not actually take money away from the `from` address of this trace?
> 
> Was the caller that initiated this trace different than the `from` in this case?

If you have call invocation chain A -> B -> C where B and C are contracts and A is either a contract or EOA then if B calls C with `delegatecall` then provided that A called B with `call` or `staticcall` then C will observe `sender` as A (not B) and `value` will have the same value as the one passed from A -> B. Also C will operate on storage of B. So in essence C is operating as if it was part of contract B, so there's no transfer of value here to C.

In this particular case in the trace [0,0,1,2] there's transfer of value from `0xe592427a0aece92de3edee1f18e0157c05861564` to `0x7cfb89d6df1b89a678dcaf42b9c262593e881e22`. Then as part of the same invocation chain in trace [0,0,1,2,0] the `0x7cf` contract does `delegatecall` to `0xd9db270c1b5e3bd161e8c8503c55ceabee709552`. This does not transfer value as the `0xd9db` operates on `0x7cfb`'s storage.

Not sure if that's clear... but if you google around for delegatecall you may find some better explanation of how it works

**Comment by artur-jablonski** [comment]
> Hey. Thanks so much for the issue -- and especially the PR. I had to modify it a bit so the code you added didn't get overwritten by the auto-code generator, but other than that, your change passes all tests -- plus I added a new test to cover this issue. Win, win, win. I'll merge this soon.

Ok, thanks. Honestly the last time I wrote a line of c++ was 15 years ago in college :D. So not sure how the code generation works here. I put the code where I thought it most naturally fit, compiled it and verfified it fixed that particular extract. Not sure where you have the tests and didn't see a commit adding a test for this case.... can you point me to where it is?
