### ISSUE TITLE
chifra scrape run failed

### ISSUE THREAD

**Issue by ching2018** [TrueBlocks/trueblocks-core#2184]
copyRipeToStage failed...replaying...
00053025 (  53025)- <WARNG> : Current file (/root/.local/share/trueblocks/unchained/mainnet/ripe/014966281.txt) does not sequentially follow previous file 14966279.

**Comment by ching2018** [comment]
then repeat

**Comment by tjayrush** [comment]
Closing as a duplicate of this: #2091
