### ISSUE TITLE
"chifra pins" is not working 

### ISSUE THREAD

**Issue by mrlarssen** [TrueBlocks/trueblocks-core#2186]
How can I see when the manifest was last published? Docs tells me this:
chifra pins --list | tail -n 1

But that throws an error:
Error: unknown command "pins" for "chifra"

**Comment by tjayrush** [comment]
The docs were out of date. I updated them, but answering here. Use

```
chifra chunks manifest --fmt txt | tail -n 1
```

This will produce a result similar to this:

```
015013585-015016368	QmREw5qaoucbVvEQzF71D44rXKzax9YgKuEEhZYHAYFZF5	QmTbFshRSdBFoC6AvBgzdRJ6Vgb9cVL3yTprYQ24XqHTqx
```

The second number in the row is the latest published block. Use 

```
chifra when <bn>
```

will show the date of that block (remove the leading zero on the block number).
