### ISSUE TITLE
chifra export asks for Etherscan key even if not asked to articulate stuff

### ISSUE THREAD

**Issue by artur-jablonski** [TrueBlocks/trueblocks-core#2198]
```
chifra export --fmt json --accounting [address]
{ "data": [

  Warning: Articulation requires an api_key from Etherscan. See http://api.etherscan.io/apis. Quitting...

```

**Comment by tjayrush** [comment]
--accounting enables --articulate. We use it as one of the many hints to determine if the address is a token.

**Comment by artur-jablonski** [comment]
hmmm I htought --articulate was for humans :). 

So the reason I don't want to articulate is to speed things up. I think you could still look for 4byte codes to look for ERC20 signature. That should be as accurate as articulation.... unless I miss sth.

**Comment by tjayrush** [comment]
I'll leave this open. When you say "speed things up", help me understand that. Do you mean the 'first time' you ever look at an address or 'subsequent times?'

I think it should be quite a bit faster the second time you extract an address, but maybe I'm mistaken.

Is it "too slow" always or just the first time on a new address?

**Comment by artur-jablonski** [comment]
"first time" I ever look at address. If there's a lot of appearances than articulating will just slow things down for now benefit (that I can see)

**Comment by tjayrush** [comment]
Do you use `--cache` when you run your commands?

The first time you ever run against a given address, it will take longer. Articulating does take some time, you're right.

What happens if you comment out the line in the code that forces you to have an ABI if you're doing `--accounting`?

**Comment by artur-jablonski** [comment]
Nope, not using `--cache`

> What happens if you comment out the line in the code that forces you to have an ABI if you're doing --accounting?

Not sure which line you mean, but I can give it a try next week

**Comment by tjayrush** [comment]
This is no longer true. Closing.
