### ISSUE TITLE
Unable to generate go client via swagger.json

### ISSUE THREAD

**Issue by daoleno** [TrueBlocks/trueblocks-core#2208]
I got the openapi specification from [here](https://trueblocks.io/api/). 

And use [oapi-codegen](https://github.com/deepmap/oapi-codegen) to generate go client.

But get some errors
```sh
❯ oapi-codegen -package chifra swagger.json
error generating code: error generating type definitions: error generating Go types for component schemas: error converting Schema appearance to Go type: error generating Go schema for property 'blockNumber': error resolving primitive type: invalid number format: blknum
```

It seems that the number format `blknum` does not conform to the openapi specification.

**Comment by daoleno** [comment]
However, it is possible to import `swagger.json` into `postman`. Perhaps this is a case specific to `oapi-codegen`.

**Comment by tjayrush** [comment]
I was going to say that the OpenAPI file is used in numerous places without complaint, so it might be tool-specific. I'd be open a PR if you can figure something out. Otherwise, perhaps this can be closed?

**Comment by daoleno** [comment]
Yes, you're right. It's ok to use [SwaggerHub](https://app.swaggerhub.com/) to generate the client SDK.
