### ISSUE TITLE
Sepolia chain is not being updated

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#2218]
Since "the merge" on Sepolia, our node (which is running an Execution Client only) has not been updating. It runs, but it gets no data because it's not connected to the Sepolia beacon chain.

We need to install a beacon chain running Sepolia on our wildmolasses server.

We can start with this docker version, but I would actually like to bring this docker thing in house so we can have better control.

https://github.com/wmitsuda/one-liner-archive/releases/tag/v0.2.2

In particular, this file: https://github.com/wmitsuda/one-liner-archive/blob/v0.2.2/sepolia.yml

**Comment by dszlachta** [comment]
I think we can close this one?
