### ISSUE TITLE
Enable automatic production of GoLang package documentation

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#2219]

**Comment by tjayrush** [comment]
@dszlachta This one is pretty simple, I think. The basic idea is that our `pkg` folder can be pushed to the GoLang documentation site every time we merge into master. I've been trying to use the documentation feature locally and it's really helpful. This is a "self contained" project, so you can write a PR from develop.

**Comment by dszlachta** [comment]
`pkg.go.dev` automatically fetches tags, right now it's up-to-date with 0.37. I'm not sure if it's possible to push code without tag (or if we want users to use such code as package). 
I've added plain text license in a PR, this should make documentation for the subfolders in our code visible as well.
