### ISSUE TITLE
chifra scrape add chain name to info logging messages

### ISSUE THREAD

**Issue by dszlachta** [TrueBlocks/trueblocks-core#2227]
This is the current output of the scraper:
```
01820496 (   7729)- <INFO>  : Wrote 1726 records to $INDEX/finalized/000299138-000300000.bin (snapped to 100000 blocks) 41:52)             
02542291 (    135)- <INFO>  : Block 302001: have 4009 addrs of 200000 (2.0%). Need 195991 more. Found 4009 records (2.00 txs/blk).
```
It is fine, but when running scrapers for multiple chains and with outputs in the same console (e.g. docker log) it is not clear which chain's block it is.

@tjayrush what do you think?

**Comment by tjayrush** [comment]
For the scrapers too.

**Comment by tjayrush** [comment]
This would be helpful when running in docker mode.
