### ISSUE TITLE
chifra scrape non-archive and non-tracing nodes support needs better warnings

### ISSUE THREAD

**Issue by dszlachta** [TrueBlocks/trueblocks-core#2258]
It seems like support for non-archive and non-tracing nodes got lost in translation while moving code to Go.
If this is correct, we should decide to either bring it back or inform the users that such nodes are no longer supported.
Issues spotted:
1. The new scraper (Go) assumes that tracing is on.  There is no single mention of anything like `isArchiveNode` or `isTracingNode` in `blaze.go`: https://github.com/TrueBlocks/trueblocks-core/blob/develop/src/apps/chifra/internal/scrape/blaze.go
2. Go version of `isTracingNode` always returns `true`. It looks like a mock got merged into `develop`: https://github.com/TrueBlocks/trueblocks-core/blob/c0fbc744d51e6a6935f133f89ec50f800af27f5c/src/apps/chifra/pkg/rpcClient/client.go#L228
3. Setting `archive=false` and using non-archive node will make `blockScrape` exit: https://github.com/TrueBlocks/trueblocks-core/blob/develop/src/apps/blockScrape/options.cpp#L98

**Comment by tjayrush** [comment]
> It seems like support for non-archive and non-tracing nodes got lost in translation while moving code to Go. If this is correct, we should decide to either bring it back or inform the users that such nodes are no longer supported.

It never was properly supported, even in the C++ code. It was only theoretically possible, but never a priority.

We should fix the messaging and fail more gracefully.

**Comment by tjayrush** [comment]
This is related: https://github.com/TrueBlocks/trueblocks-core/issues/2111

**Comment by tjayrush** [comment]
This is so freaking old it's the same as not even existing...
