### ISSUE TITLE
chifra config - make this tool more capable

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#2299]
IPFS has an amazing `config` command that allows two wonderful things:

1) `ipfs config edit` which uses the EDITOR enviornment variable to open the config file. Super simple - very useful - only run if we're in a terminal (shows the need for a isTerminal() go routine
2) `ipfs config Section.Key <value>` For example: `chifra config chains.mainnet.rpcProvider <whatever>`.

This is super useful because it allows configuration by script and also configuration by web page.

**Comment by tjayrush** [comment]
@dszlachta I just wanted you to see this. Some day we will do this. It's so useful in IPFS we should do it. It would be easy.

**Comment by dszlachta** [comment]
I'd add printing values, too: `chifra config settings.indexPath` => `/some/directory`
It would make our docs and communication with the users easier, because instead of telling them to "check where your index is" you could just send them a command:
- ```cp -R `chifra config settings.indexPath`/unchained ~/backup```
- ```curl --data $RPC_COMMAND `chifra config chains.mainnet.rpcProvider` ```

**Comment by tjayrush** [comment]
> I'd add printing values, too: `chifra config settings.indexPath` => `/some/directory` It would make our docs and communication with the users easier, because instead of telling them to "check where your index is" you could just send them a command:
> 
> * `` cp -R `chifra config settings.indexPath`/unchained ~/backup ``
> * `` curl --data $RPC_COMMAND `chifra config chains.mainnet.rpcProvider`  ``

Exactly. IPFS calls it `show`.

**Comment by tjayrush** [comment]
This will get done one day, we don't need to remember it here.
