### ISSUE TITLE
API bugs

### ISSUE THREAD

**Issue by 0x-diy** [TrueBlocks/trueblocks-core#2371]
I'm trying to interact with monitors via the api. I'm seeing issues with some of the commands. I'm running 0.40.2-beta. 

When I run: /monitors?addrs={address}&watch=true I do not get any type of a response back....it just spins.

When I want to delete a monitor and run: /monitors?addrs={address}&delete=true I get this response back from the api...

{
    "errors: [
        "The --delete, --undelete, and --remove options are not valid when using the GET route
    ]
}

According to the api docs (trueblocks.io/api), these should be GET commands. If I change request type to put/post I get a 405: method not allowed response from serve.

**Comment by tjayrush** [comment]
`--watch` has been disabled from the API. The other options are currently unsupported, but will be in the future.
