### ISSUE TITLE
`chifra scrape` doesn't work?

### ISSUE THREAD

**Issue by snf** [TrueBlocks/trueblocks-core#2374]
Updated my code pulling from develop and noticed that `chifra scrape run` doesn't work anymore?

I did some digging and it seems that this is because the `scrapeBlock` command is no longer compiled and added to `$HOME/.local/bin/chifra/`.

What's the best way to run the scraper now or keeping the index up to date?

Extra info:
the output form `chifra scrape run` is this message repeated:
`TB: Error while reading stderr --  read |0: file already closed`

From strace I saw that chifra is trying to execve scrapeBlock:
```
[pid 49881] execve("/home/user/.local/bin/chifra/blockScrape", ["/home/user/.local/bin/chifra/blo"..., " run --fmt txt"], 0xc000391560 /* 32 vars */) = -1 ENOENT (No such file or directory)
[pid 49881] write(12, "\2\0\0\0\0\0\0\0", 8) = 8
[pid 49881] exit(253)                   = ?
[pid 49881] +++ exited with 253 +++
```

**Comment by tjayrush** [comment]
Try just `chifra scrape`. (`run` has been removed.)

For any command, do `chifra <cmd> —help`.

Sorry — still beta...

> I did some digging and it seems that this is because the scrapeBlock command is no longer compiled and added to $HOME/.local/bin/chifra/.
> 


The change was exactly this. We removed the C++ version of the scraper and replaced it with a GoLang version so the scraper is now “inside chifra” It will allow us to move forward more easily.

**Comment by snf** [comment]
Thanks for the colour! Confirmed it works. I think I was mixing up the binaries before so I was executing the old `chifra` but with the new bindir.
