### ISSUE TITLE
Traces should have timestamp in them

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#2384]
Check this user-created mention of an issue

https://github.com/wschwab/research0xa57/issues/14#issuecomment-1262696654

**Comment by tjayrush** [comment]
Different but related issue: https://github.com/TrueBlocks/trueblocks-core/issues/2367.

Ultimately, the solution will be to allow end users to use GoLang templated display which is currently a work in progress. We have a few test cases working, but the feature is immature.

When it's ready, user will be able to specify a configuration item (per tool, per chain, with default per chain and system-wide default). When implemented, user will be able to do something like this:

```
{{.timestamp}}\t{{.blockNumber}}\t{{.transactionIndex}}
```

Or perhaps specify a list of fields and allow the template to be built from that, and/or both.

**Comment by wschwab** [comment]
For those who can't see it, the reference is to an issue where I'm interested in having the timestamps built in to the information given in the traces. While Trueblocks provides `chifra when` which can return timestamp from a block, having it built in would be useful when collecting bulk data.

In the meantime, based on another suggestion from TJ, I'm looking at using the following to get `<blockNumber>,<timestamp>,<address delegatecalled to>`:
```bash
# get block and timestamp from txs
awk -F"," '(NR>1) {print $1 "," $4}' file_with_txs.csv > temp1.csv
# get addresses being delegatecalled to from traces
awk -F"," '(NR>1) $4~/delegatecall/ {print $1 "," $7}' file_with_traces.csv > temp2.csv
# manually echo headers
echo '"blockNumber","timestamp","action::to"' > block_timestamp_addr.csv
# join files together
join -1 1 -2 1 temp1.csv temp2.csv -t',' >> block_timestamp_addr.csv

# cleanup
rm temp1.csv; rm temp2.csv
```
Initial testing using this looks promising. I'll include it here in case it's useful for anyone trying to do something similar, or even for implementing an internal solution.

**Comment by tjayrush** [comment]
Closing as `timestamps` are now part of traces in the `develop` branch.
