### ISSUE TITLE
Dockerfile missing

### ISSUE THREAD

**Issue by austin-lambertajollylife** [TrueBlocks/trueblocks-core#2414]
I was looking through the development branch and it appears that the Dockerfile was deleted. Was this intentional?

**Comment by tjayrush** [comment]
Yes. The docker version is now in its own repo, here: https://github.com/TrueBlocks/trueblocks-docker

You want to use the develop version there as well, although, to be honest, it's not yet officially supported yet, so there may be dragons.

**Comment by tjayrush** [comment]
May I close this?

**Comment by tjayrush** [comment]
Closing.
