### ISSUE TITLE
chifra export big wallet error

### ISSUE THREAD

**Issue by raulmonge** [TrueBlocks/trueblocks-core#2428]
Data:
`2022/10/11 02:06:38 Client:       erigon/2022.09.3/linux-amd64/go1.19.1 (archive, tracing)
2022/10/11 02:06:38 TrueBlocks:   GHC-TrueBlocks//0.40.2-beta-6ab01bad2-20221009 (eskey, pinkey)
2022/10/11 02:06:38 RPC Provider: http://localhost:8545 - mainnet (1,1)
2022/10/11 02:06:38 Config Path:  /root/.local/share/trueblocks/
2022/10/11 02:06:38 Cache Path:   /root/.local/share/trueblocks/cache/mainnet/
2022/10/11 02:06:38 Index Path:   /root/.local/share/trueblocks/unchained/mainnet/
2022/10/11 02:06:38 Progress:     15721774, 15714037, 15717200, 15721760
`

The command im running: 
`chifra export 0x3a8713065e4daa9603b91ef35d6a8336ef7b26c6 --articulate --first_block 11883506 --cache`

Error trace:
`terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
14850638        82      2022-05-26 22:55:28 UTC 1653605728      0x3a8713065e4daa9603b91ef35d6a8336ef7b26c6      0x74312363e45dcaba76c59ec49a7aa8a65a67eed3      0.000000000000000000    0.000000036078158516    44779   0x42ca1f447999604a0aec8a7be0ae6eaa18f1088ce461907b6175551b9591471e   0       0x2295f9bf      0x2295f9bf(stub:00000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000629059c9000000000000000000000000000000000000000000000000000000000000001b7c41261adad51ff8439c893eafbbfa8a52f3d54184795667071654e9073565d24f15c81f2a2296bc2fabd80e816a1ed441beb049884b003546c09ba9626ff06100000000000000000000000000000000000000000000, stub:00000000000000000001abaabdc3355a18a1606`

Problem comes from this tx in specific
[Etherscan](https://etherscan.io/tx/0x42ca1f447999604a0aec8a7be0ae6eaa18f1088ce461907b6175551b9591471e)

When I run the command without the articulate doesnt break so probably have someting to be with the X2Y2 contract or the ABI

**Comment by tjayrush** [comment]
Cannot reproduce.

This does not appear to happen any longer. Not sure what was fixed. If it persists, please re-open.
