### ISSUE TITLE
chifra receipts --to_file test is failing

### ISSUE THREAD

**Issue by dszlachta** [TrueBlocks/trueblocks-core#2432]
This test https://github.com/TrueBlocks/trueblocks-core/blob/master/test/gold/tools/getReceipts/getReceipts_to_file.txt fails. The output is printed to stdout instead of a file.

Comment from @tjayrush:
>The gold is correct (with both --output and --to_file, there is not output other than the name of the file into which the results were printed. In the case of --output, the user tells us the filename. In the case of --to_file (which should only work in API mode), the file name is generated. In both cases, the caller is responsible to remove the file.

**Comment by tjayrush** [comment]
No such test cases
