### ISSUE TITLE
chifra cmd write custom, thread-safe JSON writer

### ISSUE THREAD

**Issue by dszlachta** [TrueBlocks/trueblocks-core#2433]
There are few issues with the code we have right now:
1. Brackets and other JSON fragments as string literals in `StreamMany` source
2. No control over opening/closing JSON object (e.g. when using `--file`)
3. Need to manually print meta and errors in `StreamMany` (but also elsewhere if the code doesn't call `StreamMany`)

It seems like the best solution is to write a custom JSON writer. Such a writer could open/close the result object and print the footer (meta and errors) automatically:

```json
{ ⬅️ inserted automatically 
  "data": [ ⬅️ field opened by caller
    {}, ⬅️ comma inserted automatically
    {} ⬅️ no comma, because there's no more items
  ],
  "meta": {}, ⬅️ inserted automatically
  "errors": [] ⬅️ inserted automatically
} ⬅️ inserted automatically
```

### Thread-safety
For future use, we can implement a thread-safe variant of "open field", which would write to a buffer first and copy the buffer into the output when the field is "closed", for example:
```go
type Container int
const (
  ContainerArray Container = iota
  ContainerObject
)

// "Opens" a field by printing `[` or `{` to the output writer and returns
func OpenField(key string, containerType Container) error {}

// Same, but prints into a buffer, until `writeItems` finishes. This allows us to stream data from multiple goroutines
func OpenFieldConcurrent(key string, containerType Container, writeItems func(buf *io.Writer) error) error {}
```

**Comment by dszlachta** [comment]
@tjayrush any comments appreciated :)

**Comment by tjayrush** [comment]
Can you add a short example of how it might look like from the calling code? In the previous incarnation, some of the 'details' rose up into the calling code. I like to try to keep the calling code simpler to understand. An example would help me understand what you have in mind.

Also, in your above list of "issues with existing code", under item 2. I think the same thing applies to the block or transaction identifiers for `chifra blocks`, `chifra transactions` (and `addresses` for `chifra export`). Is that right? Just in a different loop (or channel)?

**Comment by dszlachta** [comment]
Example from the call:
```bash
chifra export --appearances <address_with_100000_appearances> > file.out
# produces JSON obj with `data` array
chifra traces --file file.out --fmt json
# does it have a `data` array? should it have one?
chifra traces --raw --file file.out
```

Also, we've decided not to write concurrent variants yet.

**Comment by dszlachta** [comment]
Caller example:
```go
// note: this will probably be only in 1 place, inside StreamMany
// 1. Create JSON writer that will print to globals.Writer 
// (which can be stdout, a file or HTTP response)
w := NewJsonWriter(opts.Globals.Writer)
// 2. Prints `"data": [`. Because OpenField uses 
// w.Write internally, the writer will print the opening `{` as well
w.OpenField("data", FieldType.Array)
// 3. Now we just write the data. `w.Write` can be called in a 
// goroutine, too, and it does not need buffering in both cases
for _, itemToPrint := range dataToPrint {
  // comma is added automatically when needed
  w.Write(itemToPrint)
}
// 4. Tell the writer that we are done. It knows that it is inside of
// an array, so it will print the closing `]`. Next, it prints `meta`
// and `errors` if needed.
w.Close() 
```

**Comment by tjayrush** [comment]
Looks super simple. Let's go for it.

**Comment by dszlachta** [comment]
Implemented
