### ISSUE TITLE
chifra export -- filter erc20 token with given account address

### ISSUE THREAD

**Issue by fenghaojiang** [TrueBlocks/trueblocks-core#2460]
I wonder are there ways to get erc20 token balance with given account address with TrueBlocks.
1. filter erc20 token with given account address.
2. get the erc20 token balance by calling the contract.

**Comment by tjayrush** [comment]
Yes. There is already.

`chifra export --statements <address(es)>`

Please try that out and if it's what you're looking for let me know (and close this issue).

I'm going to ask a favor of you. Can you go to our documentation repo, and add this as an FAQ? You'll earn a GitPoap...

If not, I can do it, just let me know.

**Comment by fenghaojiang** [comment]
I create FAQ on your docs. I wonder whether this one would be ok? 
And one suggestion: May be it's good to add some example outputs in your docs would be great.

**Comment by fenghaojiang** [comment]
You can close this issue if you think my FAQ is acceptable. 😂

**Comment by fenghaojiang** [comment]
I have tried TrueBlocks but seems not the same result I expect.
```shell
$ ./bin/chifra export --statements 0x3608f1a98ae83553f8776f166dd2bbb6b44b894e
```
00183086 ( 183086)- <PROG>  : Completed          1 of        1 txs (0 statements) for address 0x3608f1a98ae83553f8776f166dd2bbb6b44b894e
assetAddress    assetSymbol     decimals        blockNumber     transactionIndex        timestamp       prevBlock       prevBlockBal    begBal  amountIn        internalIn      selfDestructIn  minerBaseRewardIn   minerNephewRewardIn     minerTxFeeIn    minerUncleRewardIn      prefundIn       totalIn amountOut       internalOut     selfDestructOut gasCostOut      totalOut        totalOutLessGas     amountNet       endBal  begBalDiff      endBalCalc      endBalDiff      reconciled      spotPrice       priceSource     reconciliationType

**Comment by tjayrush** [comment]
> I create FAQ on your docs. I wonder whether this one would be ok? And one suggestion: May be it's good to add some example outputs in your docs would be great.

I'm not finding that. Can you link to what you did?

**Comment by tjayrush** [comment]
> ```shell
> ./bin/chifra export --statements 0x3608f1a98ae83553f8776f166dd2bbb6b44b894e
> ```

Please open a new issue for this...

I tried it locally here, and it works. It's easier to track in a new issue.

I'm going to close this issue.
