### ISSUE TITLE
Missing index items?

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [TrueBlocks/trueblocks-core#2467]
I am looking at this transaction on the mainnet: https://etherscan.io/tx/0xc738fc254b05db7933e9b465b2db63ae854215359dc1bd789a647a1850a62acd

It's from address is: 0x054993ab0f2b1acc0fdc65405ee203b4271bebe6
Block number: 10277711

But if i query the index it's not showing up, while other address occurrences do definitely show up. Am i missing something?..

Full log on my system:
```
vasiliybondarenko@Vasiliys-MBP16 bin % ./chifra transactions -a -u 0xc738fc254b05db7933e9b465b2db63ae854215359dc1bd789a647a1850a62acd
bn	tx	tc	addr	reason
10277711	64		0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	from
10277711	64		0x7a250d5630b4cf539739df2c5dacb4c659f2488d	to
10277711	64		0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2	input
10277711	64		0x6b175474e89094c44da98b954eedeac495271d0f	input
10277711	64		0xa478c2975ab1ea89e8196811f51a7b7ade33eb11	log_1_topic_2
vasiliybondarenko@Vasiliys-MBP16 bin % ./chifra transactions 0xc738fc254b05db7933e9b465b2db63ae854215359dc1bd789a647a1850a62acd
blockNumber	transactionIndex	date	timestamp	from	to	ether	ethGasPrice	gasUsed	hash	isError	encoding	compressedTx
10277711	64	2020-06-16 15:52:46 UTC	1592322766	0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	0x7a250d5630b4cf539739df2c5dacb4c659f2488d	0.223063180000000000	0.000000040000000000	125298	0xc738fc254b05db7933e9b465b2db63ae854215359dc1bd789a647a1850a62acd	0	0x7ff36ab5	0x7ff36ab5(stub:000000000000000000000000000000000000000000000002c4df11130ed0d5010000000000000000000000000000000000000000000000000000000000000080000000000000000000000000054993ab0f2b1acc0fdc65405ee203b4271bebe6000000000000000000000000000000000000000000000000000000005ee8ef670000000000000000000000000000000000000000000000000000000000000002000000000000000000000000c02aaa39b223fe8d0a0e, stub:5c4f27ead9083c756cc20000000000000000000000006b175474e89094c44da98b954eedeac495271d0f)
vasiliybondarenko@Vasiliys-MBP16 bin % ./chifra list 0x054993ab0f2b1acc0fdc65405ee203b4271bebe6
INFO[20-10|21:50:47.859] Downloading  015531844-015534579  from IPFS.
address	blockNumber	transactionIndex
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	12655959	195
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	12697277	188
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	12697303	99
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	12697322	281
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	12697324	88
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	13269886	45
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	13269900	177
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	13269973	178
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	13772984	129
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	14366254	17
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	14469880	33
```

The same is true for this transaction: https://etherscan.io/tx/0x8b291cc405c937e8547bbb082f2e8f3b3621ebcaf737dedb5b5794ccf3e7b714
it's also not in the list from the index.

**Comment by tjayrush** [comment]
When I run `chifra list 0x054993ab0f2b1acc0fdc65405ee203b4271bebe6 `, I get this result:

```
2022/10/20 14:02:46 0x054993ab0f2b1acc0fdc65405ee203b4271bebe6 appended 4 apps at 010276425-010280719
2022/10/20 14:02:46 0x054993ab0f2b1acc0fdc65405ee203b4271bebe6 appended 2 apps at 010366446-010369908
2022/10/20 14:02:46 0x054993ab0f2b1acc0fdc65405ee203b4271bebe6 appended 2 apps at 010956146-010959166
2022/10/20 14:02:46 0x054993ab0f2b1acc0fdc65405ee203b4271bebe6 appended 2 apps at 010972000-010975263
2022/10/20 14:02:46 0x054993ab0f2b1acc0fdc65405ee203b4271bebe6 appended 1 apps at 011470953-011473807
2022/10/20 14:02:46 0x054993ab0f2b1acc0fdc65405ee203b4271bebe6 appended 1 apps at 011946881-011949948
2022/10/20 14:02:46 0x054993ab0f2b1acc0fdc65405ee203b4271bebe6 appended 1 apps at 012108328-012111155
2022/10/20 14:02:46 0x054993ab0f2b1acc0fdc65405ee203b4271bebe6 appended 1 apps at 012517646-012520291
2022/10/20 14:02:46 0x054993ab0f2b1acc0fdc65405ee203b4271bebe6 appended 1 apps at 012653782-012656533
2022/10/20 14:02:46 0x054993ab0f2b1acc0fdc65405ee203b4271bebe6 appended 4 apps at 012696729-012699357
2022/10/20 14:02:46 0x054993ab0f2b1acc0fdc65405ee203b4271bebe6 appended 1 apps at 013192217-013195102
2022/10/20 14:02:46 0x054993ab0f2b1acc0fdc65405ee203b4271bebe6 appended 3 apps at 013268742-013271610
2022/10/20 14:02:46 0x054993ab0f2b1acc0fdc65405ee203b4271bebe6 appended 1 apps at 013771503-013774313
2022/10/20 14:02:46 0x054993ab0f2b1acc0fdc65405ee203b4271bebe6 appended 5 apps at 014358497-014361038
2022/10/20 14:02:46 0x054993ab0f2b1acc0fdc65405ee203b4271bebe6 appended 1 apps at 014363929-014366711
2022/10/20 14:02:46 0x054993ab0f2b1acc0fdc65405ee203b4271bebe6 appended 2 apps at 014435826-014438546
2022/10/20 14:02:46 0x054993ab0f2b1acc0fdc65405ee203b4271bebe6 appended 1 apps at 014469359-014472078
2022/10/20 14:02:47 0x054993ab0f2b1acc0fdc65405ee203b4271bebe6 appended 1 apps at 015548513-015551407
2022/10/20 14:02:47 0x054993ab0f2b1acc0fdc65405ee203b4271bebe6 appended 1 apps at 015551408-015554007
address	blockNumber	transactionIndex
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	10277683	200
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	10277711	64
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	10277776	94
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	10277780	102
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	10367593	194
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	10367608	23
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	10958509	72
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	10958518	77
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	10972535	102
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	10972735	84
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	11472274	222
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	11947926	77
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	12110203	88
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	12517694	73
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	12655959	195
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	12697277	188
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	12697303	99
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	12697322	281
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	12697324	88
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	13193257	227
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	13269886	45
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	13269900	177
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	13269973	178
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	13772984	129
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	14359849	140
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	14359857	202
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	14359877	153
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	14360325	141
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	14360361	80
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	14366254	17
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	14436713	58
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	14436713	59
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	14469880	33
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	15549162	83
0x054993ab0f2b1acc0fdc65405ee203b4271bebe6	15552509	117
```

which includes both `10277711.64` and `14436713.59`.

I wonder if you've kept the TrueBlocks build up to date? There was some issues with Erigon back in June that caused some errors in our index (missing appearances), so maybe your index is outdated. What do you get when you run:

```
chifra status --terse
```

**Comment by Vasiliy-Bondarenko** [comment]
Well... i did not build my own index. i have just `chifra init` and started using it.

```
vasiliybondarenko@Vasiliys-MBP16 bin % ./chifra status --terse
2022/10/21 00:26:22 Client:       Geth/v1.10.23-omnibus-b38477ec/linux-amd64/go1.18.5 (archive, not tracing)
2022/10/21 00:26:22 TrueBlocks:   GHC-TrueBlocks//0.41.0-beta-f5ce08a37-20221018 (eskey, pinkey)
2022/10/21 00:26:22 RPC Provider: https://mainnet.infura.io/v3/8a1c877729fe42d0bc3dc13b4c878168 - mainnet (1,1)
2022/10/21 00:26:22 Config Path:  /Users/vasiliybondarenko/Library/Application Support/TrueBlocks/
2022/10/21 00:26:22 Cache Path:   /Users/vasiliybondarenko/Library/Application Support/TrueBlocks/cache/mainnet/
2022/10/21 00:26:22 Index Path:   /Users/vasiliybondarenko/Library/Application Support/TrueBlocks/unchained/mainnet/
2022/10/21 00:26:22 Progress:     15791689, 15534579, 15534579, 15534579, ts: 15499540
```

**Comment by tjayrush** [comment]
When was the last time you did `chifra init`? There were bugs in the index prior to version `v0.40.2`.

**Comment by Vasiliy-Bondarenko** [comment]
i did `chifra init` only once yesterday. so i have no idea about prior versions. i have just started evaluating the software and found this issue.

**Comment by tjayrush** [comment]
Sorry for my continued density...I'm a bit slow, but I'm thorough, so we will come to a conclusion eventually...

Two things, please. Results of `git log | head -100` and results of `chifra chunks index` (this later file is bigger).

**Comment by Vasiliy-Bondarenko** [comment]
ok. sure.

[chnks.txt](https://github.com/TrueBlocks/trueblocks-core/files/9847322/chnks.txt)
[gitlog.txt](https://github.com/TrueBlocks/trueblocks-core/files/9847323/gitlog.txt)

**Comment by tjayrush** [comment]
This is very helpful to me. Thanks so much. What it shows me is that you have what I would call a "partial index." This is totally, exactly as it should be, so nothing's wrong with what you have, it's just put my in the right mind-set on how to proceed. (I was thinking you had a "full index" which takes up much more space on your hard drive, but has no missing "chunks". A partial index only download the parts of the index it needs. Maybe something is going wrong there.)

We can proceed thus:

Please send me the results of `chifra chunks blooms` and also (if possible) a list of all the addresses you've previous queried -- this may not work -- but perhaps `history | grep "chifra export"`.

This will (hopefullly) allow me to reproduce your "situation" and from there, I may be able to better help you debug this issue.

Sorry this is so complicated, but -- it's complicated...

**Comment by Vasiliy-Bondarenko** [comment]
[blooms.txt](https://github.com/TrueBlocks/trueblocks-core/files/9863425/blooms.txt)

address list (out of order)
- 0x054993ab0f2b1acc0fdc65405ee203b4271bebe6
- 0xAA877d440fa75Ac41E8C7704637C0F1791b12114
- 0xED333fA03cf2d41898671475aB056461a2879270
- 0xB487562715aC79C81C44830F964c8c65a4b76CBD

**Comment by Vasiliy-Bondarenko** [comment]
@tjayrush hello. any updates on the issue? anything i can help with?

**Comment by tjayrush** [comment]
Sorry, this is taking so long. I guess I'm not noticing your responses to GitHub. If you ping me in the discord channel after responding here, I'll respond more quickly.

I checked your list of bloom filters against mine, and (thankfully) we have the exact same data (with the exception that I have more bloom filters You can run `chifra init` and then `chifra scrape` to catch up).

If we have the exact same bloom filters, then this command should produce the exact same results:


```
chifra list --fmt csv 0x054993ab0f2b1acc0fdc65405ee203b4271bebe6 0xAA877d440fa75Ac41E8C7704637C0F1791b12114 0xED333fA03cf2d41898671475aB056461a2879270 0xB487562715aC79C81C44830F964c8c65a4b76CBD | tee export.csv
```

Can you send me the results of that? Here's my results:

[export.csv](https://github.com/TrueBlocks/trueblocks-core/files/9912034/export.csv)

**Comment by Vasiliy-Bondarenko** [comment]
i don't want and can't do `chifra scrape` because i requires to have a full node which i don't have right now on hand. i was trying to play with the software without putting the effort of running a full node from the start. so i have initialised with `chifra init` only - it's mentioned in my second message.

 output of `chifra list --fmt csv 0x054993ab0f2b1acc0fdc65405ee203b4271bebe6 0xAA877d440fa75Ac41E8C7704637C0F1791b12114 0xED333fA03cf2d41898671475aB056461a2879270 0xB487562715aC79C81C44830F964c8c65a4b76CBD | tee export.csv` 
is here:
[export.csv](https://github.com/TrueBlocks/trueblocks-core/files/9916589/export.csv)

**Comment by Vasiliy-Bondarenko** [comment]
i don't want and can't do `chifra scrape` because i requires to have a full node which i don't have right now on hand. i was trying to play with the software without putting the effort of running a full node from the start. so i have initialised with `chifra init` only - it's mentioned in my second message.

 output of `chifra list --fmt csv 0x054993ab0f2b1acc0fdc65405ee203b4271bebe6 0xAA877d440fa75Ac41E8C7704637C0F1791b12114 0xED333fA03cf2d41898671475aB056461a2879270 0xB487562715aC79C81C44830F964c8c65a4b76CBD | tee export.csv` 
is here:
[export.csv](https://github.com/TrueBlocks/trueblocks-core/files/9916589/export.csv)

**Comment by Vasiliy-Bondarenko** [comment]
@tjayrush any updates on this?

**Comment by tjayrush** [comment]
> i don't want and can't do chifra scrape because i requires to have a full node

I think this may have something to do with the problem. TrueBlocks "requires" a full node, so it really doesn't matter if you "want to" use one. You have to have one.

I'm convinced (given the results above which indicate that there were errors during the download) and the fact that when I run against your addresses, I see the transactions you're looking for, that you have a corrupted index.

What I would do, if I were you, would be to run

```
chifra chunks index --truncate 10277711
```

which will remove all parts of the index at or after block 10277711, and then run

```
chifra init
```

and then try the query again.

My great preference would be for you to have access to an archive/tracing node (which is different from a full node), as we've never really even tested running against a non-archive, non-tracing node.

I'd also prefer to see you using `chifra init --all` which downloads all the index portions at once (it does take up about 100GB, whereas `chifra init` only requires 4GB plus whatever your addresses need. The non "--all" mode has been tested, but it's a bit less well tested than the `--all` mode.

In either case, you will need to be running `chifra scrape` (which is the part that requires the tracing node) to get "new" data past the `chifra init`.

**Comment by tjayrush** [comment]
I believe this is fixed. Please reopen if you disagree.

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @Vasiliy-Bondarenko)
