### ISSUE TITLE
Add section to README for 'resources' for getting started

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#2505]
**As per a user:**

Hey. Maybe you can add a section that points to good resources & suggested setup (Erigon + recommended CL) on how to spin up an Erigon node. I found this post very useful at that time.  https://trueblocks.io/blog/installing-erigon-and-trueblocks-as-services-on-ubuntu/  Magnus also posted a post mergue guide https://magnushansson.xyz/blog_posts/crypto_defi/2022-09-15-Erigon-Merge

**Comment by wschwab** [comment]
I'm writing a guide to how I got started, I expect to publish within the next month or so. It would probably be a bit informal for docs, but I'm happy to share what I've got now, and you're welcome to take anything you want from it.
