### ISSUE TITLE
chifra export allow to filter failed transactions for an address

### ISSUE THREAD

**Issue by yabirgb** [TrueBlocks/trueblocks-core#2550]
## Request

It would be helpful for me to track transactions that failed to execute for a given address. There are multiple scenarios where this is useful but one that might help many is computing the amount of ETH wasted on failed transactions.

## How to use it

I believe a good approach to consume this resource would be adding a new argument to the `/export` endpoint that allows to filter the returned transactions, for example, `onlyReverted: bool`

**Comment by tjayrush** [comment]
Done. Use `--reverted`.
