### ISSUE TITLE
chifra export Add filtering on output address for chifra  export

### ISSUE THREAD

**Issue by noegracia** [TrueBlocks/trueblocks-core#2562]
Right now we can get the OUT transactions of an address by `chifra  export  ADDRESS_1 -f out --statements `
It could be nice if we could add one or multiple out addresses with a flag like `-to ADDRESS_2 ADDRESS_3 ....` in order to filter the result
The result should be the same as `chifra export ADDRESS_1 -f out --statements | grep ADDRESS_2`

**Comment by tjayrush** [comment]
Two quick questions before I move forward on this:

1. Sometimes, I like to leave the way things work more "linux" like in the sense that piping through `grep` works (as you point out). Can you tell me why `grep` doesn't work? Not saying this is a killer reason why NOT to do this, but I just wonder.

2. Are you aware of the `--emitter` option for `chifra export --logs`? It only generates logs for events generated by the given smart contract. You may add multiple emitters.

If we do add this feature, do you think it would be worth extending the way `--emitter` works?

Also, for `chifra export --traces`, how might this work?

How about for `chifra export --statements`? Would it be any statement with `recipient` == to the address?

It's not a difficult thing to add, but I'd like to think more broadly so we don't get a disjointed collection of solutions for similar problems...

Your thoughts would be appreciated.

**Comment by tjayrush** [comment]
Any thoughts on this? I'm going to try to work on it this coming week.

**Comment by tjayrush** [comment]
We're going to leave this as it is. One cannot really get just `--flow out` transactions with a `grep`, but as the OPs comments makes clear, one can get the `--to` behaviour using `grep`. Stick with the Linxuy way of doing things. Closing.
