### ISSUE TITLE
chifra scrape - better reporting

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#2581]
It would make debugging much easier if I

1. Added commas to the block numbers being displayed,
2. Generated a 'progress' after each scrape in the same way as `chifra status --terse`

**Comment by LoboSolitario** [comment]
I noticed one more issue with this @tjayrush .
If we do `chifra status --terse`, it gives the wrong `staging` value. 
![image](https://user-images.githubusercontent.com/33311245/208107807-e02c8366-de7b-4a0c-a4a1-e1f8ab380fef.png)

**Comment by tjayrush** [comment]
Is this the issue where it's reporting the first number in the staging file vs. the second? That is the first 'staged' block as opposed to the last 'staged' block which is what you need?

**Comment by LoboSolitario** [comment]
Exactly right. It should be changed from first staged block to the last staged block (~currentBlock - 28)

**Comment by tjayrush** [comment]
This is fixed.
