### ISSUE TITLE
chifra cmd - When porting to Go is done, store addresses and hashes as binary

### ISSUE THREAD

**Issue by dszlachta** [TrueBlocks/trueblocks-core#2585]
It would make sense to store addresses and hashes as bytes in cache files (currently they're strings).
> _tjayrush_:
> Can you write an issue that says something like: "Once we move to pure GoLang cache for all types, we want to store addresses and hashes as binary bytes (as opposed to translate them into strings). I think this will cut the size of the cache in half" (Assuming that this is true. Is it?)
> _dawid_:
> Yeah, and it should be easy because we already use common.Hash and common.Address in Go code

**Comment by tjayrush** [comment]
Also: there's this related to the need to reverse the C++ strings:  https://github.com/golang/go/issues/40891.

Search for `func reverseBytes(original []byte) (reversed []byte) `

**Comment by tjayrush** [comment]
I'm going to close this. It will naturally happen when we go to using the actual GoLang caching code and have an upgrade facility.
