### ISSUE TITLE
chifra export --traces doesn't check the cache without --cache_traces

### ISSUE THREAD

**Issue by wakamex** [TrueBlocks/trueblocks-core#2675]
```
chifra export 0x422494292e7a9dda8778bb4ea05c2779a3d60f5d --traces --factory  1.69s user 0.21s system 2% cpu **1:17.35 total**
chifra export 0x422494292e7a9dda8778bb4ea05c2779a3d60f5d --traces --factory **--cache_traces**   0.34s user 0.10s system 113% cpu **0.390 total**
```
200x faster using --cache_traces (order doesn't matter)

as opposed to --logs, where without --cache, the cache is still read from, just not written to
```
chifra export 0x422494292e7a9dda8778bb4ea05c2779a3d60f5d --logs  0.63s user 0.24s system 127% cpu **0.678 total**
chifra export 0x422494292e7a9dda8778bb4ea05c2779a3d60f5d --logs **--cache**  0.75s user 0.32s system 132% cpu **0.805 total**
```

good first issue? 😀

**Comment by tjayrush** [comment]
It's a bit surprising that it acts this way, to be honest.

The first command (`--traces` without `--cache`) should be faster than the second because my thought is that the second would be identical to the first with the added downside of writing the cache. That's odd.

The second example (for `--logs`) makes more sense.

So maybe we can do a test as follows:

```
time chifra monitors <address> --decache                         # clears the cache
time chifra export <address> --traces --factory                 # should run without writing the cache
time chifra export <address> --traces --factory --cache  # should run without writing the cache
time chifra export <address> --traces --factory                 # this run should be way faster
time chifra export <address> --traces --factory --cache  # this run should be identically as fast as the previous
```

The same should happen with `--logs`:

```
time chifra monitors <address> --decache     # clears the cache
time chifra export <address> --logs                 # should run without writing the cache
time chifra export <address> --logs --cache  # should run without writing the cache
time chifra export <address> --logs                 # this run should be way faster
time chifra export <address> --logs --cache  # this run should be identically as fast as the previous
```

**Comment by tjayrush** [comment]
848 transactions in account 0x422494292e7a9dda8778bb4ea05c2779a3d60f5d

| Run                       | S    | Ms    | Tx / Sec | Comments                                           |
| ------------------------- | ---- | ----- | -------- | -------------------------------------------------- |
| clear cache...            |      |       |          |                                                    |
|                           |      |       |          |                                                    |
| --trace --factory         | 188s | 480ms | 4.50     |                                                    |
| --trace --factory --cache | 196  | 390   | 4.32     | slower when writing to cache (makes sense)         |
| --trace --factory         | -    | 629   | 1,348.17 | much faster when reading from cache (makes sense)  |
| --trace --factory --cache | -    | 781   | 1,085.79 | slower when reading and writing (slightly strange) |
|                           |      |       |          |                                                    |
| clear cache...            |      |       |          |                                                    |
|                           |      |       |          |                                                    |
| --logs --cache            | 14   | 760   | 57.45    |                                                    |
| --logs --cache            | 10   | 250   | 82.73    | faster when writing to cache (strange)             |
| --logs --cache            | -    | 516   | 1,643.41 | much faster when reading from cache (makes sense)  |
| --logs --cache            | -    | 803   | 1,056.04 | slower when reading and writing (slightly strange) |

**Comment by tjayrush** [comment]
> good first issue? 😀

Maybe. When you say in the title of the issue that it "doesn't read the cache" is that because you looked at the code or just based on performance?

**Comment by tjayrush** [comment]
This is fixed.
