### ISSUE TITLE
trace_filter definition

### ISSUE THREAD

**Issue by villanuevawill** [TrueBlocks/trueblocks-core#2702]
https://github.com/TrueBlocks/trueblocks-docs/blob/5e208d595c265644aa8cfe630ec51fb2388392d9/content/chifra/chaindata.md?plain=1#L235

I can put up a quick PR - but which filter is this supposed to be referencing? Transaction?

**Comment by wakamex** [comment]
are you asking how to do a 1-line PR to rename `fitler` to `filter`?

**Comment by tjayrush** [comment]
@villanuevawill It tries to send the same filter as is required by `trace_filter` routine in the RPC.

The command line is parsed here (https://github.com/TrueBlocks/trueblocks-core/blob/master/src/tools/getTraces/options.cpp#L91) and the data structure is defined here (https://github.com/TrueBlocks/trueblocks-core/blob/master/src/libs/etherlib/tracefilter.h#L26) and used here (https://github.com/TrueBlocks/trueblocks-core/blob/master/src/tools/getTraces/main.cpp#L32) to call this function (https://github.com/TrueBlocks/trueblocks-core/blob/master/src/libs/etherlib/node.cpp#L570) which builds the query and returns the result to the caller.
