### ISSUE TITLE
chifra abis - doesn't appear to know about proxies

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#2711]
This command

```
chifra abis 0x99b36fdbc582d113af36a21eba06bfeab7b9be12
```

reports nothing. But this command

```
chifra explore 0x99b36fdbc582d113af36a21eba06bfeab7b9be12
```

https://etherscan.io/address/0x99b36fdbc582d113af36a21eba06bfeab7b9be12#readProxyContract

shows a smart contract that is a proxy. If EtherScan can figure this out, we should be able to as well.

**Comment by CyMule** [comment]
# Observation

Is this only the case for for contracts that don't abide by [EIP-1967](https://eips.ethereum.org/EIPS/eip-1967)?
As in `chifra abis` already understands proxies that abide by EIP-1967?

## Aave V2 (abides by EIP-1967)
`chifra abis 0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9`  (proxy address for [Aave V2](https://etherscan.io/address/0x7d2768de32b0b80b7a3454c06bdac94a69ddc7a9)) returns:
```
encoding        type    name    signature       input_names     output_names
0x3659cfe6      function        upgradeTo       upgradeTo(address)      newImplementation,      ,
0x4f1ef286      function        upgradeToAndCall        upgradeToAndCall(address,bytes) newImplementation,data, ,
0x5c60da1b      function        implementation  implementation()                val_0,,
0xbc7cd75a20ee27fd9adebab32041f755214dbc6bffa90cc0225b39da2e5c2d3b      event   Upgraded        Upgraded(address)       implementation, ,
0xd1f57894      function        initialize      initialize(address,bytes)       _logic,_data,   ,
0xf851a440      function        admin   admin()         val_0,
```

## 0x99b36fDbC582D113aF36A21EBa06BFEAb7b9bE12 (doesn't abide by EIP-1967)
Etherscan labels as 0x99b36fDbC582D113aF36A21EBa06BFEAb7b9bE12 as GnosisSafeProxy.

I checked the contract and found that the implementation/logic address of the contract is stored in storage slot 0.
The following code:
```python
from web3 import Web3, HTTPProvider
w3 = Web3(HTTPProvider('https://YOUR_RPC_HERE')) 
# 0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc
# is obtained from bytes32(uint256(keccak256('eip1967.proxy.implementation')) - 1)
# in accordance with EIP-1967
print(w3.eth.get_storage_at('0x99b36fDbC582D113aF36A21EBa06BFEAb7b9bE12', 0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505
d382bbc).hex())
print(w3.eth.get_storage_at('0x99b36fDbC582D113aF36A21EBa06BFEAb7b9bE12', 0).hex())
```
returns
```
0x0000000000000000000000000000000000000000000000000000000000000000
0x000000000000000000000000d9db270c1b5e3bd161e8c8503c55ceabee709552
```
where the storage slot 0 references the implementation/logic address of the contract found here [0xd9Db270c1B5E3Bd161E8c8503c55cEABeE709552](https://etherscan.io/address/0xd9Db270c1B5E3Bd161E8c8503c55cEABeE709552)

# Solution

It appears that the solution to cover GnosisSafeProxies might be to check if etherscan labels the contract GnosisSafeProxy, and if it does then grab the ABI for the implementation/logic contract that is stored in storage slot 0 of the proxy contract.

I am not 100% sure that this is the case for all GnosisSafeProxies. This is solely my observation from this example, but I can take a deeper dive to resolve this.

Are there any other preferred alternatives to this solution?

**Comment by tjayrush** [comment]
Thanks so much for this.

Unfortunately, we can't use EtherScan as our desire is to be 100% decentralized. We want a solution who's only source of information is on-chain.

This code may be of interest: https://github.com/TrueBlocks/trueblocks-core/blob/master/src/libs/etherlib/ethcall.cpp#L482.

(This is in the context of calling a smart contract as opposed to decoding byte streams, but it's a similar idea.)

Here, we try the suggested function against the proxied-for contract and only if that fails do we fall back to making the assumption it's a proxy and seeing if that works. (Failing if neither methods work.)

For the ABI case, we might request the ABI at the contract itself and then, if the ABI reports an `implementation` endpoint, query that as well and report the proxy interfaces.

**Comment by CyMule** [comment]
## Correcting Myself

The reason `chifra abis 0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9` works is just because there are actually 5 public write functions for the proxy contract which makes sense. I didn't see those initially. So chifra doesn't know about the proxies.

## Is this actually correct behavior?

- Should `chifra abis`  return the abi for the implementation contract?
- Should this happen automatically? With a flag?
- Just show a message saying this is a proxy?
- Return the implementation ABI only if (like in the case of `chifra abis 0x99b36fdbc582d113af36a21eba06bfeab7b9be12`) there are no public functions on the proxy?

I'm not confident that it makes sense to automatically return the ABI for the implementation contract as it would prevent a user from getting the ABI of the proxy itself. Maybe a flag like `--follow-if-proxy` (but better named) could be added to return the ABI of the implementation contract instead of the proxy contract in the case of a proxy?

**Comment by tjayrush** [comment]
In the best of all worlds, it would be nice if we could tell that the contract is a proxy.

(Are there multiple ways? (1) it has an `implementation` function, (2) it has what appears to be a contract address at a known location in storage, (3) it has no public functions...(4) other?)

If we suspect it's a proxy, we could then report those "proxied-to" functions (without requiring a flag). (We can take a hint of the way EtherScan does it.)

Maybe the output would have an additional field or the already existing field called `type` could take on different values such as `proxied-function` or `proxied-event`.

I'm open to a flag, but maybe we can avoid it. If we sort of "automatically" report both `proxy-only` and `proxied-to` functions and events, users would catch on pretty quickly, I think.

**Comment by CyMule** [comment]
> (Are there multiple ways? (1) it has an implementation function, (2) it has what appears to be a contract address at a known location in storage, (3) it has no public functions...(4) other?)

Relying on 1 and 2 seems reasonable. If we don't find the implementation address from 1 or 2, then we won't be able to get the ABI anyway so I think 3 can be ignored.

> Maybe the output would have an additional field or the already existing field called type could take on different values such as proxied-function or proxied-event.

This makes sense to me.

**Comment by tjayrush** [comment]
We added a `--proxy_for` option that will work for now. It could be automated, but we will add that at a later point.
