### ISSUE TITLE
chifra scrape - missing unchained index for gnosis

### ISSUE THREAD

**Issue by ghost** [TrueBlocks/trueblocks-core#2713]
Hello, unchained index for gonsis chain was published last time 75 days ago:
https://etherscan.io/tx/0xb02c633ee2e639e746f667887aa4ed4442ac3f256107590e189f66b562f5b314

**Comment by tjayrush** [comment]
That was probably right around the time they went through their own The Merge.

We've not had the resources necessary to produce the index on our machines as we've not had the ability to install and run the new node software.

But...not all is lost...are you indexing Gnosis?

The Unchained Index is purposefully permissionless which means anyone may publish an IPFS has to the manifest.

And/or you could help us figure out how to upgrade to the new chain. I'm very, very good with data pipelines and writing GoLang and C++ code. I suck at DevOps which is what I need to do to get Gnosis back on-line.

**Comment by ghost** [comment]
I am developing app, now it's okay for me to test on ethereum mainnet, but more networks is much better.
No, I don't index Gnosis, because I don't have ability launch archive node right now.
Mostly, gnosis setup should have the same steps as in ethereum mainnet, launch consensus layer, execution layer...

**Comment by tjayrush** [comment]
I'm going to close this as stale. One day we hope to get back to indexing Gnosis, but that day is not today. Please reopen if you wish and, maybe, to tell us that you're going to generate the Gnosis index.
