### ISSUE TITLE
Change EXISTING_CODE tags to HTML-style angle brackets

### ISSUE THREAD

**Issue by CyMule** [TrueBlocks/trueblocks-core#2714]
As a new contributor, I've found the current method of differentiating existing code and generated code through the use of `// EXISTING_CODE` tags to be unclear. It would be beneficial if the tags were replaced with HTML-style angle brackets to more distinctly indicate the start and end of existing code.

For instance, instead of:
```golang
// EXISTING_CODE
... existing code ...
// EXISTING_CODE
```
it could be written as:
```golang
// <EXISTING_CODE>
... existing code ...
// </EXISTING_CODE>
```

Alternatively, the tags could be changed to `// EXISTING_CODE_START` and `// EXISTING_CODE_END`.

The code handling these tags is located in `src/dev_tools/makeClass/handle_codewriting.cpp`.

This is not a major issue, but it could improve the clarity of the codebase, especially for new contributors who are not as familiar with it. The use of HTML-style angle brackets would make it easier to distinguish the start and end of existing code, which could help streamline the contribution process.

**Comment by tjayrush** [comment]
Good thought. I've been looking at this for so long, I never re-considered it, but it makes total sense.

A new contributor (or any contributor for that matter) would have trouble distinguishing between code inside the tags and code outside the tag.

This wouldn't be that hard to change. I'll do this one of those days where I feel like procrastinating.
