### ISSUE TITLE
chifra export - weird behaviour between API and command line

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#2738]
From a user:

when I try this url:

 /export?addrs=0x087C35C7bfDE457304604c7c512d8616Ef8d4A5b&addrs=0x2e8AcA22060ada53bDb1600bF89A5f0D228f3f0d&firstBlock=16472534&reversed=true&logs=true&emitter=0x5283d291dbcf85356a21ba090e6db59121208b44&emitter=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2&relevant=true 

I get a blank screen and no response or error... then if I remove the second emitter address, it works fine. 
Is it a bug or am I entering something wrong? 
This command works fine though

chifra export 0x087C35C7bfDE457304604c7c512d8616Ef8d4A5b 0x2e8AcA22060ada53bDb1600bF89A5f0D228f3f0d --first_block 16472534 --logs --emitter 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 --emitter 0x5283d291dbcf85356a21ba090e6db59121208b44 -x json --relevant

**Comment by tjayrush** [comment]
For future reference:

I suppose the obvious interpretation is "in the context of transactions for address X, show all events emitted by either contract A or contract B." Is that what you're looking for?

User:

Yes.

**Comment by tjayrush** [comment]
Question: Is that what the command line generates?

**Comment by trand2** [comment]
Yes. that's correct. 

In this specific example it has two addresses so it should be written as "in the context of transactions for address X or address Y, show all events (logs) emitted by either contract A or contract B.".
