### ISSUE TITLE
Add 'value' field when exporting logs

### ISSUE THREAD

**Issue by trand2** [TrueBlocks/trueblocks-core#2739]
For example, add this `value` line from the transactional data:

`"value": 462767059307997620`

to this exported log:

```
{
   "address": "0x57f1887a8bf19b14fc0df6fd9b2acc9af147ea85",
   "blockNumber": 16604862,
   "logIndex": 172,
   "topics": [
     "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
     "0x000000000000000000000000087c35c7bfde457304604c7c512d8616ef8d4a5b",
     "0x0000000000000000000000000000000000000000000000000000000000000000",
     "0x39c43b87cd2effff005855467b70ec0ebacd1326290c001ebe80a796a6da6503"
   ],
   "data": "0x",
   "compressedLog": "",
   "transactionHash": "0x85cf93e1ba51c14dd1ff69741f6003b5fb5eb9552c6aa6d7954311e1cdb7809b",
   "transactionIndex": 107
}
```

**Comment by tjayrush** [comment]
The `value` field is not part of the log data structure, it's part of the transaction data structure. We only return what the Erigon RPC gives to us, so if we were to do this, we would have to make two calls for every one log requested. We decided not to do that. If we do it, everyone gets hit. If we require the caller to call the transaction themselves and join the results, only callers who need value get hit.

Does that make sense?

The basic idea is that TrueBlocks generally returns what we're given by the RPC and we avoid calling multiple times to "build" the data up.

With one exception. We do call for the receipt when doing a call to `eth_getTransaction`. In other words we go down the tree. We don't go up. So, you could call `chifra transactions` and you would get all the log data (and `value`) but to get that data the other way, you'd have to make two calls.

Hope that helps.

**Comment by trand2** [comment]
That makes sense. Thanks for clarifying. I'll go ahead and close this then.

**Comment by tjayrush** [comment]
Let me know if you need any other help.
