### ISSUE TITLE
chifra scrape on an unsynchronized node

### ISSUE THREAD

**Issue by maximebucher** [TrueBlocks/trueblocks-core#2750]
Hello, 

is it possible to run the function chifra scrape on an unsynchronized node?

if not, is it possible to apply the function  chifra scrape on a range of blocks only? The ones already synchronized.

Thanks!

**Comment by tjayrush** [comment]
The trouble, you'll find, at least with Erigon is that Erigon does not respond to it's RPC (or responds with empty data) until it gets through it's first synchronization pass. After that first pass, `chifra scrape` should scrape right up until the latest block Erigon synced.

Said another way -- Erigon reports block `0` until its first sync pass is finished. `chifra scrape` scrapes to `0`. Once Erigon is finished it's first pass, it will report to that block -- and then `chifra scrape` will catch up.

If you quit Erigon and restart before it finishes its first pass, it starts at the last block it synced and proceeds to a new head, but it still reports `0`.

Said yet one more way -- Erigon syncs in stages. If finishes one stage before starting another. Until it gets to the end of the last stage, it reports `latest` block as `0`.

**Comment by tjayrush** [comment]
If this answers your question, please close this. If you wish to create a feature request (concerning syncing from blocks of ranges), please do. However, please try to be as specific as you can to help us understand better.

One thing I've thought of is this:

1) chifra scrape --first_block X
2) Read the existing manifest and snap to the block at the end of last full chunk before X. Call this block S.
3) Start the scrape at S+1

Would that work? If yes, please copy this to a feature request and close this issue. Thanks.

**Comment by maximebucher** [comment]
Thank you very much for your answer.
