### ISSUE TITLE
chist list ignores --first_block / --last_block

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#2819]
Do this:

```
chifra list trueblocks.eth | wc
```

get a number (X).

Then this

```
chifra list trueblocks.eth --first_block 16500000 | wc
```

You should get a number smaller than X. Then do this:

```
chifra list trueblocks.eth --count
```

You should get X.

Then do:

```
chifra list trueblocks --first_block 16500000 --count
```

~You don't get X.~ You get X, but that's the problem. You should get the same smaller number than X.

Temporary Fix
============
While this is being fixed, you can either do what we did above (`chifra export <address> | wc`) or do something like this with `awk`: https://unix.stackexchange.com/questions/188095/remove-lines-where-a-fields-value-is-less-than-or-equal-to-3-sed-or-awk.

**Comment by dszlachta** [comment]
Started work here: `feature/2819_chifra_list_range`
