### ISSUE TITLE
chifra list does not have an --unripe flag

### ISSUE THREAD

**Issue by juanlenoves** [TrueBlocks/trueblocks-core#2834]
Given that _**chifra list**_ functions very similarly to **_chifra export_**, other than not calling the node to export the entire transaction object, it makes sense that it should also have a flag to consider transactions newer than 28 blocks.

**Comment by tjayrush** [comment]
Agreed. I'll try to get this added soon.

**Comment by tjayrush** [comment]
This will be merged into `develop` tonight and added to `master` the next time we merge to master.
