### ISSUE TITLE
chifra names on rpc branch reports errors when running from command line

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#2837]
No big deal. Just recording this so I don't forget to tell you. No need to respond.

When I run your `rpc_names` branch, I get these errors for all command line tests (which pass otherwise). Maybe it's expected.

```
INFO[DATE|TIME] Not using RPC server because of error dial unix /tmp/trueblocks.sock: connect: connection refused
```

**Comment by dszlachta** [comment]
I'm aware of that. This branch is not ready for merging yet, so I left the message - it's useful when testing manually
