### ISSUE TITLE
How to integrate gRPC types

### ISSUE THREAD

**Issue by dszlachta** [TrueBlocks/trueblocks-core#2841]
While researching the usage of gRPC inside chifra, I've tried to replace our SimpleName type with the one defined in protobuffer file, but there were some issues:
- Address type has to be string or slice of bytes. There are no fixed length arrays in gRPC
- gRPC types want pointers as their values. In Go, there are no pointer literals (e.g. `object.Field = &address.Hex()`), so we would have to use a function or helper variable: `object.Field = utils.Ptr(address.Hex())` or `helperVar := address.Hex(); object.Field = &helperVar`
- We lose control over fields’ `”json:”` tags
- We can’t change the type without changing gRPC protocol
So I've decided to add methods to SimpleName that would convert between the two types. All fields of gRPC type are pointers, so no data is copied (I think)

These methods are here: https://github.com/TrueBlocks/trueblocks-core/blob/feature/grpc_names/src/apps/chifra/pkg/types/types_name.go#L217

**Comment by tjayrush** [comment]
Isn't this and all following lines copying? In C++, that syntax copies the bytes to a new location.

https://github.com/TrueBlocks/trueblocks-core/blob/feature/grpc_names/src/apps/chifra/pkg/types/types_name.go#L242

**Comment by tjayrush** [comment]
Concerning this point:

> Address type has to be string or slice of bytes. There are no fixed length arrays in gRPC

I've been thinking about this. I'm not sure we "have to" have address stored as a fixed width bytes in our code. It comes from the node's RPC as a string, we convert it to an common.Address, then we bounce it around for a while and convert it right back into a string to present it (in the model). We could just leave it a string and always reference it with a pointer so that there's only ever one copy which is the memory returned by the RPC.

If we wanted to (because of size or speed) we could convert it into bytes when writing to the cache, but other than that, I'm not sure why we convert it. Hashes are nearly identical and even worse because we never actually do anything with hashes other than shuttle them around.

**Comment by tjayrush** [comment]
Concerning this:

> We can’t change the type without changing gRPC protocol

This is already true of our cache. Plus, I imagine gRPC must have versioning of some type.

And, I'm just thinking out loud now -- maybe gRPC is our cache format.

**Comment by tjayrush** [comment]
Concerning this:

> We lose control over fields’ ”json:” tags

Can you explain this more? Why is this? If we're able to edit the gRPC protocol file why can't we edit this? Or does it require a certain format?

**Comment by dszlachta** [comment]
> Isn't this and all following lines copying? In C++, that syntax copies the bytes to a new location.
> 
> https://github.com/TrueBlocks/trueblocks-core/blob/feature/grpc_names/src/apps/chifra/pkg/types/types_name.go#L242

You're right, sorry. But I'm still getting almost identical performance to `rpc` branch, so maybe it's not so costly...

**Comment by dszlachta** [comment]
> Concerning this point:
> 
> > Address type has to be string or slice of bytes. There are no fixed length arrays in gRPC
> 
> I've been thinking about this. I'm not sure we "have to" have address stored as a fixed width bytes in our code. It comes from the node's RPC as a string, we convert it to an common.Address, then we bounce it around for a while and convert it right back into a string to present it (in the model). We could just leave it a string and always reference it with a pointer so that there's only ever one copy which is the memory returned by the RPC.
> 
> If we wanted to (because of size or speed) we could convert it into bytes when writing to the cache, but other than that, I'm not sure why we convert it. Hashes are nearly identical and even worse because we never actually do anything with hashes other than shuttle them around.

I totally agree. We should observe performance boost if we decide to change Address to string. And just as you said, we store them in bytes but convert back to strings everywhere

**Comment by dszlachta** [comment]
> Concerning this:
> 
> > We can’t change the type without changing gRPC protocol
> 
> This is already true of our cache. Plus, I imagine gRPC must have versioning of some type.

Yes, what I meant there is that there's an extra step involved if we want to add a field to a type (changing protobuffer file and regenerating client/server files)

> And, I'm just thinking out loud now -- maybe gRPC is our cache format.

This is true for both gRPC and Go's `rpc` package (the latter uses `encoding/gob` to turn data into bytes).

**Comment by dszlachta** [comment]
> Concerning this:
> 
> > We lose control over fields’ ”json:” tags
> 
> Can you explain this more? Why is this? If we're able to edit the gRPC protocol file why can't we edit this? Or does it require a certain format?

I don't think there's protobuffer syntax to change `omitempty`. There's one for setting `"json:differentKeyName"`. I also can't find a syntax to add custom structure tags.

I'm just noting this issues so that we're aware of them. I'm not saying we shouldn't go with gRPC because of them. The huge benefit of using gRPC is generating client SDK libraries in different languages.
