### ISSUE TITLE
chifra init - protect against control+c while download timestamp file

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#2851]
A user reports that the timestamp file was corrupted by hitting control+c during download. It should be protected with the trap, but it appearently is not. Protect the download of timestamp better. Note that downloading the index portions is already protected.

**Comment by sarob** [comment]
`$ chifra init
INFO[11-04|15:12:16.312] Chain: mainnet
INFO[11-04|15:12:16.312] Gateway: https://ipfs.unchainedindex.io/ipfs/
INFO[11-04|15:12:16.312] CID: QmZwMnV8uudW2J2HBMnVZV16TZpRV4xHCA1Zq2aJefY5Sv
INFO[11-04|15:12:16.312] URL: https://ipfs.unchainedindex.io/ipfs/QmZwMnV8uudW2J2HBMnVZV16TZpRV4xHCA1Zq2aJefY5Sv
WARN[11-04|15:12:16.312] Downloading timestamp file. This may take a moment, please wait...
^Z
[2]+  Stopped                 chifra init

$ chifra init
FATL[11-04|15:18:51.670] While parsing config: (29, 2): duplicated tables
`

**Comment by tjayrush** [comment]
@sarob. Thanks for your report. May I ask you: does the ^Z indicate you `paused` the process as opposed to Control+C killed it? I'm kind of not surprised that something doesn't work in that case. It's like the guy who says to the doctor, "It hurts when I do this," and the doctor says, "Don't do that..."

Or, maybe I'm misunderstanding...

**Comment by tjayrush** [comment]
Most likely a duplicate of #2321. Closing soon...

**Comment by tjayrush** [comment]
This is done.
