### ISSUE TITLE
chifra names - query ENS when calling names --clean

### ISSUE THREAD

**Issue by dszlachta** [TrueBlocks/trueblocks-core#2911]
As pointed out by @tjayrush, it could be useful to query ENS and keep the response in our names database. We don't want to do it too often, so `names --clean` or `names --autoname` would be a good candidate.
> what do we do with ENS names? It feels like we don't want to query for them (especially during reconciliation), but they are SUPER useful in helping people understand what's going on.
ABI files and names are similar in that sense -- we need them because they are SO helpful in aiding understanding, but we don't want to query for them all the time. Perhaps chifra names --clean is a good place to do that query once and store the result.
And, now that I think of it, when we do autoname, that could also look at ENS (not just the token name).

**Comment by tjayrush** [comment]
We do it during `chifra names --autoname` but not clean.

**Comment by tjayrush** [comment]
This would involve adding a new field to the names database. I don't want to do that (not worth the effort), so closing.
