### ISSUE TITLE
export doesn't work

### ISSUE THREAD

**Issue by 32ethers** [TrueBlocks/trueblocks-core#2919]
I installed chifra following turtoial at https://trueblocks.io/docs/install/install-core/,

Environment: 
* ubuntu 22.04
* go version 1.20
* Eth RPC: erigon + lighthouse + rpcdaemon

I compled chifra, and init it with ```chifra init --all```

Then I tried query address following turtoial in https://trueblocks.io/blog/recipe-list-tokens-i-own/, 

List function is normal, `````

```
> chifra list 0x4A10307E221781570E4B7E409EB315F11E8D0385
address blockNumber     transactionIndex
0x4a10307e221781570e4b7e409eb315f11e8d0385      11148912        139
0x4a10307e221781570e4b7e409eb315f11e8d0385      11150508        133
0x4a10307e221781570e4b7e409eb315f11e8d0385      11150618        94
0x4a10307e221781570e4b7e409eb315f11e8d0385      11150644        100
...
```

but when I export transactions, I just got some column headers

```
> chifra export --fmt csv 0x4A10307E221781570E4B7E409EB315F11E8D0385
"blockNumber","transactionIndex","date","timestamp","from","to","ether","ethGasPrice","gasUsed","hash","isError","encoding","compressedTx"
```

If I export json, I can get some additional info: 

```
> chifra export --fmt json 0x4A10307E221781570E4B7E409EB315F11E8D0385

{ "data": [
] }21242 ( 121242)- <PROG>  : Extracting 456 of 455 txs at block 0 for address 0x4a10307e221781570e4b7e409eb315f11e8d0385

```

It seems chifra can find txs, but it will try to export at block 0

So I add L parameter to search from some height, It doesn't work too. 

```
> chifra export --logs -v --log_level 5 -F 10000000 --fmt json 0x4A10307E221781570E4B7E409EB315F11E8D0385
00120339 ( 120339)- : 4-----Loaded timestamp file
{ "data": [   437)- <PROG>  : Extracting 456 of 455 txs at block 0 (found 0 logs) for address 0x4a10307e221781570e4b7e409eb315f11e8d0385
] }
```

Is that a bug or I missed something? Thanks.

**Comment by tjayrush** [comment]
A couple of things to try:

0. Run `chifra status` and copy the results here.

2. `chifra monitors --decache <address>` -- this will remove the address and all associated transactions, blocks, logs, and traces from the cache. Might not fix things, but it cannot hurt and if you do this before each "experiment" you'll know where you're starting at.

3. Try `chifra chunks index --check`. It takes a minute, but it should report (basically) "all clear". If it reports any errors, please stop the experiment and let me know (it will help me figure out what may have gone wrong).

4. If the above works, you can try `chifra init --all` again. You can repeat this command as often as you like. If it finds anything it doesn't like, it will try to repair itself. You can run it multiple times until it reports no further anything to download.

Between each of these tests, you can re-try both `chifra list` and `chifra export` (note that `chifra list` actually gets called by `chifra export`, so it's redundant). Make sure though, if something doesn't seem to work to re-run the `--decache` option so you start from scratch each time.

Complete the above steps and please then let me know what you find. This at least will give me some information.

Note, you can always re-run `chifra status` as well and this may give you some useful information.

**Comment by 32ethers** [comment]
Hi Thomas:

I checked chifra's status, it seems normal.

```
> chifra status
16-05|02:09:39.453 Client:            erigon/2.43.0/linux-amd64/go1.20.3 (archive, tracing)
16-05|02:09:39.453 TrueBlocks:        GHC-TrueBlocks//0.64.0-beta (no eskey, no pinKey)
16-05|02:09:39.453 RPC Provider:      http://localhost:8545 - mainnet (1/1)
16-05|02:09:39.453 Root Config Path:  /home/eth/.local/share/trueblocks/
16-05|02:09:39.453 Chain Config Path: /home/eth/.local/share/trueblocks/config/mainnet/
16-05|02:09:39.453 Cache Path:        /node1/chifra/cache/mainnet/
16-05|02:09:39.453 Index Path:        /node1/chifra/index/unchained/mainnet/
16-05|02:09:39.453 Progress:          17269223, 17243635, 17243635, 17243635 ts: 884736
```

And clear cache did not report any error

```
eth@zelos-server01:~$ chifra monitors --decache  0x4A10307E221781570E4B7E409EB315F11E8D0385
INFO[16-05|02:04:58.102] Decaching 0x4a10307e221781570e4b7e409eb315f11e8d0385
INFO[16-05|02:04:58.279] 0 items totaling 0 bytes were removed from the cache.                                                             
INFO[16-05|02:04:58.279] Monitor 0x4a10307e221781570e4b7e409eb315f11e8d0385 was deleted but not removed.
INFO[16-05|02:04:58.279] Monitor for 0x4a10307e221781570e4b7e409eb315f11e8d0385 was permanently removed.

```

Index check doesn't show any error, too

```
eth@zelos-server01:~$ chifra chunks index --check
INFO[16-05|02:03:09.183] Chain: mainnet
INFO[16-05|02:03:09.183] Gateway: https://ipfs.unchainedindex.io/ipfs/
INFO[16-05|02:03:09.183] CID: QmctoKvvGsrr44PkRaJUjDZz6WrXhMNRHan7jHfHPgj7z9
{
  "data": [
    {
      "checkedCnt": 10965,
      "reason": "Filenames sequential",
      "result": "passed"
    },
    {
      "checkedCnt": 3656,
      "reason": "Internally consistent",
      "result": "passed"
    },
    {
      "checkedCnt": 14624,
      "reason": "Consistent hashes",
      "result": "passed"
    },
    {
      "checkedCnt": 3656,
      "reason": "Check file sizes",
      "result": "passed"
    },
    {
      "checkedCnt": 7312,
      "reason": "Remote Manifest to Cached Manifest",
      "result": "passed"
    },
    {
      "checkedCnt": 7312,
      "reason": "Disc Files to Cached Manifest",
      "result": "passed"
    },
    {
      "checkedCnt": 7312,
      "reason": "Disc Files to Remote Manifest",
      "result": "passed"
    }
  ]
}

```

Since I got some download error(connect reset by peer) on ``` chifra init --all ``` yestoday, I already tried this commend over again, until everything seems ok

```
> chifra init --all
INFO[16-05|02:17:07.768] Chain: mainnet
INFO[16-05|02:17:07.768] Gateway: https://ipfs.unchainedindex.io/ipfs/
INFO[16-05|02:17:07.768] CID: QmctoKvvGsrr44PkRaJUjDZz6WrXhMNRHan7jHfHPgj7z9
INFO[16-05|02:17:10.354] Unchained Index: 0x0c316b7042b419d07d343f2f4f5bd54ff731183d
INFO[16-05|02:17:10.354] Schemas: QmUou7zX2g2tY58LP1A2GyP5RF9nbJsoxKTp299ah3svgb
INFO[16-05|02:17:10.354] Config Folder: /home/eth/.local/share/trueblocks/config/mainnet/
INFO[16-05|02:17:10.354] Index Folder: /node1/chifra/index/unchained/mainnet/
INFO[16-05|02:17:10.354] Chunks in Manifest: 3656
INFO[16-05|02:17:10.354] Corrections Needed: 0
INFO[16-05|02:17:10.354] Completed initializing index files.                                                             
INFO[16-05|02:17:10.354] Completed initializing bloom files. 
```




initial of a export do show some thing useful, but the output is still empty

```
eth@zelos-server01:~$ chifra export --fmt csv 0x4a10307e221781570e4b7e409eb315f11e8d0385
INFO[16-05|02:01:21.552] 0x4a10307e221781570e4b7e409eb315f11e8d0385 appended 1 apps at 011147090-011150315
INFO[16-05|02:01:21.553] 0x4a10307e221781570e4b7e409eb315f11e8d0385 appended 15 apps at 011150316-011153264
INFO[16-05|02:01:21.553] 0x4a10307e221781570e4b7e409eb315f11e8d0385 appended 21 apps at 011156383-011159332
.......
INFO[16-05|02:01:21.813] 0x4a10307e221781570e4b7e409eb315f11e8d0385 appended 1 apps at 017205744-017208773
INFO[16-05|02:01:21.813] 0x4a10307e221781570e4b7e409eb315f11e8d0385 appended 2 apps at 017200001-017202860
"blockNumber","transactionIndex","date","timestamp","from","to","ether","ethGasPrice","gasUsed","hash","isError","encoding","compressedTx"

```

Pls help, thanks.

**Comment by tjayrush** [comment]
That's truly strange... When I do

```
chifra list 0x4a10307e221781570e4b7e409eb315f11e8d0385
```

I get a long list of appearances (address, block_number, transaction_id).

When I do

```
chifra list 0x4a10307e221781570e4b7e409eb315f11e8d0385 --count
```

I get 455 transactions.

When I do 

```
chifra export 0x4a10307e221781570e4b7e409eb315f11e8d0385 --fmt csv
```

I get a long stream of data exactly as I would expect.

When you run

```
chifra blocks 12
```

What do you see?

Also -- just because I'm grasping -- what operating system are you one? Are you directly logged in to the machine's command line?

**Comment by tjayrush** [comment]
Also, can you do 

```
find /node1/chifra/index/unchained/mainnet/ -exec ls -l {} ';'
```

and send me the results (through DM if you don't want to list them here).

**Comment by 32ethers** [comment]
After I build off chain index myself, everything goes normal. 
I do met some download error while running ```chifra init --all```, caused by query limit. 
But I'm sure all files are downloaded, I ran ```chifra init --all``` until every thing is downloaded. 
I think some files are broken
