### ISSUE TITLE
chifra export - phony transfers

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#2934]
Some smart contract report an event that Transfers tokens, but the balance of the account does not change. This is a "phishing" attempt and used to confuse our accounting.

We wrote some code that fixes the problem, but it does so in a weird way. What it should do in this case is record the fact that this was a phonyTranfer by storing the value in a new field in the reconciliation called `phoneTransfer` (or similar). And this new field should not be included in the reconciliation calculation.

What it does do instead is allow the positive income to appear (likely in `internalIn`) and then add a fake `internalOut` to offset the phony income. This is at best confusing and at worst completely wrong as there was actually no transfer of value (because the balances didn't change).

An example is the test case that runs this command: `transactions?transactions=0xf9a11aed09a4be208539a261d8c79567ba9918b4c4e577400ac39b64350b45fd&fmt=json&accountFor=0xf503017d7baf7fbc0fff7492b751025c6a78179b` called `getTrans_failed_recon_2.txt`.

**Comment by dszlachta** [comment]
What about adding `malicious` field that would be a bit field? `phonyTransfer` could be a bit flag and we could add more in the future. We could also mark the transaction in the UI if `malicious` is set to any value.

**Comment by tjayrush** [comment]
Actually, on second thought, I rather like the way this is handled. We mark this 'false transfer' with a `correctingReason` of `null-transfer`. Closing.
