### ISSUE TITLE
Bring docs and sdk into core repo

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#2939]
Automate publishing docs to website

**Comment by dszlachta** [comment]
We could also automate the whole build process (for all repos) by using continuos integration. Example CI services are:
- [Jenkins](https://www.jenkins.io/)  open source, but we'd have to host it on our own. 
- [Buddy](https://buddy.works/) or [Buildkite](https://buildkite.com) - both paid, with a little nicer UI and no need to host them.

In any of these, we could define pipelines to build and deploy docs, build and publish SDK, Docker image and update Explorer. We then can configure those pipelines to run in a cascade, after a new tag to master is pushed.

**Comment by dszlachta** [comment]
Another way to make release process easier is to automate testing. 
- when SDK is updated, we could use mock server generated by https://stoplight.io/open-source/prism and run test to check Explorer works correctly
- For Docker, maybe we could use Ganache or Foundry's `anvil` locally running dev chains to test if chifra is running OK

**Comment by dszlachta** [comment]
Regarding Jenkins, it could run the tests using the Dockerfile we have right now (https://www.jenkins.io/doc/book/pipeline/docker/). It could also manage artefacts (`test/working`) for us. 

But we can also leave the tests as they are right now (i.e. executed by our custom scripts) and only delegate releases to Jenkins. It would be semi-automatic as someone would have to check if the tests succeeded first, then push a new tag, which would trigger Jenkins

**Comment by tjayrush** [comment]
This is done.
