### ISSUE TITLE
chifra names with no parameters should list all names

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#2948]
The C++ version, when run with no parameters

```
chifra names
```

used to display all names. I would use it with `chifra names --expand` to write-back the data after adding a new name to the database.

```
chifra names --expand >../src/other/install/names/names.tab
```

When I run `chifra names` now, I get:

```
EROR[30-05|05:52:31.949] gRPC connection error: gRPC server not running
WARN[30-05|05:52:31.949] No results for [chifra names]
```

There are two problems here:

1) It should report every name (sorted by address) including all details so it can be used to write-back to the database

2) It should not report the gPRC error. It's very confusing...

**Comment by dszlachta** [comment]
I can't reproduce 1. The output that you've pasted suggests that you were looking for "chifra names" name. Maybe something got into your prompt?

**Comment by tjayrush** [comment]
Sleep walking...
