### ISSUE TITLE
chifra cmd - we need test cases to protect against breaking changes in the RPC data

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#2959]
I think all the Raw data mimics the RPC data directly (with a few exceptions). 

It would be nice to have testing that, using GoLang reflection, queries each RPC end point we use and ensures (not that the data returned is exact) but that the fields included in the data is as expected.

My guess is that other node software (Nethermind, etc.) produces slightly different data, especially for traces.

**Comment by dszlachta** [comment]
If we build a collection of the correct raw data (save them as files), then we could use Go's `reflect.DeepEqual` to ensure the object we get from the other client are same. We could even compare raw bytes (this is how Go stores objects marshalled to JSON).

I imagine that some minor details could be different, so we could write logic to normalize them and include it in our tests. Step by step to become node agnostic 👍
