### ISSUE TITLE
reth is not being detected as an archive node

### ISSUE THREAD

**Issue by banteg** [TrueBlocks/trueblocks-core#3009]
the code that does the detection is here https://github.com/TrueBlocks/trueblocks-core/blob/master/src/apps/chifra/pkg/node/is_archive.go

i guess it has something to do with it not serving or serving genesis allocations differently

**Comment by rkrasiuk** [comment]
indeed we fixed that last week https://github.com/paradigmxyz/reth/pull/3346

**Comment by tjayrush** [comment]
It's so cool that TrueBlocks see this. Have any of you'all run `make test-all` against RETH?
