### ISSUE TITLE
Installation Issue: type declarations inside generic functions are not currently supported

### ISSUE THREAD

**Issue by CristianNe** [TrueBlocks/trueblocks-core#3011]
Hello,

I was trying to install TrueBlocks and ran into the following error:
This type declaration `src/apps/chifra/pkg/utils/iteration.go:29:2` causes an error when executing `make` during installation. 
<img width="376" alt="image" src="https://github.com/TrueBlocks/trueblocks-core/assets/28632299/33c7714e-dcb9-47a3-8836-e12c56ff4997">

As of go 1.18 type declarations inside generic functions are no longer supported it seems.

**Comment by CristianNe** [comment]
### What version of go are you using?
```
$ go version
go version go1.19.2 darwin/amd64
```

### What operating system and processor architecture are you using (go env)?
<details><summary> go env output </summary>
<p>
GO111MODULE="" <br>
GOARCH="amd64" <br>
GOBIN="/Users/cristian/bin" <br>
GOCACHE="/Users/cristian/Library/Caches/go-build" <br>
GOENV="/Users/cristian/Library/Application Support/go/env"<br>
GOEXE=""<br>
GOEXPERIMENT=""<br>
GOFLAGS=""<br>
GOHOSTARCH="amd64"<br>
GOHOSTOS="darwin"<br>
GOINSECURE=""<br>
GOMODCACHE="/Users/cristian/go/pkg/mod"<br>
GONOPROXY=""<br>
GONOSUMDB=""<br>
GOOS="darwin"<br>
GOPATH="/Users/cristian/go"<br>
GOPRIVATE=""<br>
GOPROXY="https://proxy.golang.org,direct"<br>
GOROOT="/usr/local/go"<br>
GOSUMDB="sum.golang.org"<br>
GOTMPDIR=""<br>
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"<br>
GOVCS=""<br>
GOVERSION="go1.19.2"<br>
GCCGO="gccgo"<br>
GOAMD64="v1"<br>
AR="ar"<br>
CC="clang"<br>
CXX="clang++"<br>
CGO_ENABLED="1"<br>
GOMOD="/dev/null"<br>
GOWORK=""<br>
CGO_CFLAGS="-g -O2"<br>
CGO_CPPFLAGS=""<br>
CGO_CXXFLAGS="-g -O2"<br>
CGO_FFLAGS="-g -O2"<br>
CGO_LDFLAGS="-g -O2"<br>
PKG_CONFIG="pkg-config"<br>
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/_8/_ks2j0v51zz9fgp_v3c4h0qc0000gn/T/go-build1589065125=/tmp/go-build -gno-record-gcc-switches -fno-common"
</p>
</details>

**Comment by tjayrush** [comment]
You have to upgrade to GoLang version 1.20.

**Comment by CristianNe** [comment]
Yes this solved it, thanks!

**Comment by tjayrush** [comment]
Hey @CristianNe Thanks for reporting the issue. Are you in our discord? Say Hi. If you're so inclined, tell us what you're working on. Perhaps there's some tips or tricks we can give you to make your work easier. Cheers.

**Comment by CristianNe** [comment]
Hi Thomas,

sure good idea!
Cheers.

From: Thomas Jay Rush ***@***.***>
Date: Tuesday, 4. July 2023 at 23:34
To: TrueBlocks/trueblocks-core ***@***.***>
Cc: Cristian Neufuss ***@***.***>, Mention ***@***.***>
Subject: Re: [TrueBlocks/trueblocks-core] Installation Issue: type declarations inside generic functions are not currently supported (Issue #3011)

Hey @CristianNe<https://github.com/CristianNe> Thanks for reporting the issue. Are you in our discord? Say Hi. If you're so inclined, tell us what you're working on. Perhaps there's some tips or tricks we can give you to make your work easier. Cheers.
