### ISSUE TITLE
chifra transactions -`transactions/handle_show` loops twice through the same set of items

### ISSUE THREAD

**Issue by dszlachta** [TrueBlocks/trueblocks-core#3063]
[Here](https://github.com/TrueBlocks/trueblocks-core/blob/develop/src/apps/chifra/internal/transactions/handle_show.go#L45) we modify map item, but [later](https://github.com/TrueBlocks/trueblocks-core/blob/develop/src/apps/chifra/internal/transactions/handle_show.go#L67) we loop again only to add the item to a slice. 

I think we could add item to the slice in `iterFunc`, to avoid the second loop. But let's check the performance first

**Comment by tjayrush** [comment]
This is no longer correct. Closing.
