### ISSUE TITLE
Cache issues

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#3082]
1) There is no real testing of the cache. We can run them in two place -- prior to all testing to decache everyting and then use cache status to see if it works, and after all tests to see if it works.
2) ~Currently the help files say `--cache` is available on many tools, but it's not -- it fails validation.~
3) Some internal calls (such as GetTransactionCountByBlockNumber (or similar) force a non-cache query.

**Comment by tjayrush** [comment]
Many cache related called start with `cacheNew.` and take an `rpcOptions` parameter. Inside these functions they use `rpcOptions` all over the place. This is an indication that these functions should be methods.

**Comment by dszlachta** [comment]
It seems to me that we would use similar wrapper abstraction in `rpcClient` package as Go's `http` (as an example): https://cs.opensource.google/go/go/+/refs/tags/go1.20.6:src/net/http/client.go;l=58

**Comment by tjayrush** [comment]
There are methods on a type called `Client`. That's what I'm talking about. Even our package is called `rpcClient`.
