### ISSUE TITLE
"No new blocks at block"

### ISSUE THREAD

**Issue by germashevanton** [TrueBlocks/trueblocks-core#3145]
hi, 

after TrueBlocks synced (very close to the head) seems that new transactions are not indexed anymore, as when I got such message: "No new blocks at block" i was not able to find any transactions from this block, however, they exist for sure

some logs:

trueblocks-scrape-mainnet | INFO[08-08|14:02:08.617] Block=17869641 have 197883 appearances of 2000000 (9.9%). Need 1802117 more. Added 197883 records (98.94 apps/blk).
trueblocks-scrape-mainnet | INFO[08-08|14:02:08.880] Sleeping for 10 seconds - 3013 away from head.
trueblocks-scrape-mainnet | INFO[08-08|14:02:49.606] Block=17870661 have 844092 appearances of 2000000 (42.2%). Need 1155908 more. Added 646209 records (633.54 apps/blk).
trueblocks-scrape-mainnet | INFO[08-08|14:02:49.859] Sleeping for 10 seconds - 1021 away from head.
trueblocks-scrape-mainnet | INFO[08-08|14:03:00.331] No new blocks at block 17870668 (7 away from head)                                        
trueblocks-scrape-mainnet | INFO[08-08|14:03:00.581] Sleeping for 10 seconds - 7 away from head.
trueblocks-scrape-mainnet | INFO[08-08|14:03:10.260] No new blocks at block 17870668 (1 away from head)

**Comment by tjayrush** [comment]
I'm going to close this because we fixed it a branch. We're going to do our best to get this in to the next release which should be available some time next week.
