### ISSUE TITLE
Error while reading stderr: bufio.Scanner: token too long

### ISSUE THREAD

**Issue by germashevanton** [TrueBlocks/trueblocks-core#3146]
when executing this API call got this error 'Error while reading stderr: bufio.Scanner: token too long' and have not received any response 

/export?addrs=0xbdfa4f4492dd7b7cf211209c4791af8d52bf5c50&articulate=true&relevant=true&firstBlock=17857353&lastBlock=17869634

**Comment by tjayrush** [comment]
A couple of things:

1. When I try the above URL, I get an error message.

```
{
  "errors": [
    "The --relevant option is only available with the --logs option."
  ]
}
```

2. You're using `firstBlock` and `lastBlock` to paginate. That's fine, but you can also try `firstRecord` and `maxRecords`. I'd be interested to learn the results.

3. Querying the node is always going to be slower than hitting a "regular" API, so you have to expect a bit of slower performance (and therefor, perhaps, lower the block or record range). But, you should also be using the `--cache` option (if you have the disc space). It's WAY faster.

4. What release version are you running?

**Comment by germashevanton** [comment]
my version is v0.70.0-beta, 

'firstRecord' and 'maxRecords' I do not need as I have complex logic combining 6 chains and doing pagination, 
before doing the /export request I have to call just 'appearances' so I am sure how many records I need in a certain chain
I am not using firstRecord option as it is not working to get 'count' in chains other than mainnet and I need to know 'count' as transactions always returned from small to higher blocks, so I choose another approach using firstBlock and lastBlock.

**Comment by germashevanton** [comment]
What did you mean by "regular" API? Is it '/export' not the API of TrueBlocks?

**Comment by germashevanton** [comment]
i have the same problem with this request: '/export?addrs=0xef764bac8a438e7e498c2e5fccf0f174c3e3f8db&articulate=true&relevant=true&firstBlock=17857339&lastBlock=17871656' 

Very strange, have not faced it before. Recourses on the server are fine, I have 256GB Ram and more than 200GB of free space

**Comment by germashevanton** [comment]
Basically, i noticed that I can not execute any /export request with latest blocks due to this problem

**Comment by germashevanton** [comment]
Regarding this error:

{
  "errors": [
    "The --relevant option is only available with the --logs option."
  ]
}

I do not observe this problem in my request (version is v0.70.0-beta), 
you can try to do my request without the relevant option and the error will be still the same: " Error while reading stderr: bufio.Scanner: token too long". An error appeared in the 'serve' logs, and I have a timeout for the request

**Comment by germashevanton** [comment]
@tjayrush are you able to reproduce this error with this request /export?addrs=0xbdfa4f4492dd7b7cf211209c4791af8d52bf5c50&articulate=true&firstBlock=17857353&lastBlock=17869634?

**Comment by germashevanton** [comment]
@tjayrush, the problem is in this tx 0x0364c67567189d0c35431ee22125369d570aa996c3b9e65a623e2f6386f110aa, 
it has 3000 logs, so I think that the response from the node is too big and the input stream is not processed, 

here is a query to trueblocks containing only one tx that failed. Interesting that error is visible only in 'serve' logs however, the request failed only after a timeout. So there is no such error in the response. it just stuck.

'export?articulate=true&addrs=0xbdfa4f4492dd7b7cf211209c4791af8d52bf5c50&firstBlock=17865561&lastBlock=17865563'

**Comment by tjayrush** [comment]
Can you try `chifra logs 0x0364c67567189d0c35431ee22125369d570aa996c3b9e65a623e2f6386f110aa` and tell me what you find?

Also, can you run this command against both your current version and the latest `develop` branch?

```
chifra export --articulate 0xbdfa4f4492dd7b7cf211209c4791af8d52bf5c50 --first_block 17865561 --last_block 17865563 --fmt json | jq
```

Also, please send the results of

```
chifra status | grep -v Path
```

**Comment by germashevanton** [comment]
thanks for your response

- chifra logs 0x0364c67567189d0c35431ee22125369d570aa996c3b9e65a623e2f6386f110aa
[chifra logs.docx](https://github.com/TrueBlocks/trueblocks-core/files/12362808/chifra.logs.docx)

- chifra export
[chifra export.docx](https://github.com/TrueBlocks/trueblocks-core/files/12362813/chifra.export.docx)
[chifra export dev.docx](https://github.com/TrueBlocks/trueblocks-core/files/12362815/chifra.export.dev.docx)

- chifra status | grep -v Path
16-08|18:35:24.166 Client:            erigon/2.42.0/linux-amd64/go1.20.2 (archive, tracing)
16-08|18:35:24.166 TrueBlocks:        GHC-TrueBlocks//0.70.0-beta (eskey, no pinkey)
16-08|18:35:24.166 RPC Provider:      http://173.249.29.238:8545 - mainnet (1/1)
16-08|18:35:24.166 Progress:          17929209, 17928717, 17929207, 17929207 ts: 17929208
and with dev ver
16-08|19:16:54.403 Client:            erigon/2.42.0/linux-amd64/go1.20.2 (archive, tracing)
16-08|19:16:54.403 TrueBlocks:        GHC-TrueBlocks//0.82.0-beta (eskey, no pinkey)
16-08|19:16:54.403 RPC Provider:      http://173.249.29.238:8545 - mainnet (1/1)
16-08|19:16:54.403 Progress:          17929413, 17928717, 17929410, 17929410 ts: 17929411

**Comment by tjayrush** [comment]
Sorry. I can't open .docx files.

**Comment by germashevanton** [comment]
@tjayrush , uploaded in a .pdf format

[chifra.logs.pdf](https://github.com/TrueBlocks/trueblocks-core/files/12393367/chifra.logs.pdf)
[chifra export.pdf](https://github.com/TrueBlocks/trueblocks-core/files/12393368/chifra.export.pdf)
[chifra export dev.pdf](https://github.com/TrueBlocks/trueblocks-core/files/12393372/chifra.export.dev.pdf)

**Comment by tjayrush** [comment]
I truly do hate to be a pain in your ass. I can see you're new to GitHub. It would make my life easier if you would simple copy and paste the data you're providing directly into the issue. In that way, I can simple copy it down to my computer to analyze it. This is just a hint to you meant to be helpful. To the extent you can make the developer's life easier, the chances of getting a quick, timely, and accurate answer to your problem skyrockets. If I have to spend time doing something that's not necessary because the person asking is making things harder, the chances of getting an timely answer plummets.

Please take my comment as it's intended -- as a way to help both you and I. I realize it may come across as a bit harsh, but I don't mean it to.

Just copy and paste in the issue.

**Comment by tjayrush** [comment]
I just re-ran this on the latest `develop` build (version 1.0.0). I am not able to reproduce the issue. Is it still a problem? I'll close this, but if it continues to be a problem with version 1.0.0, please re-open.
