### ISSUE TITLE
Feature suggestion: Helm Chart for trueblocks-docker

### ISSUE THREAD

**Issue by tnet-ag** [TrueBlocks/trueblocks-core#3189]
Benefits:
     - easy to start setup
     - potential API performance improvement via k8 replicaset

Initial Ideas for a potential chart could be:

Components:

Init job/container who runs 
./scripts/chifra.sh init --all
to download the index

scraper pod which starts after init container is done 
runs then
./scripts/chifra.sh scrape

A Replicaset with auto scaler for serving the API

Pod that serves trueblocks-explorer

A shared read/write Persistent Volume to store the index

-----------------------------------
should be easy to install without much options to get a basic running version

```
helm repo add  trueblocks <TRUEBLOCKS GITHUB IO REPO URL>
helm install trueblocks/trueblocks
```

-----
for more options like trueblocks-explorer instance, init behaviour etc. the values in values.yaml can be overridden.

**Comment by tjayrush** [comment]
I truly appreciate your suggestion, I do, so please understand that I make the following comment with a concern that I make you feel that I don't value the idea. I certainly do not intend to do that. Please accept my words.

I don't understand at all what this means. I'm going to close this issue, but I invite you to re-open it, but, if you do, please add a very large amount of context assuming your reader does not know anything about what you're discussing.

What does this do?
Why do I want it?
How much work is involved?
What is the direct benefit to add it?
Does it keep the ethos of our project in mind (we have a VERY heavy decentralization-first ethos).

Again, I appreciate the suggestion, but I need a lot more context before I spend too much time on it.

**Comment by tnet-ag** [comment]
Okay here some context what Kubernetes and Helm are about:

Kubernetes, also known as K8s, is an open-source platform designed to automate deploying, scaling, and operating application containers. 
It groups containers that make up an application into logical units for easy management and discovery. 
Kubernetes provides a framework to run distributed systems resiliently, scaling and rolling out new features seamlessly. It was originally developed by Google and is now maintained by the Cloud Native Computing Foundation.

Helm is a package manager for Kubernetes. It's an open-source project that enables developers to create, version, share, and publish applications. It's like an apt/yum/homebrew for Kubernetes as it provides tools needed to manage the complexity of defining, installing, and upgrading applications deployed on Kubernetes clusters.

Helm provides a higher level of abstraction on top of Kubernetes and manages Kubernetes applications – Helm uses a packaging format called charts.


For a multi-container application, Helm becomes exceedingly useful due to the following reasons:

1. Organized Configuration: Multi-container applications normally involve intricate configurations with many Kubernetes objects, like Deployments, Services, ConfigMaps, Secrets, etc. Helm allows organizing these configurations into a single Helm chart, which greatly simplifies management and deployment.

2. Dependency Management: Helm's powerful dependency management system allows you to define dependencies between different services that span multiple containers. This is especially handy for multi-container applications where services often depend on each other.

3. Easy Updates and Rollbacks: Helm streamlines updating the version of applications or their configurations. If something goes wrong, Helm provides easy rollback functionality, which is essential for maintaining the uptime of multi-container applications.

4. Reusability: Helm charts are reusable, so common patterns for multi-container applications can be packaged as a chart and reused across multiple setups. 

5. Consistency: Helm helps enforce consistency. When deploying complex multi-container applications, it’s crucial that deployments are consistent to avoid "it works on my machine" scenarios. Helm charts provide a template for consistency.

6. Release Management: Helm keeps track of all versions of your application that have been installed and allows you to limit the history depth. This is particularly useful if your multi-container application needs to go through multiple version upgrades.

In essence, Helm makes working with multi-container applications on Kubernetes easier, more manageable and more efficient, especially in large environments.


To answer your questions:

1. What does this do?

Kubernetes is an open-source platform designed to automate deploying, scaling, and operating a container-centric infrastructure. It allows for seamless scaling of your applications according to need. It also helps to keep your application running without downtime and makes use of resources more efficiently.

Helm, on the other hand, is a package manager for Kubernetes. It simplifies deployments and provides easy versioning and release management. Helm takes care of managing all the Kubernetes manifest files, handling application dependencies, and provides a way to share applications.

2. Why do I want it?

If you are running containerized applications, especially in a production environment, Kubernetes and Helm can provide immense value by automating many tasks. 

- With Kubernetes, you don't have to manually intervene to scale your application, it's done automatically.
- Helm simplifies deployment, making application management a breeze. It enables quick and reliable deployment of services.
- Both ensure high availability and efficient use of your resources.
- They are designed with DevOps practices in mind, promoting agility and efficiency in software development and deployment.

3. How much work is involved?

Setting up Kubernetes and Helm does require an initial investment in time and effort to set up the environment, learn the basic components and terminologies, and to configure everything correctly. Depending on the size of your project, the complexity may vary. 

However, this investment pays off over time in increased efficiency, automation, scalability, and high availability. The Kubernetes and Helm communities also offer extensive support and resources to assist users.

4. What is the direct benefit to add it?

- Automation: Kubernetes will automate many operational tasks – it will keep your services running, distribute loads, scale your applications, among many other things.
- Efficiency: Helm will make your deployments easy and efficient. It simplifies managing manifest files, helps share applications, manages dependencies, and handles versioning.
- Scalability: Kubernetes will help you not to worry about infrastructure as it will scale your applications based on the demand.
- Reduced downtime: Kubernetes can quickly and effectively respond to failures ensuring high availability and resilience.
- Cost Saving: With effective and efficient use of resources, Kubernetes can result in cost savings over time.

Given how critical these benefits can be for delivering reliable software quickly, it's definitely worth in my opinion to exploring Kubernetes and Helm for trueblocks.

**Comment by tnet-ag** [comment]
btw: I can not reopen the issues

**Comment by tnet-ag** [comment]
Let me also explain each of the components i mentioned in detail:

1. **Init job/container**: An init container is a specialized container that runs before the application container starts and it's used to perform setup tasks such as downloading required files, creating configuration files on the fly, setting permissions, etc. In this case, the init container runs a script `./scripts/chifra.sh init --all` to download an index data that is required by the application.

2. **Scraper pod**:  This scraper pod starts once the init container is done, and then runs `./scripts/chifra.sh scrape`, presumably to fetch or update some additional data needed by the application/service.

3. **ReplicaSet with autoscaler**: In Kubernetes, a ReplicaSet is responsible for ensuring the desired number of replicas for a pod is always running in the cluster. This means if a pod crashes, the ReplicaSet will ensure a new one replaces it. The autoscaler attached to the ReplicaSet automatically scales the number of pods up or down based on the CPU usage or other selected metric. This is for serving the API that is part of this application/service.

4. **Shared read/write Persistent Volume to store the index**: A Persistent Volume (PV) is a piece of storage in the cluster that has been provisioned by an administrator or dynamically provisioned using Storage Classes. This PV is shared, meaning it can be used by multiple pods and it has read-write access. This PV is used to store the index that was downloaded by the init container, thus making it available to other pods that might need to read from or write to it.

**Comment by tnet-ag** [comment]
I can not reopen the issue btw.

**Comment by tjayrush** [comment]
Re-opened.

**Comment by tjayrush** [comment]
I truly appreciate you spending the time to make this issue, but I think I'm going to close it. We do not have the resources to work on this at this time. We may in the future. If you wish to pursue this, please let us know in the discord and we can discuss.
