### ISSUE TITLE
chifra status - Improve UX of `chifra status` Progress row

### ISSUE THREAD

**Issue by dszlachta** [TrueBlocks/trueblocks-core#3209]
Sometimes we need to explain to the users how to read `Progress` row of `chifra status`.
I think that we could make it more user friendly, so that users know what's happening.
For example, when the node is syncing, it should be visible in the output, because the behaviour of all other commands depends on synced node.

Some suggestions:
### Add labels to the items in "Progress"
```
07-09|11:02:03.171 Progress:          
07-09|11:02:03.171 Chain head at block 18083530 
07-09|11:02:03.171 Your index is 340,662 blocks BEHIND the chain
07-09|11:02:03.171 Index finalized for block: 17742868. Staging: 17742868. Currently indexing: 17742888 
07-09|11:02:03.171 Timestamps synced up to block: 17062507 (1,021,023 blocks BEHIND the chain)
```
> Note: it says `currently indexing` instead of `unripe` because in order to understand the meaning of `unripe` one needs to know our conventions. 

In the message above, the information about being behind the chain can, obviously, change depending on the current state:
- _Your index is X blocks BEHIND the chain_ when behind the chain large number of blocks
- _Your index is catching up (X blocks left)_ when behind, but the number of blocks is small and we think it wouldn't cause that big issue
- _Your index is up-to-date with the chain_ when the index is caught up

### Warn when scraper is not running and index is lagging behind
We can detect if the scraper is running and if it's not, add following line after the message above:
```
WARN: Index is behind the chain head, but scraper is not running. 
WARN: This means chifra is not aware of latest transactions and can return incomplete data. 
WARN: Run `chifra daemon --scrape index` to solve the issue.
```

### Detect node syncing state
We can use `eth_syncing` (https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_syncing) to ask the node if it's in syncing state. If yes, we can display a warning:
```
WARN: Your node seems to be syncing. During this state it can refuse queries from chifra 
WARN: or return incomplete data. If you observe such issues, please wait until your node 
WARN: is fully synced and your index catches up to the chain head.
```

### New command?
I know it'd make `chifra status` more verbose, so we could consider implementing these changes as part of a new command, e.g. `chifra diagnose`. Or, we can make the verbose output default and bring back `--terse`.

### Example outputs
**Node synced, index up-to-date**
```
07-09|11:02:03.171 Progress:          
07-09|11:02:03.171 Chain head at block 18083530 
07-09|11:02:03.171 Your index is up-to-date with the chain
07-09|11:02:03.171 Index finalized for block: 18083530. Staging: 18083531. Currently indexing: 18083532 
07-09|11:02:03.171 Timestamps synced up to block: 18083530
```

**Node synced, successfull chifra init but scraper not running**
```
07-09|11:02:03.171 Progress:          
07-09|11:02:03.171 Chain head at block 18083530 
07-09|11:02:03.171 Your index is 340,662 blocks BEHIND the chain
07-09|11:02:03.171 Index finalized for block: 17742868. Staging: 17742868. Currently indexing: 17742888 
07-09|11:02:03.171 Timestamps synced up to block: 17062507 (1,021,023 blocks BEHIND the chain)

WARN: Index is behind the chain head, but scraper is not running. 
WARN: This means chifra is not aware of latest transactions and can return incomplete data. 
WARN: Run `chifra daemon --scrape index` to solve the issue.
```

**Node is syncing**
```
07-09|11:02:03.171 Progress:          
07-09|11:02:03.171 Chain head at block 0 
07-09|11:02:03.171 Index finalized for block: 0. Staging: 0. Currently indexing: 0 
07-09|11:02:03.171 Timestamps synced up to block: 0

WARN: Your node seems to be syncing. During this state it can refuse queries from chifra 
WARN: or return incomplete data. If you observe such issues, please wait until your node 
WARN: is fully synced and your index catches up to the chain head.
```

**Comment by tjayrush** [comment]
I implemented part of this under `--diagnose` option to `chifra status`, but not the `WARN` parts. I added a TODO list item copying in the suggested text, so we won't lose it, but closing this for now.
