### ISSUE TITLE
ABI docs are vague and unclear

### ISSUE THREAD

**Issue by bh2smith** [TrueBlocks/trueblocks-core#3223]
When running the `chifra daemon` and accessing the route `abis?addrs=0xA2177F14AAD9B44C2FE04EE6731629B8D4E7270C`

the [response](https://jsonblob.com/1153576037266612224) is a very compact (incomplete) representation of the actual [abi](https://jsonblob.com/1153576508236619776).

It turns out that adding the `&verbose` flag to the request, returns the expected result!

However this is not at all apparent from the [API docs](https://trueblocks.io/api/#operation/accounts-abis)

**Comment by tjayrush** [comment]
The docs are auto-generated (by us), but the files that input into the docs for `chifra abis` are here: https://github.com/TrueBlocks/trueblocks-core/blob/master/docs/templates/readme-intros/accounts-abis.md and here: https://github.com/TrueBlocks/trueblocks-core/blob/master/docs/templates/readme-intros/accounts-abis.notes.md.

We invite PRs.

**Comment by tjayrush** [comment]
Note that the `--sol` option in the docs is incorrect. It no longer exists.

**Comment by tjayrush** [comment]
Done
