### ISSUE TITLE
chifra abis - Separate ABIs Response instead of Union

### ISSUE THREAD

**Issue by bh2smith** [TrueBlocks/trueblocks-core#3224]
Its counter intuitive that the response when requesting multiple ABIs it the union. One would generally expect some sort of

`Map<Address, ABI>` so they can match the abis to the addresses in question.

abis?addrs=0xA2177F14AAD9B44C2FE04EE6731629B8D4E7270C&addrs=0xAC5B46D8D5674389B14D8E758024C603D43E85D4&verbose"

**Comment by tjayrush** [comment]
Thanks for this issue. May I invite you to create a PR with suggested changes? The changes would start in this file: https://github.com/TrueBlocks/trueblocks-core/blob/master/src/apps/chifra/internal/abis/handle_addresses.go. We'd also probably need a new Modeler type.

**Comment by tjayrush** [comment]
Fixed with this PR https://github.com/TrueBlocks/trueblocks-core/pull/3448, but only if

1. You're using more than one address, and
2. You're exporting to `json` format.

We did this to preserve back-ward compatibility for most use cases.

**Comment by tjayrush** [comment]
Note that as of version 3.0 all commands (no matter how many addresses or which format, now separate the results grouped by address. This is a backward incompatible change (and one of the reasons for the major version change).
