### ISSUE TITLE
chifra monitors -- does it work?

### ISSUE THREAD

**Issue by mbwmbw1337** [TrueBlocks/trueblocks-core#3233]
daemon monitor fails saying use --watch yet watch does not exist at all returning "unknown flag: --watch"

```
erigon@dal-edge-3:~$ /home/erigon/trueblocks-core/bin/chifra daemon --port ":10432" --api "on" --grpc --verbose --monitor
Error: The --monitor option is currenlty not available. Use chifra monitors --watch instead.
Usage:
  chifra daemon [flags]

Aliases:
  daemon, serve

Flags:
  -p, --port string     specify the server's port (default ":8080")
  -a, --api string      instruct the node to start the API server
                        One of [ off | on ] (default "on")
  -s, --scrape string   start the scraper, initialize it with either just blooms or entire index, generate for new blocks
                        One of [ off | blooms | index ]
  -m, --monitor         instruct the node to start the monitors tool
  -g, --grpc            run gRPC server to serve names
  -x, --fmt string      export format, one of [none|json*|txt|csv]
  -v, --verbose         enable verbose output
  -h, --help            display this help screen

Notes:
  - To start API open terminal window and run chifra daemon.
  - See the API documentation (https://trueblocks.io/api) for more information.

erigon@dal-edge-3:~$ /home/erigon/trueblocks-core/bin/chifra daemon --port ":10432" --api "on" --grpc --verbose --watch  
Error: 
  unknown flag: --watch

Usage:
  chifra daemon [flags]

Aliases:
  daemon, serve

Flags:
  -p, --port string     specify the server's port (default ":8080")
  -a, --api string      instruct the node to start the API server
                        One of [ off | on ] (default "on")
  -s, --scrape string   start the scraper, initialize it with either just blooms or entire index, generate for new blocks
                        One of [ off | blooms | index ]
  -m, --monitor         instruct the node to start the monitors tool
  -g, --grpc            run gRPC server to serve names
  -x, --fmt string      export format, one of [none|json*|txt|csv]
  -v, --verbose         enable verbose output
  -h, --help            display this help screen

Notes:
  - To start API open terminal window and run chifra daemon.
  - See the API documentation (https://trueblocks.io/api) for more information.
```

**Comment by tjayrush** [comment]
I think it means that you should run a different command called `chifra monitors --watch` (not that you should use `--monitors --watch` in the daemon command. We working out exactly how `monitoring` and running the `daemon` should work. We've been going back and forth between monitoring being part of the `daemon` and a stand alone tool. I guess we landed (incorrectly) somewhere half way between.

The next release has a re-working of `monitoring` (yet again). This time it will work fully as a stand-alone tool (not part of `daemon`).

To the extent to which you can help us understand your exact use case (DM me in discord if you'd rather not share publicly), that would be helpful.

**Comment by tjayrush** [comment]
Hello.

This should now be fixed in the `develop` branch.

Note that `chifra daemon monitors` is no longer allowed. Instead use `chifra monitors --watch`.

If you type that command, you'll get a help file describing how the new monitor code works. Basically, it now requires two additional parameters:

`--watch_list` which is a list of addresses to watch, and
`--commands` which is the name of a file that contains the commands to apply to each address.

Please try it out and let us know how it works.

Closign this issue. Please open a new issue with other problems (if any).
