### ISSUE TITLE
chifra state - fails against Geth

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#3348]
This command:

```
chifra state 0x1f9090aaE28b8a3dCeaDf281B0F12828e676c326
```

which uses this curl command under the covers:

```
curl -X POST -H "Content-Type: application/json" --data '{ "jsonrpc": "2.0", "method": "eth_getBalance", "params": [ "0x1f9090aae28b8a3dceadf281b0f12828e676c326", 18470077 ], "id": 1 }' rpcurl
```

Produces this error message from `Geth` (but not Erigon).

```
{"jsonrpc":"2.0","id":1,"error":{"code":-32602,"message":"invalid argument 1: json: cannot unmarshal number into Go value of type string"}}
```

**Comment by ghost** [comment]
I think this should solve the query

> curl -X POST -H "Content-Type: application/json" --data '{ "jsonrpc": "2.0", "method": "eth_getBalance", "params": [ "0x1f9090aae28b8a3dceadf281b0f12828e676c326", "0x119d4bd" ], "id": "1" }' rpcurl

Don't know why but sometimes geth fails with integer params or non string params
