### ISSUE TITLE
`chifra init` missing index publisher

### ISSUE THREAD

**Issue by dszlachta** [TrueBlocks/trueblocks-core#3400]
This happens on both `master` and `develop`.

When I ran `chifra init --all` I get:
```
Error: the --call value provided (manifestHashMap(0x0, "mainnet")) was not found: abi not found for manifestHashMap(0x0, "mainnet"): abi not found 
```

Same happens if I run `chifra init --all --publisher publisher.unchainedindex.eth`.
Only when I "resolve ENS name manually" (I look it up on Etherscan) the error message changes:
```
chifra init --all --publisher 0x02F2b09B33FdbD406ead954A31F98BD29a2A3492
EROR[17-11|10:15:49.559] Could not connect to RPC client not found # <-- it CAN connect
INFO[17-11|10:15:49.562] Chain: mainnet
INFO[17-11|10:15:49.562] Database: mainnet
INFO[17-11|10:15:49.562] Publisher: 0x02f2b09b33fdbd406ead954a31f98bd29a2a3492
INFO[17-11|10:15:49.562] Gateway: https://ipfs.unchainedindex.io/ipfs/
INFO[17-11|10:15:49.562] CID: <nil>
Error: fetch to pinning service (https://ipfs.unchainedindex.io/ipfs/%3Cnil%3E) failed: 400 Bad Request
```

Not sure why it says it cannot connect to the RPC. `chifra status` and `chifra block XYZ` work fine.
My config file is in "v2.0.0" format and doesn't have `unchained.PreferredPublisher` set

**Comment by tjayrush** [comment]
Please let me know if you think this is a corrupted Erigon node. If yes, Please close this.

I will open a new issue to make sure we report a better, more meaningful error message.

**Comment by dszlachta** [comment]
It is definitely a corrupted Erigon node. It works fine with another node.
