### ISSUE TITLE
Chifra Export Topic Filters not Applying

### ISSUE THREAD

**Issue by amuDev** [TrueBlocks/trueblocks-core#3427]
**Issue**: When filtering exported logs by topic, the output does not perform filtering based on the input topic(s). First observed on `v2.0.0-release` and re-validated on `v2.1.2-release` for sanity.

**Example**: Exporting logs generated by a given ERC20 contract (here we use ICHI `0x111111517e4929d3dcbdfa7cce55d30d4b6bc4d6`), applying the flag `-B` or the long form `--topic` with the input set as `0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef` (human readable: `Transfer(address,address,uint256)`). We also apply the following flags for these examples: `-x json -l -e 10`, explicitly set output to json format `-x json`, export logs only `-l`, shortform version of max_records `-e 10`.
Given these parameters, we would expect the output to be a json object containing an array of logs in the `data` object with 10 objects each representing a log.

As a baseline exporting 10 records with no filtering on this contract produces an object with 21 logs from 10 transactions. 6 of these 21 logs contain the topic that we wish to filter for.
`$ chifra export -x json -l -e 10 0x111111517e4929d3dcbdfa7cce55d30d4b6bc4d6 > erc20_log_export_raw_example.json`
[erc20_log_export_raw_example.json](https://github.com/TrueBlocks/trueblocks-core/files/13499417/erc20_log_export_raw_example.json)

We then add in our topic constraint, we expect this output to share 6 of the same logs from the previous command, and introduce 4 new logs.
`$ chifra export -x json -l -e 10 -B 0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef 0x111111517e4929d3dcbdfa7cce55d30d4b6bc4d6 > erc20_log_export_filtered_topic_example.json`
[erc20_log_export_filtered_topic_example.json](https://github.com/TrueBlocks/trueblocks-core/files/13499415/erc20_log_export_filtered_topic_example.json)
This is where the core problem appears, these 2 commands produce the same output.

For sanity, lets check that the other filterable constraints are working as expected, applying the `-m` or longform `--emitter` flag passing in the same address as the token to remove any logs that are produced by external calls.
`$ chifra export -x json -l -e 10 -m 0x111111517e4929d3dcbdfa7cce55d30d4b6bc4d6 0x111111517e4929d3dcbdfa7cce55d30d4b6bc4d6 > erc20_log_export_filtered_emitter_example.json`
[erc20_log_export_filtered_emitter_example.json](https://github.com/TrueBlocks/trueblocks-core/files/13499412/erc20_log_export_filtered_emitter_example.json)
We can now see that the output is different. It correctly filters 12 logs out from the original raw output, now we have an output of 9 logs, all of which are emitted under the expected address. So we confirmed that the filtering does work to an extent.  [Diffchecker link comparing to raw](https://www.diffchecker.com/QGVMNMA7/)

**Expected Output**:  The expected output for this is at most 10 records to be processed, any log which passes the topic filter is appended to the output. In this particular case, if we only filter by topic, we would expect 6 logs to be output, 4 of which originate from the ICHI contract and 2 of which originate from an unknown address. Combining these 2 filter types `-m -B` we would expect the output to be reduced from 6, to 4, only containing the logs that originated from the filtered emitter. These expected outputs are [erc20_log_export_filtered_topic_expected.json](https://github.com/TrueBlocks/trueblocks-core/files/13499416/erc20_log_export_filtered_topic_expected.json) and [erc20_log_export_filtered_topic_and_emitter_expected.json](https://github.com/TrueBlocks/trueblocks-core/files/13499414/erc20_log_export_filtered_topic_and_emitter_expected.json) respectively.

**Comment by tjayrush** [comment]
I'll just take this one at a time:

```
chifra export --fmt json --logs --max_records 10 0x111111517e4929d3dcbdfa7cce55d30d4b6bc4d6
```

I confirm this produces
- 21 logs
- from 10 unique transactions
- 6 of which have topic 0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef

**Comment by tjayrush** [comment]
> We then add in our topic constraint, we expect this output to share 6 of the same logs from the previous command, and introduce 4 new logs.

```
chifra export -x json -l -e 10 -B 
 0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef 0x111111517e4929d3dcbdfa7cce55d30d4b6bc4d6
``` 
> This is where the core problem appears, these 2 commands produce the same output.

I am going to try to solve this problem first and merge it with `develop`. Once that's done, I'll come back here and you can tell me if the rest of the problem still exists...

It's a bigger change that you might think (it applies to all routines with `--max_records`, so I'll let you know when the fix is merged.

**Comment by tjayrush** [comment]
Can you do me a favor? Please confirm my understanding.

This command shows the exact problem:

```
chifra export -l -e 10 -B 
 0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef 0x111111517e4929d3dcbdfa7cce55d30d4b6bc4d6 | wc -l
```

This command shows the exact problem. By exporting text records (one per line) and taking the line count, it should show `10`, but it shows `22` instead. So `--max_record` is incorrect.

That's the first problem I'm going to solve.

**Comment by amuDev** [comment]
While I do believe the `--max_record` flag is a bit confusing, I think it is working as intended in this scenario. If instead we check the number of unique transaction hashes in the output, it returns 10 transaction hashes.
```shell
$ chifra export -x json -l -e 10 \
  -B 0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef \
  0x111111517e4929d3dcbdfa7cce55d30d4b6bc4d6 \
  | jq -r '.data[].transactionHash' | sort | uniq | wc -l
10
```
I think the documentation of this flag could be made more clear, but that is not the original issue I was facing. This seems to lean closer to a core design consideration rather than a bug.
`-e, --max_records uint    the maximum number of records to process (default 250)`
Although during testing while writing this I did notice that, when not passing an explicit `-e` flag, the stated `default` value does not seem to be actively applied.

The bug in question pertains to the fact that the topic filter is not working, we can also confirm that by using the same method as above to count the number of unique topics (only checking the first index since that is what this filter is intended for)
```shell
$ chifra export -x json -l -e 10 \
  -B 0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef \
  0x111111517e4929d3dcbdfa7cce55d30d4b6bc4d6 \
  | jq -r '.data[].topics[0]' | sort | uniq | wc -l
7
```
returns `7` instead of the expected `1`.

**Comment by tjayrush** [comment]
Thanks for this. I understand. There's two issues here. I'm going to solve the first one first so as to make the second one easier.

The first one is `--max_records` which is not working as it should.

I think I'll open a new issue for that. 

Once that's merged, I'll then focus on this. (The code is too confusing otherwise.)

Thanks for your help.

**Comment by tjayrush** [comment]
I can see in the code that the filtering for topics, emitter, etc. for the `--logs` option is not working. That's confirmed.

**Comment by tjayrush** [comment]
I just merged a fix for the `--max_records` issue to `develop`. It will appear in master soon.

Now that that's done, perhaps you can make this super simple for me and give me a one-line command that shows the problem.

I'll solve the problem the next day if you also include the exact results you expect.

No need to explain anything. Just the command and the expected result.

**Comment by amuDev** [comment]
```bash
chifra export -x json -l -e 10 -B 0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef 0x111111517e4929d3dcbdfa7cce55d30d4b6bc4d6
```
[Expected output](https://github.com/TrueBlocks/trueblocks-core/files/13499416/erc20_log_export_filtered_topic_expected.json)

**Comment by tjayrush** [comment]
That captured it. Thanks so much for your help. I put this into our testing bucket. Which means it needs to get fixed before we push to `master`. I'll comment here when I push to `develop` and soon thereafter, we'll push to `master`.

Thanks so much for your help.

**Comment by tjayrush** [comment]
I pushed a fix to `develop`. I'm going to close this. If the issue persists or there's some other problem, please open a new issue. You may reference this one.
