### ISSUE TITLE
chifra init failed for local besu client

### ISSUE THREAD

**Issue by meijiesky** [TrueBlocks/trueblocks-core#3468]
I have a local private network with a besu client with rpc port 8545.

I followed https://trueblocks.io/docs/install/install-core/ to install chifra. I keep the rpcProvider = "http://localhost:8545" unchanged for chains.mainnet since my local besu node has this exact port even though it is not actually connected to the mainnet.

And I can use cmmmand like `chifra blocks 12` to fetch blocks in my besu node. It returns something like this.
```

❯ chifra blocks 12
WARN[02-01|12:06:43.339] the --call value provided (manifestHashMap(0x0, "mainnet-ts")) was not found: abi not found for manifestHashMap(0x0, "mainnet-ts"): abi not found
{
  "data": [
    {
      "baseFeePerGas": 0,
      "blockNumber": 12,
      "date": "2024-01-02 02:57:33 UTC",
      "difficulty": 100,
      "gasLimit": 9007199254740991,
      "gasUsed": 0,
      "hash": "0x9afb000a9d90a89cf7bc59a46df1866c8cb4ad9cf4686f700e99740a2ffa342d",
      "miner": "0xfe3b557e8fb62b89f4916b721be55ceb828dbd73",
      "parentHash": "0x71ab0aaf8eb70895e6213635cc61464cb20af161e039c8cc36b496fabfdc7f83",
      "timestamp": 1704164253,
      "transactions": [],
      "uncles": [],
      "withdrawals": []
    }
  ]
}
```

Note the warning at the beginning.

I can also run `chifra status`, and it returns
```
❯ chifra status
WARN[02-01|12:07:32.969] the --call value provided (manifestHashMap(0x0, "mainnet-ts")) was not found: abi not found for manifestHashMap(0x0, "mainnet-ts"): abi not found
02-01|12:07:35.045 Client:            besu/v23.10.3-dev-e49ed0e8/osx-x86_64/openjdk-java-17 (no archive, tracing)
02-01|12:07:35.045 TrueBlocks:        GHC-TrueBlocks//2.5.0-release (no eskey, no pinkey)
02-01|12:07:35.045 RPC Provider:      http://localhost:8545 - mainnet (231211/231211)
02-01|12:07:35.045 Root Config Path:  /Users/mjsky/Library/Application Support/TrueBlocks/
02-01|12:07:35.045 Chain Config Path: /Users/mjsky/Library/Application Support/TrueBlocks/config/mainnet/
02-01|12:07:35.045 Cache Path:        /Users/mjsky/Library/Application Support/TrueBlocks/cache/mainnet/
02-01|12:07:35.045 Index Path:        /Users/mjsky/Library/Application Support/TrueBlocks/unchained/mainnet/
02-01|12:07:35.045 Progress:          4226, 0, 0, 0 ts: 0
```

Then I run `chifra init`, it failed with the following log
```
❯ chifra init
WARN[02-01|12:08:21.471] the --call value provided (manifestHashMap(0x0, "mainnet-ts")) was not found: abi not found for manifestHashMap(0x0, "mainnet-ts"): abi not found
Error: the --call value provided (manifestHashMap(0x0, "mainnet")) was not found: abi not found for manifestHashMap(0x0, "mainnet"): abi not found
Usage:
  chifra init [flags]

Flags:
  -a, --all                in addition to Bloom filters, download full index chunks (recommended)
  -d, --dry_run            display the results of the download without actually downloading
  -F, --first_block uint   do not download any chunks earlier than this block
  -s, --sleep float        seconds to sleep between downloads
  -v, --verbose            enable verbose output
  -h, --help               display this help screen

Notes:
  - If run with no options, this tool will download or freshen only the Bloom filters.
  - The --first_block option will fall back to the start of the containing chunk.
  - You may re-run the tool as often as you wish. It will repair or freshen the index.
```

I use trueblocks mainly because I want to establish an explorer for this local besu node. Wondering whether trueblocks support this kind of situation.

**Comment by tjayrush** [comment]
This is an issue we've seen elsewhere (https://github.com/TrueBlocks/trueblocks-core/issues/3480). It happens when you're running against a non-mainnet RPC as your default RPC. A couple of questions:

1) Did you modify the `defaultChain` value in the config file (edit it with `chifra config edit`). You should change it to something.
2) Do you have a valid rpcProvider for mainnet (this is what the complaint is about -- we're trying to connect to a mainnet RPC for some data we store on a smart contract on mainnet). In order to work properly, TrueBlocks always needs a mainnet RPC as well as whatever RPC you use for the 'defaultChain' (We should check this better than simply reporting that useless error.)
3) Set up a corresponding section under `[chains]` for your "default" RPC.

Not sure if I explained this well, but please ask questions if not. If you try this and it works, please let us know.

**Comment by tjayrush** [comment]
I'm going to close this as a duplicate. If you wish, you can comment on the referenced issue (#3480) or re-open this.
