### ISSUE TITLE
chifra scrape - running against remote RPC node

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#3485]
**from gphil in our discord**

"chifra scrape -n 10 -s 1" when pointed to my QuickNode archive node RPC (I am on the "build" plan) and just let it run for a few days starting on 1/26 and I had the complete index up to the latest block by 1/30. There were a couple times when my network timed out and the command stopped running, so I had to manually restart it. I could fix this by daemonizing "chifra scrape" (I might do that anyway so it just stays up to date in the background) but might be nice to allow for waiting out network interruptions in chifra itself so you can fire and forget.

**Comment by gphil** [comment]
I was able to reproduce this pretty easily. I ran the `chifra scrape -n 10 -s 1` command above and verified the scraper was humming along nicely. I then cut my network connection to see what happened next and I got the following error messages before the process exited:

```
EROR[01-02|14:19:00.228] EROR[01-02|14:19:00.228] EROR[01-02|14:19:00.228] Could not connect to RPC client Post "https://<redacted>.quiknode.pro/<redacted>": read tcp 192.168.1.19:55112->132.145.191.48:443: read: operation timed out
Could not connect to RPC client Post "https://<redacted>.quiknode.pro/<redacted>": read tcp 192.168.1.19:55112->132.145.191.48:443: read: operation timed out
Could not connect to RPC client Post "https://<redacted>.quiknode.pro/<redacted>": read tcp 192.168.1.19:55112->132.145.191.48:443: read: operation timed out
EROR[01-02|14:19:00.239] error at block 19135596: read tcp 192.168.1.19:55112->132.145.191.48:443: read: operation timed out
EROR[01-02|14:19:00.239] error at block 19135593: read tcp 192.168.1.19:55112->132.145.191.48:443: read: operation timed out
EROR[01-02|14:19:00.239] error at block 19135595: read tcp 192.168.1.19:55112->132.145.191.48:443: read: operation timed out
EROR[01-02|14:19:00.239] error at block 19135591: Post "https://<redacted>.quiknode.pro/<redacted>": read tcp 192.168.1.19:55112->132.145.191.48:443: read: operation timed out
EROR[01-02|14:19:00.239] error at block 19135594: read tcp 192.168.1.19:55112->132.145.191.48:443: read: operation timed out
EROR[01-02|14:19:00.239] error at block 19135590: read tcp 192.168.1.19:55112->132.145.191.48:443: read: operation timed out
EROR[01-02|14:19:00.239] error at block 19135592: read tcp 192.168.1.19:55112->132.145.191.48:443: read: operation timed out
EROR[01-02|14:19:00.239] error at block 19135587: Post "https://<redacted>.quiknode.pro/<redacted>": dial tcp: lookup chaotic-multi-diamond.quiknode.pro: no such host
EROR[01-02|14:19:00.239] error at block 19135588: Post "https://<redacted>.quiknode.pro/<redacted>": dial tcp: lookup chaotic-multi-diamond.quiknode.pro: no such host
EROR[01-02|14:19:00.239] error at block 19135589: Post "https://<redacted>.quiknode.pro/<redacted>": dial tcp: lookup chaotic-multi-diamond.quiknode.pro: no such host
EROR[01-02|14:19:00.239] encountered errors while scraping
```

**Comment by gphil** [comment]
I've never programmed in Go before but it looks like the 2nd return value here: 

https://github.com/TrueBlocks/trueblocks-core/blob/4e14b390c5da98c9d4937b36f970d9203565b230/src/apps/chifra/internal/scrape/scrape_batch.go#L26

Is bubbling up to the `!ok` check here and and invoking `break` instead of `PAUSE` which might be the issue.

https://github.com/TrueBlocks/trueblocks-core/blob/4e14b390c5da98c9d4937b36f970d9203565b230/src/apps/chifra/internal/scrape/handle_scrape.go#L143-L146

If you let me know what you want the criteria for `break` vs. `PAUSE` to be I can take a crack at a PR if you want.

**Comment by tjayrush** [comment]
@gphil We pushed a modification to the above line to return `ok==true` which will cause the loop to continue (simply reporting an error, not quitting on an error). I think you can test this against the `develop` branch. Let me know, and I'll close this.

**Comment by gphil** [comment]
Thanks! I pulled down the develop branch and things are looking good now. I threw "chifra scrape" some abuse from the network level and I couldn't get it to exit like it was before.

**Comment by tjayrush** [comment]
Thanks for taking the time. Closing.
