### ISSUE TITLE
Warn that API is not meant to be used on server

### ISSUE THREAD

**Issue by dszlachta** [TrueBlocks/trueblocks-core#3516]
We should clearly state (maybe in a form of a banner?) that some of the API endpoints are destructive, while open to any request incoming. This makes API not suitable for server usage, which is totally OK with us (local-first software) but might not be obvious for some users.

This is how GitHub is doing it (the red-ish box):
![Zrzut ekranu 2023-06-1 o 14 20 36](https://github.com/TrueBlocks/trueblocks-docs/assets/2346536/d3c3d673-3a2c-4fc6-83fd-10ca3e3bbb11)

**Comment by tjayrush** [comment]
Done. Will be merged in next release.
