### ISSUE TITLE
Progress: Could not load RPC provider: invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by cevatbostancioglu** [TrueBlocks/trueblocks-core#3527]
Hello,
i see following error on any chifra fetching command and ./testRunner app.
WARN[26-02|01:13:49.889] the --call value provided (manifestHashMap(0x0, "mainnet-ts")) was not found: abi not found for manifestHashMap(0x0, "mainnet-ts"): abi not found 
INFO[26-02|01:13:49.889] Server URL:         localhost:8080
INFO[26-02|01:13:49.889] RPC Provider:       https://etherscan.io
INFO[26-02|01:13:49.889] Root Config Path:   /home/xx/.local/share/trueblocks/
INFO[26-02|01:13:49.889] Chain Config Path:  /home/xx/.local/share/trueblocks/config/mainnet/
INFO[26-02|01:13:49.889] Cache Path:         /home/xx/.local/share/trueblocks/cache/mainnet/
INFO[26-02|01:13:49.889] Index Path:         /home/xx/.local/share/trueblocks/unchained/mainnet/
INFO[26-02|01:13:50.299] Progress: Could not load RPC provider: invalid character '<' looking for beginning of value
2024/02/26 01:13:50 

even with default config, i observe this error.

My config:
go version go1.22.0 linux/amd64
Ubuntu 22.04.2 LTS

Thanks,
Cevat

**Comment by tjayrush** [comment]
This text

```
Could not load RPC provider: invalid character '<' looking for beginning
```

Seems to indicate a problem.

Do not post your RPC endpoint here, but do this:

```
chifra config | grep rpcProvider
```

You should recognize one of these as your Ethereum mainnet rpcProvider.

(You can edit the config with `chifra config edit` and find your ETH mainnet rpc provider that way too.)

One you find that, do this:

```
curl -X POST -H "Content-Type: application/json" --data '{ "jsonrpc": "2.0", "method": "eth_getBlockByNumber", "params": [ "latest", true ], "id": 1 }' MAINNET_RPC
```

with MAINNET_RPC the value you found above.

I suspect this won't work, which means that's the problem. You need a valid mainnet ETH rpc endpoint.

Reminder: do not post your RPC endpoint to this issue.

**Comment by tjayrush** [comment]
I'm going to close this, but if the above doesn't fix your issue, please re-open.
