### ISSUE TITLE
sdk - should we return base.Blknum?

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#3546]
Many of our types use `base.Blknum` which is annoying when I have to use it in the SDK. I write code like this for example:

```
meta, _ := sdk.GetMeta()
for i := 0 ; i < meta.Latest ; i++ {
    ...
}
```

which doesn't compile because of a type mismatch. Casting the `meta.Latest` to an int fixes it, but makes the code ugly.

**Comment by dszlachta** [comment]
We can add `Int()` method to `Blknum`, which is kinda idiomatic Go

**Comment by tjayrush** [comment]
I don't love that any more than I like the need for the cast. Both methods impose on the calling code something that may not be necessary. We have a fresh slate with the SDK to expose an interface that is super straight forward.
