### ISSUE TITLE
Chifra state --call extend to many calls per invocation 

### ISSUE THREAD

**Issue by yosrahelal** [TrueBlocks/trueblocks-core#3561]
Currently, chifra state --call perform only one call per invocation. 
Is it possibke to extend to many calls per invocation ?? Like adding an array of calls ?

**Comment by tjayrush** [comment]
Hey. Thanks for your issue. We're currently working on a release (3.0) which will include an SDK. I won't be able to add this feature before then, but I'm very interested in it. Once 3.0 is released, we'll take a closer look at this.

**Comment by tjayrush** [comment]
This is being merged into `develop` now. Will be in `master` shortly.

In order to use it, simply use the same syntax as before, but separate calls by a `colon`.

So, for example:

```
chifra state --call 'manifestHashMap(trueblocks.eth,"mainnet"):0x8da5cb5b' unchainedindex.eth --fmt json
```

Will returns results for both calls.
