### ISSUE TITLE
Renew domain name

### ISSUE THREAD

**Issue by Abraham21** [TrueBlocks/trueblocks-core#3583]
- https://trueblocks.io/
<img width="1214" alt="Screenshot 2024-04-17 at 1 47 28 PM" src="https://github.com/TrueBlocks/trueblocks-core/assets/16629942/bebcefbf-8af8-42ea-bfd3-f356c44bfeb3">

**Comment by Abraham21** [comment]
@tjayrush

**Comment by tjayrush** [comment]
Thanks. Done.
