### ISSUE TITLE
Handler code should not use Fatal

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#3587]
At this line https://github.com/TrueBlocks/trueblocks-core/blob/develop/src/apps/chifra/internal/slurp/handle_show.go#L19, it says this:

```
	provider, err := opts.Provider()
	if err != nil {
		logger.Fatal(err)
	}
```

Do we want to fail fatally? In API mode, this will crash the server. I think I tried to not use Fatal because no matter what, we don't want the server to die.

Why not just return the error?

**Comment by dszlachta** [comment]
Sorry for that, it's Key's bad influence on me
