### ISSUE TITLE
defaultChain works for initial setup only

### ISSUE THREAD

**Issue by dreaded369** [TrueBlocks/trueblocks-core#3592]
I set default chain to an alternative chain (pulsechain) in trueBlocks.toml initially and did some scraping.
I've now changed the value in trueBlocks.toml to "mainnet" and restarted.
Trueblocks still sees pulsechain as the default chain (status messages), and to scrape "mainnet" I need to use "--chain mainnet"

**Comment by dreaded369** [comment]
False alarm I think - I also had an environmental setting in my .env 
I'll check next restart.

**Comment by tjayrush** [comment]
Very good. I was going to say that that feature has worked for a long time. So, the environment variable overrode the config file. That makes sense. I'll close this. Please reopen it if you need to.
