### ISSUE TITLE
Insustry standard URL for our API

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#3639]
I feel like our API is odd. Shouldn't it be

```
http://localhost:8080/blocks/:id/
```

or maybe even

```
http://localhost:8080/v3/blocks/:id/
```

(with a version string?)

Then we can remove things like `http://localhost:8080/blocks?blocks=12` or `http://localhost:8080/chunks?modes=index`

Should be `http://localhost:8080/chunks/index` (I think.)

**Comment by dszlachta** [comment]
Agree, it'd make much more sense
