### ISSUE TITLE
migration build instructions

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#3660]
I'm going to push a weird change tonight that moves one of the `examples` to `dev_tools`.

Can you `git pull --recurse-submodules` and then `make clean`.

Do not remove `go.work` and do `cmake ../src` then `make`.

Does it build? I think probably not.

Then do `../scripts/make-go-work.sh`

Does that work? I think probably not.

Then, remove `../go.work` and re-run `../scripts/make-go-work.sh`. That should work.

Then `make -j 12`

Then, `run sdkFuzzer`. Does this work?

Summary:

```
git pull --recurse-submodules
make clean
cmake ../src
make # fails
../scripts/make-go-work.sh # fails
rm -f ../go.work
../scripts/make-go-work.sh # should work
make -j 12
sdkFuzzer
```

**Comment by dszlachta** [comment]
It went just as you described. It didn't work first, but after removing `go.work` it worked.

**Comment by tjayrush** [comment]
Did the fuzzer run?

**Comment by dszlachta** [comment]
Yes it did

Dawid Szlachta
