### ISSUE TITLE
Add GH action to generate code

### ISSUE THREAD

**Issue by dszlachta** [TrueBlocks/trueblocks-core#3664]
1. Install prettier on action's instance: https://stackoverflow.com/a/58002908
2. call `make && make generate .` and fail if there are changes

**Comment by tjayrush** [comment]
Just FYI: there's this line here, but I don't think it's quite right. It's commented. You remove it if you wish.

https://github.com/TrueBlocks/trueblocks-core/blob/develop/scripts/test-all.sh#L37
