### ISSUE TITLE
chifra status --healthcheck

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#3684]
This should be the absolute least cost (in speed and resource) call just to say "I'm still standing..."

**Comment by dreaded369** [comment]
one usecase - docker healthcheck:

> healthcheck:
>       test: ["CMD", "curl", "-f", "http://localhost:8080/when?blocks=0"]
>       interval: 1m30s
>       timeout: 10s
>       retries: 3
>       start_period: 40s
>       start_interval: 5s

**Comment by tjayrush** [comment]
This will be in the next release. I just pushed it into `develop`.
