### ISSUE TITLE
Getting Started with TrueBlocks

### ISSUE THREAD

**Issue by Pfed-prog** [TrueBlocks/trueblocks-core#3700]
https://trueblocks.io/docs/install/install-core/

`golang-go` package absolutely does not pass `cmake` and `make` stages from the installation guide even though it is 1.18.0

the logs asked me to install the latest go version

Very good tutorial on go installation https://www.digitalocean.com/community/tutorials/how-to-install-go-on-ubuntu-20-04

**Comment by Pfed-prog** [comment]
Found config
https://github.com/TrueBlocks/trueblocks-core/blob/3f8eaf44105d4272fa89ca7b1a1d67162ee6dd0d/src/other/install/trueBlocks.toml

`chifra config` command to query the config, but not sure how to edit

**Comment by Pfed-prog** [comment]
https://github.com/TrueBlocks/trueblocks-docs/issues/231 found config

**Comment by tjayrush** [comment]
Hi. Thanks so much for your issue.

Can you be a little bit more descriptive? Did the build fail? How did you fix it?

Also, if the build worked, you can type `chifra config edit` to edit the config file.

**Comment by tjayrush** [comment]
Any suggestions you can make will be helpful. THanks.

**Comment by Pfed-prog** [comment]
The build failed because i decided to take a shorter path and installed `golang-go` apt package. Latest go version probably would be a better solution. I am not sure. The build logs asked for effectively the latest version. 

`$CONFIG/trueBlocks.toml` somewhat disoriented me. I also got completely different outputs for `chifra config --paths`.

I did not notice for some reason that `chifra config` had further arguments. I have received outputs from `chifra config` and went to search solutions on Google and GitHub.

<img width="437" alt="image" src="https://github.com/TrueBlocks/trueblocks-core/assets/66903336/d496906e-1dfb-4d64-bb8c-b91967279aab">

I can not really use `chifra config edit`, maybe output `trueBlocks.toml` with `chifra config --paths`?

**Comment by tjayrush** [comment]
Thanks so much for your feedback. We'll save this issue and try to incorporate some of your suggestions.

**Comment by Pfed-prog** [comment]
`chifra --help --verbose` provides

 `Error: 
  unknown flag: --verbose`

https://github.com/TrueBlocks/trueblocks-core/tree/master/bin

<img width="167" alt="image" src="https://github.com/TrueBlocks/trueblocks-core/assets/66903336/99d4b066-164d-41c6-8997-1a3913bdc799">

**Comment by Pfed-prog** [comment]
<img width="422" alt="image" src="https://github.com/TrueBlocks/trueblocks-core/assets/66903336/af50810e-2393-43f2-ae84-258073f3c772">

Go version:
<img width="189" alt="image" src="https://github.com/TrueBlocks/trueblocks-core/assets/66903336/1ac389b0-e7ac-454a-a801-ff4a23f0e9a8">

<img width="542" alt="image" src="https://github.com/TrueBlocks/trueblocks-core/assets/66903336/bd405a37-0b22-490d-a0dc-51ae54f448d9">

**Comment by tjayrush** [comment]
we made numerous changes related to how chifra starts up. Hopefully this wlil be fixed. Please re-open if not.
