### ISSUE TITLE
429 too many requests

### ISSUE THREAD

**Issue by Pfed-prog** [TrueBlocks/trueblocks-core#3703]
Any chance to query the data and adapt to alchemy/infura rate limited apis. I get 429 for `chifra export vitalik.eth` from both infura and alchemy.
<img width="1102" alt="image" src="https://github.com/TrueBlocks/trueblocks-core/assets/66903336/179686d3-1e8f-4ffb-811b-e59326bcd7f9">

I am also not sure that even if i purchase a very expensive subscription, the queries will export the data.

**Comment by tjayrush** [comment]
This should be a progressive backoff, so if it hits a 429, it sleeps and if it hits again, it sleeps twice as long, and so on...

There's a `--sleep` option to `chifra slurp` that you can play with. That should help, but it's not progressive.

If you like, please take a stab at making it a progressive backoff. We'll merge it (and finish it if you don't -- testing/documenting/etc.) if you get it started.

**Comment by Pfed-prog** [comment]
> If you like, please take a stab at making it a progressive backoff. We'll merge it (and finish it if you don't -- testing/documenting/etc.) if you get it started.

I am struggling to get started. Are there any developer onboarding resources ?

**Comment by tjayrush** [comment]
Please come into our discord: https://discord.com/invite/kAFcZH2x7K

DM me. I'll help you as much as you need.

**Comment by tjayrush** [comment]
I'll close this assuming we'll be able to help you on discord.
