### ISSUE TITLE
/bin/sh: 1: go: not found on `make`

### ISSUE THREAD

**Issue by Pfed-prog** [TrueBlocks/trueblocks-core#3707]
I have installed chifra, removed build to compile once again. 

Run the installation commands once again and the script says that go is not installed

https://github.com/TrueBlocks/trueblocks-core/issues/3700#issuecomment-2130380906

**Comment by tjayrush** [comment]
I'm going to close this. The second line of this install instruction (here: https://trueblocks.io/docs/install/install-core/) says,

```
Type go version.

If Go is not installed...install the latest version of Go.
```

It even provides a link: https://go.dev/doc/install
