### ISSUE TITLE
Names sharing

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-core#3777]
The end user needs a way to get names locally (so the end user gets what they want -- named addresses), but there needs to be a "sharing" component while still preserving privacy. Something like "I know this address is XYZ contract, and I want to share this with the world" -- chifra names --add --share

and also "I know this addresses, but it would be really bad if it were leaked: chifra names --add --private . (Adding this comment to the issue as well.)

**Comment by dszlachta** [comment]
I'd suggest making `--private` the default. Otherwise it might be too easy to accidentally leak the names

**Comment by tjayrush** [comment]
Totally agree. We want to be super careful that we don't leak names.
