### ISSUE TITLE
chifra locked up

### ISSUE THREAD

**Issue by bonze82** [TrueBlocks/trueblocks-core#3912]
Get this error during chifra status:
EROR[25-11|11:58:06.354] The method 'eth_chainId' is found but the namespace 'Eth' is disabled for http://127.0.0.1:8545. Consider adding the namespace 'Eth' to JsonRpc.AdditionalRpcUrls for an additional URL, or to JsonRpc.EnabledModules for the default URL.

unfortunantly no other chifra commands run without an error and unable to kill current running process

error all chifra commands give exept status not sure what command created this issue:
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 1 [running]:
github.com/TrueBlocks/trueblocks-core/src/apps/chifra/pkg/config.checkUnchainedProvider({0xc000400513, 0x7}, 0xe43a29)
	/data/build/trueblocks-core/src/apps/chifra/pkg/config/config.go:259 +0x86d
github.com/TrueBlocks/trueblocks-core/src/apps/chifra/pkg/config.validateRpcEndpoint({0xc000400513, 0x7}, {0xc000454108, 0x15})
	/data/build/trueblocks-core/src/apps/chifra/pkg/config/config.go:219 +0x1b2
github.com/TrueBlocks/trueblocks-core/src/apps/chifra/pkg/config.GetRootConfig()
	/data/build/trueblocks-core/src/apps/chifra/pkg/config/config.go:125 +0xc37
github.com/TrueBlocks/trueblocks-core/src/apps/chifra/pkg/config.GetSettings(...)
	/data/build/trueblocks-core/src/apps/chifra/pkg/config/settingsGroup.go:10
github.com/TrueBlocks/trueblocks-core/src/apps/chifra/internal/globals.SetDefaults(...)
	/data/build/trueblocks-core/src/apps/chifra/internal/globals/options.go:64
github.com/TrueBlocks/trueblocks-core/src/apps/chifra/internal/globals.InitGlobals({0xd5f5a4, 0x4}, 0x14a0ae0, 0x1501dd8, 0x3fe7)
	/data/build/trueblocks-core/src/apps/chifra/internal/globals/options.go:143 +0x6dd
github.com/TrueBlocks/trueblocks-core/src/apps/chifra/cmd.init.0()
	/data/build/trueblocks-core/src/apps/chifra/cmd/abis.go:66 +0x245

running nethermind with nimbus port 8545 is open and eth namespace is available and enabled.

**Comment by tjayrush** [comment]
I'm not sure I completely understand, but it seems to me that you're not enabling certain RPC namespaces when you start you node software.

Try this:

```
TB_DEBUG_CURL=true chifra blocks 12 >/dev/null
```

This should spit out some debugging information in the form of Curl commands.

Try those commands directly.

If they don't work, then neither will `chifra` and you'll have to start your node with the correct rpc namespaces.

We use this command to start our Erigon node:

```
./build/bin/erigon --datadir /mnt/md0/erigon-devel/ --private.api.addr=localhost:9091 --db.size.limit=8TB --port 30304 --chain mainnet --http --http.api=eth,debug,net,trace,web3,erigon --http.vhosts=host.docker.internal,localhost --snapshots=true
```

Your milage may vary.

**Comment by tjayrush** [comment]
Is this resolved? Please re-open it if you wish.
